import type { ItemDef } from "@/game/types";

/** Density pack — shop/loadout volume. */
export const ITEMS_EXTRA: ItemDef[] = [
  { id: "micro_shim", name: "Micro shim", kind: "tool", baseValue: 95, toolMod: 2, description: "Thin steel for soft latches." },
  { id: "pickup_gun", name: "Pick gun", kind: "tool", baseValue: 1100, toolMod: 6, description: "Noisy if you rush the pins." },
  { id: "torque_wrench", name: "Torque wrench", kind: "tool", baseValue: 280, toolMod: 3, description: "Turns stubborn fasteners quietly enough." },
  { id: "glass_cutter", name: "Glass cutter", kind: "tool", baseValue: 420, toolMod: 4, description: "Score, tap, lift. Watch the edges." },
  { id: "bump_key", name: "Bump key set", kind: "tool", baseValue: 650, toolMod: 5, description: "Old doors love bad habits." },
  { id: "signal_jammer", name: "Pocket jammer", kind: "tool", baseValue: 3200, toolMod: 7, description: "Short window on cheap cameras." },
  { id: "key_cloner", name: "Key cloner wand", kind: "tool", baseValue: 2800, toolMod: 6, description: "Copies soft blanks in a heartbeat." },
  { id: "pry_wedge", name: "Silent pry wedge", kind: "tool", baseValue: 140, toolMod: 2, description: "Door gaps without the clang." },
  { id: "fiber_scope", name: "Fiber scope", kind: "tool", baseValue: 1900, toolMod: 5, description: "See past the gap before you commit." },
  { id: "magnet_wand", name: "Magnet wand", kind: "tool", baseValue: 360, toolMod: 3, description: "Pulls pins and cheap sensors." },
  { id: "ladder_hooks", name: "Roof ladder hooks", kind: "tool", baseValue: 220, toolMod: 2, description: "Up without asking the lobby." },
  { id: "duct_tape_pro", name: "Industrial tape roll", kind: "tool", baseValue: 45, toolMod: 1, description: "Mouths, hinges, and temporary seals." },
  { id: "multimeter", name: "Pocket multimeter", kind: "tool", baseValue: 180, toolMod: 2, description: "Know when the wire is live." },
  { id: "usb_drop", name: "USB drop stick", kind: "tool", baseValue: 900, toolMod: 4, description: "Plant and walk. Firmware does the rest." },
  { id: "rfid_spoof", name: "RFID spoof fob", kind: "tool", baseValue: 2400, toolMod: 6, description: "Badges that blink friendly for a minute." },
  { id: "window_suction", name: "Window cups", kind: "tool", baseValue: 160, toolMod: 2, description: "Lift panes without shattered nerves." },
  { id: "chain_breaker", name: "Chain breaker", kind: "tool", baseValue: 310, toolMod: 3, description: "Bike locks and dock chains." },
  { id: "safe_dial_cam", name: "Dial camera", kind: "tool", baseValue: 1500, toolMod: 5, description: "Watch the wheel without leaning in." },
  { id: "noise_blankets", name: "Noise blankets", kind: "tool", baseValue: 480, toolMod: 3, description: "Muffles drills in soft rooms." },
  { id: "laser_mic", name: "Laser mic kit", kind: "tool", baseValue: 4100, toolMod: 8, description: "Listen through glass. Expensive ears." },
  { id: "cord_ladder", name: "Cord ladder", kind: "tool", baseValue: 340, toolMod: 3, description: "Down the alley side of tall problems." },
  { id: "lock_spray", name: "Lock graphite", kind: "tool", baseValue: 55, toolMod: 1, description: "Sticky pins become polite." },
  { id: "hinge_pins", name: "Hinge pin punch", kind: "tool", baseValue: 90, toolMod: 2, description: "Doors open the wrong way on purpose." },
  { id: "camera_hood", name: "Camera hood", kind: "tool", baseValue: 210, toolMod: 2, description: "Blackout a lens for one sweep." },
  { id: "dock_pass", name: "Dock day pass", kind: "tool", baseValue: 700, toolMod: 3, description: "Looks temporary. Works temporary." },
  { id: "valve_key", name: "Valve key", kind: "tool", baseValue: 130, toolMod: 2, description: "Utility rooms pretend to be locked." },
  { id: "soft_hammer", name: "Dead-blow mallet", kind: "tool", baseValue: 190, toolMod: 2, description: "Impact without the ring." },
  { id: "tie_wraps", name: "Heavy zip ties", kind: "tool", baseValue: 35, toolMod: 1, description: "Temporary restraints and cable management." },
  { id: "paint_marker", name: "UV paint marker", kind: "tool", baseValue: 70, toolMod: 1, description: "Mark drops only you can see." },
  { id: "spare_batteries", name: "Spare cells", kind: "tool", baseValue: 40, toolMod: 1, description: "Keep scanners awake past midnight." },
  { id: "stun_ring", name: "Stun ring", kind: "weapon", baseValue: 420, description: "Close handshake with teeth." },
  { id: "sap_glove", name: "Sap glove", kind: "weapon", baseValue: 380, description: "Weighted palm. Quiet bruise." },
  { id: "pipe_short", name: "Short pipe", kind: "weapon", baseValue: 90, description: "Found metal with intent." },
  { id: "taser_pocket", name: "Pocket taser", kind: "weapon", baseValue: 900, description: "One click of persuasion." },
  { id: "garrote_wire", name: "Garrote wire", kind: "weapon", baseValue: 260, description: "Ugly option. Works." },
  { id: "throwing_knife", name: "Throwing knife", kind: "weapon", baseValue: 310, description: "Reach without commitment." },
  { id: "expand_baton", name: "Expandable baton", kind: "weapon", baseValue: 640, description: "Collapses into a jacket." },
  { id: "pepper_gel", name: "Pepper gel", kind: "weapon", baseValue: 120, description: "Crowd control in a can." },
  { id: "steel_toes", name: "Steel-toe inserts", kind: "weapon", baseValue: 180, description: "Kick with receipts." },
  { id: "chain_whip", name: "Bike chain whip", kind: "weapon", baseValue: 150, description: "Commons classic." },
  { id: "needle_spike", name: "Needle spike", kind: "weapon", baseValue: 200, description: "Clinic-adjacent menace." },
  { id: "blackjack", name: "Leather blackjack", kind: "weapon", baseValue: 340, description: "Old school soft knock." },
  { id: "leather_jacket", name: "Lined leather", kind: "armor", baseValue: 1600, description: "Looks like fashion. Acts like padding." },
  { id: "chain_shirt", name: "Chain shirt", kind: "armor", baseValue: 3400, description: "Heavy under a hoodie." },
  { id: "trauma_plates", name: "Trauma plates", kind: "armor", baseValue: 6100, description: "Stops the first bad idea." },
  { id: "riot_helmet", name: "Riot helmet", kind: "armor", baseValue: 2200, description: "Face stays attached." },
  { id: "cut_gloves", name: "Cut-resistant gloves", kind: "armor", baseValue: 280, description: "Glass and knives argue less." },
  { id: "shin_guards", name: "Shin guards", kind: "armor", baseValue: 420, description: "Alley kicks bounce." },
  { id: "neck_guard", name: "Neck guard", kind: "armor", baseValue: 900, description: "Ugly accessory that saves throats." },
  { id: "ballistic_hoodie", name: "Ballistic hoodie", kind: "armor", baseValue: 4800, description: "Street fashion with a rating." },
  { id: "clinic_apron", name: "Lead clinic apron", kind: "armor", baseValue: 1100, description: "Looks medical. Stops scrapes." },
  { id: "dock_harness", name: "Dock harness", kind: "armor", baseValue: 750, description: "Fall arrest and punch absorb." },
  { id: "smoke_tabs", name: "Smoke tabs", kind: "consumable", baseValue: 80, description: "+8 happy, soft cover myth." },
  { id: "calm_tea", name: "Calm tea", kind: "consumable", baseValue: 45, description: "-6 stress, warm hands." },
  { id: "sugar_rush", name: "Sugar rush pack", kind: "consumable", baseValue: 20, description: "+8 happy, short buzz." },
  { id: "blood_patch", name: "Blood patch", kind: "consumable", baseValue: 110, description: "+18 life, sticky." },
  { id: "nerve_tonic", name: "Nerve tonic", kind: "consumable", baseValue: 140, description: "-8 stress, sharper feel." },
  { id: "ice_pack", name: "Gel ice pack", kind: "consumable", baseValue: 35, description: "+8 life, -3 stress." },
  { id: "antibiotic", name: "Street antibiotics", kind: "consumable", baseValue: 95, description: "+12 life over a slow hour." },
  { id: "sleeping_draft", name: "Sleeping draft", kind: "consumable", baseValue: 160, description: "-12 stress, heavy eyelids." },
  { id: "steroid_shot", name: "Gray-market shot", kind: "consumable", baseValue: 280, description: "+20 life, loud heart." },
  { id: "detox_charcoal", name: "Detox charcoal", kind: "consumable", baseValue: 70, description: "-5 stress, bitter exit." },
  { id: "bandage_kit", name: "Field bandage kit", kind: "consumable", baseValue: 55, description: "+14 life." },
  { id: "caffeine_tabs", name: "Caffeine tabs", kind: "consumable", baseValue: 30, description: "+6 happy, jitter tax." },
  { id: "morphine_vial", name: "Morphine vial", kind: "consumable", baseValue: 320, description: "+30 life, -10 stress." },
  { id: "epinephrine", name: "Epi pen street", kind: "consumable", baseValue: 240, description: "+22 life fast." },
  { id: "herbal_wrap", name: "Herbal wrap", kind: "consumable", baseValue: 50, description: "+10 life, smells like Millstone." },
  { id: "booster_vial", name: "Booster vial", kind: "consumable", baseValue: 180, description: "+15 life, +5 happy." },
  { id: "salt_tabs", name: "Salt tabs", kind: "consumable", baseValue: 25, description: "+5 life after a long walk." },
  { id: "lube_spray", name: "Quiet hinge oil", kind: "consumable", baseValue: 40, description: "Doors stop announcing you." },
  { id: "chalk_dust", name: "Chalk dust pouch", kind: "consumable", baseValue: 15, description: "Prints smear. Cheap trick." },
  { id: "flare_stick", name: "Flare stick", kind: "consumable", baseValue: 60, description: "Distraction light. Hot exit." },
  { id: "foam_earplugs", name: "Foam earplugs", kind: "consumable", baseValue: 12, description: "-2 stress in loud rooms." },
  { id: "glucose_gel", name: "Glucose gel", kind: "consumable", baseValue: 22, description: "+6 happy, quick sugar." },
  { id: "antiseptic", name: "Antiseptic spray", kind: "consumable", baseValue: 48, description: "+10 life, sting included." },
  { id: "cooling_rag", name: "Cooling rag", kind: "consumable", baseValue: 18, description: "-4 stress, pier nights." },
  { id: "ward_snack", name: "Ward snack pack", kind: "consumable", baseValue: 28, description: "+10 happy, clinic vending." },
  { id: "pier_soda", name: "Pier soda", kind: "consumable", baseValue: 16, description: "+7 happy, neon sugar." },
  { id: "blank_invoice", name: "Blank invoice pad", kind: "misc", baseValue: 220, description: "Paper that looks like money owed." },
  { id: "courier_tag", name: "Courier route tag", kind: "misc", baseValue: 180, description: "Bags move when tags match." },
  { id: "pawn_ticket", name: "Warm pawn ticket", kind: "misc", baseValue: 90, description: "Someone else's collateral." },
  { id: "usb_dead", name: "Dead drop USB", kind: "misc", baseValue: 400, description: "Encrypted nothing until it isn't." },
  { id: "press_pass", name: "Press pass blank", kind: "misc", baseValue: 850, description: "Lobby doors love clipboards." },
  { id: "valet_chip", name: "Valet chip", kind: "misc", baseValue: 320, description: "Cars that aren't yours answer." },
  { id: "hotel_key", name: "Hotel master blank", kind: "misc", baseValue: 1200, description: "Soft floors, softer locks." },
  { id: "tram_pass", name: "All-night tram pass", kind: "misc", baseValue: 60, description: "Ride without questions." },
  { id: "locker_tag", name: "Gym locker tag", kind: "misc", baseValue: 40, description: "Wrong locker, right contents." },
  { id: "cargo_seal", name: "Cargo seal stamp", kind: "misc", baseValue: 980, description: "Manifest fiction in rubber." },
  { id: "clinic_badge", name: "Clinic visitor badge", kind: "misc", baseValue: 540, description: "Ward doors blink once." },
  { id: "festival_wrist", name: "Festival wristband", kind: "misc", baseValue: 75, description: "Crowds become cover." },
  { id: "spy_mirror", name: "Spy mirror", kind: "misc", baseValue: 110, description: "Corners stop surprising you." },
  { id: "voice_changer", name: "Voice changer", kind: "misc", baseValue: 700, description: "Calls that aren't your throat." },
  { id: "map_annotated", name: "Annotated alley map", kind: "misc", baseValue: 150, description: "Shortcuts the tram ignores." },
  { id: "bribe_envelope", name: "Bribe envelope", kind: "misc", baseValue: 2000, description: "Cash shaped like a problem solved." },
  { id: "witness_photo", name: "Witness polaroid", kind: "misc", baseValue: 300, description: "Leverage that fits a pocket." },
  { id: "counterfeit_chip", name: "Counterfeit chip", kind: "misc", baseValue: 450, description: "Cage math with a limp." },
  { id: "shipping_label", name: "Shipping label kit", kind: "misc", baseValue: 260, description: "Crates go where paper says." },
  { id: "burner_phone", name: "Burner phone", kind: "misc", baseValue: 120, description: "One conversation, then trash." },
  { id: "sim_pack", name: "Prepaid SIM pack", kind: "misc", baseValue: 80, description: "Numbers that expire with the night." },
  { id: "notebook_cipher", name: "Cipher notebook", kind: "misc", baseValue: 190, description: "Names in a grammar only you keep." },
  { id: "dummy_wallet", name: "Dummy wallet", kind: "misc", baseValue: 55, description: "Give them something to steal." },
  { id: "decoy_bag", name: "Decoy courier bag", kind: "misc", baseValue: 340, description: "Heavy sand, light consequences." },
  { id: "evidence_bag", name: "Evidence bag blank", kind: "misc", baseValue: 160, description: "Looks official. Isn't." },
  { id: "key_ring_dummy", name: "Dummy key ring", kind: "misc", baseValue: 45, description: "Jingles like authority." },
  { id: "parking_permit", name: "Parking permit fake", kind: "misc", baseValue: 210, description: "Spire curb theater." },
  { id: "club_stamp", name: "Club re-entry stamp", kind: "misc", baseValue: 35, description: "Pier doors remember ink." },
  { id: "silver_rings", name: "Silver ring stack", kind: "flex", baseValue: 3200, description: "Respect that stacks on knuckles." },
  { id: "silk_scarf", name: "Silk scarf", kind: "flex", baseValue: 1800, description: "Soft money signal." },
  { id: "designer_shades", name: "Designer shades", kind: "flex", baseValue: 2600, description: "Eyes that don't flinch." },
  { id: "cufflinks", name: "Spire cufflinks", kind: "flex", baseValue: 5200, description: "Lobby grammar." },
  { id: "fur_collar", name: "Fur collar wrap", kind: "flex", baseValue: 7800, description: "Neon cold-weather flex." },
  { id: "custom_sneakers", name: "Custom sneakers", kind: "flex", baseValue: 2400, description: "Street respect underfoot." },
  { id: "platinum_tooth", name: "Platinum tooth", kind: "flex", baseValue: 4100, description: "Smile that invoices." },
  { id: "leather_briefcase", name: "Leather briefcase", kind: "flex", baseValue: 3600, description: "Looks like clean work." },
  { id: "monogram_case", name: "Monogram case", kind: "flex", baseValue: 6400, description: "Initials the desk notices." },
  { id: "velvet_blazer", name: "Velvet blazer", kind: "flex", baseValue: 8900, description: "Pier VIP without the rope." },
  { id: "diamond_stud", name: "Diamond stud", kind: "flex", baseValue: 12000, description: "One stone, many stares." },
  { id: "chrome_lighter", name: "Chrome lighter", kind: "flex", baseValue: 900, description: "Click that ends arguments." },
  { id: "perfume_vial", name: "Signature perfume", kind: "flex", baseValue: 1400, description: "Walk into a room already known." },
  { id: "tailored_coat", name: "Tailored night coat", kind: "flex", baseValue: 11000, description: "Heat looks expensive in this cut." },
  { id: "obsidian_ring", name: "Obsidian ring", kind: "flex", baseValue: 4700, description: "Dark stone, darker rooms." },
  { id: "pearl_choker", name: "Pearl choker", kind: "flex", baseValue: 6800, description: "Boardwalk money on a throat." },
  { id: "ivory_comb", name: "Ivory comb", kind: "flex", baseValue: 2100, description: "Grooming as status." },
  { id: "gilt_flask", name: "Gilt flask", kind: "flex", baseValue: 3300, description: "Drinks that look like deals." },
  { id: "satin_gloves", name: "Satin gloves", kind: "flex", baseValue: 1900, description: "Soft hands, hard reputation." },
  { id: "opera_glasses", name: "Opera glasses", kind: "flex", baseValue: 2800, description: "Spire balconies love toys." },
  { id: "angle_pick_0", name: "Angle pick", kind: "misc", baseValue: 40, description: "Fenceable pick. Nightwire scrap #0." },
  { id: "offset_pick_1", name: "Offset pick", kind: "tool", baseValue: 57, toolMod: 2, description: "Offset pick for soft entry and stubborn doors." },
  { id: "slim_pick_2", name: "Slim pick", kind: "tool", baseValue: 74, toolMod: 3, description: "Slim pick for soft entry and stubborn doors." },
  { id: "heavy_pick_3", name: "Heavy pick", kind: "tool", baseValue: 91, toolMod: 4, description: "Heavy pick for soft entry and stubborn doors." },
  { id: "quiet_pick_4", name: "Quiet pick", kind: "tool", baseValue: 108, toolMod: 5, description: "Quiet pick for soft entry and stubborn doors." },
  { id: "field_pick_5", name: "Field pick", kind: "misc", baseValue: 125, description: "Fenceable pick. Nightwire scrap #5." },
  { id: "night_pick_6", name: "Night pick", kind: "tool", baseValue: 142, toolMod: 1, description: "Night pick for soft entry and stubborn doors." },
  { id: "yard_pick_7", name: "Yard pick", kind: "consumable", baseValue: 159, description: "Field kit 7. Soft recover." },
  { id: "harbor_pick_8", name: "Harbor pick", kind: "tool", baseValue: 176, toolMod: 3, description: "Harbor pick for soft entry and stubborn doors." },
  { id: "ward_pick_9", name: "Ward pick", kind: "tool", baseValue: 193, toolMod: 4, description: "Ward pick for soft entry and stubborn doors." },
  { id: "mesh_pick_10", name: "Mesh pick", kind: "misc", baseValue: 210, description: "Fenceable pick. Nightwire scrap #10." },
  { id: "alloy_pick_11", name: "Alloy pick", kind: "tool", baseValue: 227, toolMod: 6, description: "Alloy pick for soft entry and stubborn doors." },
  { id: "carbon_pick_12", name: "Carbon pick", kind: "tool", baseValue: 244, toolMod: 1, description: "Carbon pick for soft entry and stubborn doors." },
  { id: "titanium_pick_13", name: "Titanium pick", kind: "tool", baseValue: 261, toolMod: 2, description: "Titanium pick for soft entry and stubborn doors." },
  { id: "ceramic_pick_14", name: "Ceramic pick", kind: "consumable", baseValue: 278, description: "Field kit 14. Soft recover." },
  { id: "polymer_pick_15", name: "Polymer pick", kind: "misc", baseValue: 295, description: "Fenceable pick. Nightwire scrap #15." },
  { id: "brass_pick_16", name: "Brass pick", kind: "tool", baseValue: 312, toolMod: 5, description: "Brass pick for soft entry and stubborn doors." },
  { id: "steel_pick_17", name: "Steel pick", kind: "tool", baseValue: 329, toolMod: 6, description: "Steel pick for soft entry and stubborn doors." },
  { id: "matte_pick_18", name: "Matte pick", kind: "tool", baseValue: 346, toolMod: 1, description: "Matte pick for soft entry and stubborn doors." },
  { id: "ghost_pick_19", name: "Ghost pick", kind: "tool", baseValue: 363, toolMod: 2, description: "Ghost pick for soft entry and stubborn doors." },
  { id: "angle_shim_20", name: "Angle shim", kind: "misc", baseValue: 380, description: "Fenceable shim. Nightwire scrap #20." },
  { id: "offset_shim_21", name: "Offset shim", kind: "consumable", baseValue: 397, description: "Field kit 21. Soft recover." },
  { id: "slim_shim_22", name: "Slim shim", kind: "tool", baseValue: 414, toolMod: 5, description: "Slim shim for soft entry and stubborn doors." },
  { id: "heavy_shim_23", name: "Heavy shim", kind: "tool", baseValue: 431, toolMod: 6, description: "Heavy shim for soft entry and stubborn doors." },
  { id: "quiet_shim_24", name: "Quiet shim", kind: "tool", baseValue: 448, toolMod: 1, description: "Quiet shim for soft entry and stubborn doors." },
  { id: "field_shim_25", name: "Field shim", kind: "misc", baseValue: 465, description: "Fenceable shim. Nightwire scrap #25." },
  { id: "night_shim_26", name: "Night shim", kind: "tool", baseValue: 482, toolMod: 3, description: "Night shim for soft entry and stubborn doors." },
  { id: "yard_shim_27", name: "Yard shim", kind: "tool", baseValue: 499, toolMod: 4, description: "Yard shim for soft entry and stubborn doors." },
  { id: "harbor_shim_28", name: "Harbor shim", kind: "consumable", baseValue: 516, description: "Field kit 28. Soft recover." },
  { id: "ward_shim_29", name: "Ward shim", kind: "tool", baseValue: 533, toolMod: 6, description: "Ward shim for soft entry and stubborn doors." },
  { id: "mesh_shim_30", name: "Mesh shim", kind: "misc", baseValue: 550, description: "Fenceable shim. Nightwire scrap #30." },
  { id: "alloy_shim_31", name: "Alloy shim", kind: "tool", baseValue: 567, toolMod: 2, description: "Alloy shim for soft entry and stubborn doors." },
  { id: "carbon_shim_32", name: "Carbon shim", kind: "tool", baseValue: 584, toolMod: 3, description: "Carbon shim for soft entry and stubborn doors." },
  { id: "titanium_shim_33", name: "Titanium shim", kind: "tool", baseValue: 601, toolMod: 4, description: "Titanium shim for soft entry and stubborn doors." },
];
