import type { CodexEntry, CrimeFamily, ResultOutcome } from "@/content/lore";

export const HEADLINES_EXTRA: string[] = [
  "Glassrow: patrol budget — nightwire desk notes #1",
  "Millstone: camera maintenance — nightwire desk notes #2",
  "DocksReach: tram delay — nightwire desk notes #3",
  "Ashcourt: pier rumor — nightwire desk notes #4",
  "SpireYard: ward overtime — nightwire desk notes #5",
  "OldCommons: vault premium — nightwire desk notes #6",
  "Neon Pier: crane overtime — nightwire desk notes #7",
  "Red Clinic: festival egress — nightwire desk notes #8",
  "Glassrow: fence network — nightwire desk notes #9",
  "Millstone: scholarship freeze — nightwire desk notes #10",
  "DocksReach: rival tag — nightwire desk notes #11",
  "Ashcourt: chip float — nightwire desk notes #12",
  "SpireYard: evidence reconcile — nightwire desk notes #13",
  "OldCommons: soft-house lease — nightwire desk notes #14",
  "Neon Pier: gym bruise report — nightwire desk notes #15",
  "Red Clinic: lobby silence — nightwire desk notes #16",
  "Glassrow: customs shrug — nightwire desk notes #17",
  "Millstone: alley ledger — nightwire desk notes #18",
  "DocksReach: mesh flicker — nightwire desk notes #19",
  "Ashcourt: clinic diversion — nightwire desk notes #20",
  "SpireYard: patrol budget — nightwire desk notes #21",
  "OldCommons: camera maintenance — nightwire desk notes #22",
  "Neon Pier: tram delay — nightwire desk notes #23",
  "Red Clinic: pier rumor — nightwire desk notes #24",
  "Glassrow: ward overtime — nightwire desk notes #25",
  "Millstone: vault premium — nightwire desk notes #26",
  "DocksReach: crane overtime — nightwire desk notes #27",
  "Ashcourt: festival egress — nightwire desk notes #28",
  "SpireYard: fence network — nightwire desk notes #29",
  "OldCommons: scholarship freeze — nightwire desk notes #30",
  "Neon Pier: rival tag — nightwire desk notes #31",
  "Red Clinic: chip float — nightwire desk notes #32",
  "Glassrow: evidence reconcile — nightwire desk notes #33",
  "Millstone: soft-house lease — nightwire desk notes #34",
  "DocksReach: gym bruise report — nightwire desk notes #35",
  "Ashcourt: lobby silence — nightwire desk notes #36",
  "SpireYard: customs shrug — nightwire desk notes #37",
  "OldCommons: alley ledger — nightwire desk notes #38",
  "Neon Pier: mesh flicker — nightwire desk notes #39",
  "Red Clinic: clinic diversion — nightwire desk notes #40",
  "Glassrow: patrol budget — nightwire desk notes #41",
  "Millstone: camera maintenance — nightwire desk notes #42",
  "DocksReach: tram delay — nightwire desk notes #43",
  "Ashcourt: pier rumor — nightwire desk notes #44",
  "SpireYard: ward overtime — nightwire desk notes #45",
  "OldCommons: vault premium — nightwire desk notes #46",
  "Neon Pier: crane overtime — nightwire desk notes #47",
  "Red Clinic: festival egress — nightwire desk notes #48",
  "Glassrow: fence network — nightwire desk notes #49",
  "Millstone: scholarship freeze — nightwire desk notes #50",
  "DocksReach: rival tag — nightwire desk notes #51",
  "Ashcourt: chip float — nightwire desk notes #52",
  "SpireYard: evidence reconcile — nightwire desk notes #53",
  "OldCommons: soft-house lease — nightwire desk notes #54",
  "Neon Pier: gym bruise report — nightwire desk notes #55",
  "Red Clinic: lobby silence — nightwire desk notes #56",
  "Glassrow: customs shrug — nightwire desk notes #57",
  "Millstone: alley ledger — nightwire desk notes #58",
  "DocksReach: mesh flicker — nightwire desk notes #59",
  "Ashcourt: clinic diversion — nightwire desk notes #60",
  "SpireYard: patrol budget — nightwire desk notes #61",
  "OldCommons: camera maintenance — nightwire desk notes #62",
  "Neon Pier: tram delay — nightwire desk notes #63",
  "Red Clinic: pier rumor — nightwire desk notes #64",
  "Glassrow: ward overtime — nightwire desk notes #65",
  "Millstone: vault premium — nightwire desk notes #66",
  "DocksReach: crane overtime — nightwire desk notes #67",
  "Ashcourt: festival egress — nightwire desk notes #68",
  "SpireYard: fence network — nightwire desk notes #69",
  "OldCommons: scholarship freeze — nightwire desk notes #70",
  "Neon Pier: rival tag — nightwire desk notes #71",
  "Red Clinic: chip float — nightwire desk notes #72",
  "Glassrow: evidence reconcile — nightwire desk notes #73",
  "Millstone: soft-house lease — nightwire desk notes #74",
  "DocksReach: gym bruise report — nightwire desk notes #75",
  "Ashcourt: lobby silence — nightwire desk notes #76",
  "SpireYard: customs shrug — nightwire desk notes #77",
  "OldCommons: alley ledger — nightwire desk notes #78",
  "Neon Pier: mesh flicker — nightwire desk notes #79",
  "Red Clinic: clinic diversion — nightwire desk notes #80",
  "Glassrow: patrol budget — nightwire desk notes #81",
  "Millstone: camera maintenance — nightwire desk notes #82",
  "DocksReach: tram delay — nightwire desk notes #83",
  "Ashcourt: pier rumor — nightwire desk notes #84",
  "SpireYard: ward overtime — nightwire desk notes #85",
  "OldCommons: vault premium — nightwire desk notes #86",
  "Neon Pier: crane overtime — nightwire desk notes #87",
  "Red Clinic: festival egress — nightwire desk notes #88",
  "Glassrow: fence network — nightwire desk notes #89",
  "Millstone: scholarship freeze — nightwire desk notes #90",
  "DocksReach: rival tag — nightwire desk notes #91",
  "Ashcourt: chip float — nightwire desk notes #92",
  "SpireYard: evidence reconcile — nightwire desk notes #93",
  "OldCommons: soft-house lease — nightwire desk notes #94",
  "Neon Pier: gym bruise report — nightwire desk notes #95",
  "Red Clinic: lobby silence — nightwire desk notes #96",
  "Glassrow: customs shrug — nightwire desk notes #97",
  "Millstone: alley ledger — nightwire desk notes #98",
  "DocksReach: mesh flicker — nightwire desk notes #99",
  "Ashcourt: clinic diversion — nightwire desk notes #100",
  "SpireYard: patrol budget — nightwire desk notes #101",
  "OldCommons: camera maintenance — nightwire desk notes #102",
  "Neon Pier: tram delay — nightwire desk notes #103",
  "Red Clinic: pier rumor — nightwire desk notes #104",
  "Glassrow: ward overtime — nightwire desk notes #105",
  "Millstone: vault premium — nightwire desk notes #106",
  "DocksReach: crane overtime — nightwire desk notes #107",
  "Ashcourt: festival egress — nightwire desk notes #108",
  "SpireYard: fence network — nightwire desk notes #109",
  "OldCommons: scholarship freeze — nightwire desk notes #110",
  "Neon Pier: rival tag — nightwire desk notes #111",
  "Red Clinic: chip float — nightwire desk notes #112",
  "Glassrow: evidence reconcile — nightwire desk notes #113",
  "Millstone: soft-house lease — nightwire desk notes #114",
  "DocksReach: gym bruise report — nightwire desk notes #115",
  "Ashcourt: lobby silence — nightwire desk notes #116",
  "SpireYard: customs shrug — nightwire desk notes #117",
  "OldCommons: alley ledger — nightwire desk notes #118",
  "Neon Pier: mesh flicker — nightwire desk notes #119",
  "Red Clinic: clinic diversion — nightwire desk notes #120",
  "Glassrow: patrol budget — nightwire desk notes #121",
  "Millstone: camera maintenance — nightwire desk notes #122",
  "DocksReach: tram delay — nightwire desk notes #123",
  "Ashcourt: pier rumor — nightwire desk notes #124",
  "SpireYard: ward overtime — nightwire desk notes #125",
  "OldCommons: vault premium — nightwire desk notes #126",
  "Neon Pier: crane overtime — nightwire desk notes #127",
  "Red Clinic: festival egress — nightwire desk notes #128",
  "Glassrow: fence network — nightwire desk notes #129",
  "Millstone: scholarship freeze — nightwire desk notes #130",
  "DocksReach: rival tag — nightwire desk notes #131",
  "Ashcourt: chip float — nightwire desk notes #132",
  "SpireYard: evidence reconcile — nightwire desk notes #133",
  "OldCommons: soft-house lease — nightwire desk notes #134",
  "Neon Pier: gym bruise report — nightwire desk notes #135",
  "Red Clinic: lobby silence — nightwire desk notes #136",
  "Glassrow: customs shrug — nightwire desk notes #137",
  "Millstone: alley ledger — nightwire desk notes #138",
  "DocksReach: mesh flicker — nightwire desk notes #139",
  "Ashcourt: clinic diversion — nightwire desk notes #140",
  "SpireYard: patrol budget — nightwire desk notes #141",
  "OldCommons: camera maintenance — nightwire desk notes #142",
  "Neon Pier: tram delay — nightwire desk notes #143",
  "Red Clinic: pier rumor — nightwire desk notes #144",
  "Glassrow: ward overtime — nightwire desk notes #145",
  "Millstone: vault premium — nightwire desk notes #146",
  "DocksReach: crane overtime — nightwire desk notes #147",
  "Ashcourt: festival egress — nightwire desk notes #148",
  "SpireYard: fence network — nightwire desk notes #149",
  "OldCommons: scholarship freeze — nightwire desk notes #150",
  "Neon Pier: rival tag — nightwire desk notes #151",
  "Red Clinic: chip float — nightwire desk notes #152",
  "Glassrow: evidence reconcile — nightwire desk notes #153",
  "Millstone: soft-house lease — nightwire desk notes #154",
  "DocksReach: gym bruise report — nightwire desk notes #155",
  "Ashcourt: lobby silence — nightwire desk notes #156",
  "SpireYard: customs shrug — nightwire desk notes #157",
  "OldCommons: alley ledger — nightwire desk notes #158",
  "Neon Pier: mesh flicker — nightwire desk notes #159",
  "Red Clinic: clinic diversion — nightwire desk notes #160",
  "Anonymous tip claims SpireYard vault drills ran past dawn",
  "Millstone dogs quiet for an hour — yard bosses deny treat deal",
  "Neon Pier photo booth prints go missing mid-weekend",
  "Red Clinic morphine count ‘almost’ matches again",
  "OldCommons stoop auction sells a key that shouldn’t exist",
  "Glassrow hostess union petitions for later last-call",
  "DocksReach bosun radio caught speaking two languages at once",
  "Ashcourt records aide promoted — files follow her",
  "City mesh ping spikes whenever festival lights brown out",
  "Lawyer retainers climb faster than tram fares",
  "Pawn ticket surge after catalytic week",
  "Harbor soft-house listings scrubbed then reposted",
  "Campus waitlists longer than pier lines",
  "Rival ink appears under three tram maps same night",
  "Bank clerks whisper about nests that never sleep",
];

export const CODEX_EXTRA: CodexEntry[] = [
  {
    id: "dist_neonpier",
    category: "district",
    title: "Neon Pier",
    body: "Boardwalk neon, tourist math, and velvet ropes that double as ledgers. Loud stock, louder nights — heat rides the water.",
    hint: "Travel to Neon Pier.",
  },
  {
    id: "dist_redclinic",
    category: "district",
    title: "Red Clinic",
    body: "Sirens as metronome. Ward doors, surplus meds, and admin suites that look civic until the badge blinks wrong.",
    hint: "Travel to Red Clinic.",
  },
  {
    id: "sys_missions",
    category: "system",
    title: "Contracts board",
    body: "Missions are timed contracts — accept, hit objectives, collect. Miss the window and heat sticks.",
    hint: "Accept any mission.",
  },
  {
    id: "sys_shops",
    category: "system",
    title: "Named counters",
    body: "Twelve counters, not one till. Elite wants clean; black boxes take street under visit caps.",
    hint: "Visit any shop.",
  },
  {
    id: "sys_loadout",
    category: "system",
    title: "Loadout grammar",
    body: "Tools, weapons, armor, flex — equip what the night needs. Tool mods whisper into crime odds.",
    hint: "Equip any item.",
  },
  {
    id: "sys_ranks",
    category: "system",
    title: "Rank titles",
    body: "Titles are costumes until the paper stops hedging. Climb is score-gated, not gift-wrapped.",
    hint: "Reach rank Hustler+.",
  },
  {
    id: "sys_awards",
    category: "system",
    title: "Awards wall",
    body: "Original Nightwire ink — milestones that remember your noise without Torn titles.",
    hint: "Unlock any award.",
  },
  {
    id: "sys_gym",
    category: "system",
    title: "Iron hours",
    body: "Soft caps notice gym sessions. Str/def/spd/dex tracks are the body résumé.",
    hint: "Train at the gym.",
  },
  {
    id: "sys_travel",
    category: "system",
    title: "District rails",
    body: "Eight stamps. Travel costs time and clean; shortcuts live in maps and garage rooms.",
    hint: "Travel between districts.",
  },
  {
    id: "sys_inventory",
    category: "system",
    title: "Pockets & fences",
    body: "Items fence, stack, and unlock missions. Burn kits and lawyer cards are counterplay, not cosmetics.",
    hint: "Buy or loot an item.",
  },
  {
    id: "sys_energy",
    category: "system",
    title: "Energy & nerve",
    body: "Energy fuels work and travel; nerve fuels crime. Both regen — neither forgives spam.",
    hint: "Spend energy or nerve.",
  },
  {
    id: "sys_stress",
    category: "system",
    title: "Stress ledger",
    body: "Stress taxes odds and mood. Calm tea and lay-low are cheaper than hospital clocks.",
    hint: "Hit stress 20+.",
  },
  {
    id: "sys_legitimacy",
    category: "system",
    title: "Legitimacy mask",
    body: "Civic points open soft doors. Pure street stalls political capital; hybrid wears both.",
    hint: "Gain legitimacy.",
  },
  {
    id: "sys_respect",
    category: "system",
    title: "Street respect",
    body: "Respect is alley currency. Fights, boards, and loud takes mint it.",
    hint: "Gain respect.",
  },
  {
    id: "sys_adult",
    category: "system",
    title: "Adult voice gate",
    body: "Some nightlife dossiers carry a second voice. Settings keep it optional; catalog keeps it female-tagged only.",
    hint: "Toggle adult NPC voice in settings.",
  },
  {
    id: "sys_newspaper",
    category: "system",
    title: "City desk",
    body: "Headlines rotate; reactive ink answers your flags. The paper is a mirror with an agenda.",
    hint: "Open the newspaper.",
  },
  {
    id: "sys_timeline",
    category: "system",
    title: "Timeline tape",
    body: "Actions leave tape. Timeline is memory you can scroll when the city gaslights you.",
    hint: "Generate any log line.",
  },
  {
    id: "story_pier_first",
    category: "story",
    title: "First pier night",
    body: "Neon on water. Tourists tip; locals linger. The boardwalk writes you in gossip before ink.",
    hint: "Visit Neon Pier.",
  },
  {
    id: "story_clinic_first",
    category: "story",
    title: "First ward hour",
    body: "Sirens closer than neon. Meds cheaper; questions more expensive.",
    hint: "Visit Red Clinic.",
  },
  {
    id: "story_mission_one",
    category: "story",
    title: "First contract",
    body: "A board stamped your name. Deadlines are a second heat.",
    hint: "Complete one mission.",
  },
  {
    id: "story_property_two",
    category: "story",
    title: "Second roof",
    body: "Two keys. Rent starts arguing with itself.",
    hint: "Own two properties.",
  },
  {
    id: "story_rank_operator",
    category: "story",
    title: "Operator ink",
    body: "The paper stops calling you nobody.",
    hint: "Reach Operator rank.",
  },
  {
    id: "story_attack_five",
    category: "story",
    title: "Five marks",
    body: "Five wins. Alleys remember silhouettes.",
    hint: "Win five NPC attacks.",
  },
  {
    id: "story_course_three",
    category: "story",
    title: "Three transcripts",
    body: "Campus ribbon stack. Edges multiply.",
    hint: "Finish three courses.",
  },
  {
    id: "story_heist_one",
    category: "story",
    title: "First board close",
    body: "Prep spine held. Execute sang — or limped.",
    hint: "Complete one heist.",
  },
  {
    id: "story_bank_nest_big",
    category: "story",
    title: "Bigger nest",
    body: "Twenty-five grand under glass. Clerks notice careers.",
    hint: "Bank $25,000+.",
  },
  {
    id: "story_heat_siren",
    category: "story",
    title: "Siren choir",
    body: "Heat past a hundred. Soft voices get loud.",
    hint: "Peak heat 100+.",
  },
  {
    id: "story_gig_ten",
    category: "story",
    title: "Ten gigs",
    body: "Short contracts become a circuit.",
    hint: "Complete 10 gigs.",
  },
  {
    id: "story_shift_twenty",
    category: "story",
    title: "Twenty shifts",
    body: "Still punching in. Roster knows your face.",
    hint: "Work 20 shifts.",
  },
  {
    id: "story_flex",
    category: "story",
    title: "Flex signal",
    body: "Wear money. Respect notices fabric.",
    hint: "Own a flex item.",
  },
  {
    id: "story_tool_pro",
    category: "story",
    title: "Pro kit",
    body: "Serious entry tools. Doors change tone.",
    hint: "Own lockpicks or better.",
  },
  {
    id: "story_district_all",
    category: "story",
    title: "Eight stamps",
    body: "Every district underfoot. Traveler status.",
    hint: "Visit all 8 districts.",
  },
  {
    id: "dens_system_0",
    category: "system",
    title: "Alley note",
    body: "Nightwire field note on alley: the city keeps score even when you don't.",
    hint: "Play on the wire.",
  },
  {
    id: "dens_story_1",
    category: "story",
    title: "Vault note",
    body: "Nightwire field note on vault: the city keeps score even when you don't.",
    hint: "Play on the wire.",
  },
  {
    id: "dens_school_2",
    category: "school",
    title: "Tram note",
    body: "Nightwire field note on tram: the city keeps score even when you don't.",
    hint: "Complete any course.",
  },
  {
    id: "dens_system_3",
    category: "system",
    title: "Crane note",
    body: "Nightwire field note on crane: the city keeps score even when you don't.",
    hint: "Play on the wire.",
  },
  {
    id: "dens_story_4",
    category: "story",
    title: "Badge note",
    body: "Nightwire field note on badge: the city keeps score even when you don't.",
    hint: "Play on the wire.",
  },
  {
    id: "dens_school_5",
    category: "school",
    title: "Chip note",
    body: "Nightwire field note on chip: the city keeps score even when you don't.",
    hint: "Complete any course.",
  },
  {
    id: "dens_system_6",
    category: "system",
    title: "Mesh note",
    body: "Nightwire field note on mesh: the city keeps score even when you don't.",
    hint: "Play on the wire.",
  },
  {
    id: "dens_story_7",
    category: "story",
    title: "Stoop note",
    body: "Nightwire field note on stoop: the city keeps score even when you don't.",
    hint: "Play on the wire.",
  },
  {
    id: "dens_school_8",
    category: "school",
    title: "Ward note",
    body: "Nightwire field note on ward: the city keeps score even when you don't.",
    hint: "Complete any course.",
  },
  {
    id: "dens_system_9",
    category: "system",
    title: "Lobby note",
    body: "Nightwire field note on lobby: the city keeps score even when you don't.",
    hint: "Play on the wire.",
  },
  {
    id: "dens_story_10",
    category: "story",
    title: "Manifest note",
    body: "Nightwire field note on manifest: the city keeps score even when you don't.",
    hint: "Play on the wire.",
  },
  {
    id: "dens_school_11",
    category: "school",
    title: "Festival note",
    body: "Nightwire field note on festival: the city keeps score even when you don't.",
    hint: "Complete any course.",
  },
  {
    id: "dens_system_12",
    category: "system",
    title: "Harbor note",
    body: "Nightwire field note on harbor: the city keeps score even when you don't.",
    hint: "Play on the wire.",
  },
  {
    id: "dens_story_13",
    category: "story",
    title: "Clinic note",
    body: "Nightwire field note on clinic: the city keeps score even when you don't.",
    hint: "Play on the wire.",
  },
  {
    id: "dens_school_14",
    category: "school",
    title: "Broker note",
    body: "Nightwire field note on broker: the city keeps score even when you don't.",
    hint: "Complete any course.",
  },
  {
    id: "dens_system_15",
    category: "system",
    title: "Runner note",
    body: "Nightwire field note on runner: the city keeps score even when you don't.",
    hint: "Play on the wire.",
  },
];

export const CRIME_RESULT_COPY_EXTRA: Record<CrimeFamily, Record<ResultOutcome, string[]>> = {
  "petty": {
    "SUCCESS": [
      "lift the crowd — City barely shrugs. (petty/SUCCESS)",
      "skim the ward — Exit messy. (petty/SUCCESS)",
      "lift the crowd — City barely shrugs. (petty/SUCCESS)",
      "skim the ward — Exit messy. (petty/SUCCESS)",
      "lift the crowd — City barely shrugs. (petty/SUCCESS)",
      "skim the ward — Exit messy. (petty/SUCCESS)",
      "lift the crowd — City barely shrugs. (petty/SUCCESS)",
      "skim the ward — Exit messy. (petty/SUCCESS)",
      "lift the crowd — City barely shrugs. (petty/SUCCESS)",
      "skim the ward — Exit messy. (petty/SUCCESS)",
      "lift the crowd — City barely shrugs. (petty/SUCCESS)",
      "skim the ward — Exit messy. (petty/SUCCESS)",
      "lift the crowd — City barely shrugs. (petty/SUCCESS)",
      "skim the ward — Exit messy. (petty/SUCCESS)",
      "lift the crowd — City barely shrugs. (petty/SUCCESS)",
      "skim the ward — Exit messy. (petty/SUCCESS)",
      "lift the crowd — City barely shrugs. (petty/SUCCESS)",
      "skim the ward — Exit messy. (petty/SUCCESS)",
      "lift the crowd — City barely shrugs. (petty/SUCCESS)",
      "skim the ward — Exit messy. (petty/SUCCESS)",
      "lift the crowd — City barely shrugs. (petty/SUCCESS)",
      "skim the ward — Exit messy. (petty/SUCCESS)",
      "lift the crowd — City barely shrugs. (petty/SUCCESS)",
      "skim the ward — Exit messy. (petty/SUCCESS)",
      "lift the crowd — City barely shrugs. (petty/SUCCESS)",
      "skim the ward — Exit messy. (petty/SUCCESS)",
      "lift the crowd — City barely shrugs. (petty/SUCCESS)",
      "skim the ward — Exit messy. (petty/SUCCESS)",
      "Fingers faster than the aisle music.",
      "Tourist blink; you're gone.",
      "Receipt printer never met you.",
      "Festival foam hides a perfect lift.",
      "Corner store gap measured in heartbeats.",
      "Tram sneeze covers the snatch.",
      "Vending coil never stood a chance.",
      "Charity cup lighter; smile intact.",
      "Bike lock learns a new opinion.",
      "Parking meter coughs coins into your palm."
    ],
    "MIXED": [
      "swap the lobby — Pride lighter. (petty/MIXED)",
      "stamp the till — Vex would laugh. (petty/MIXED)",
      "swap the lobby — Pride lighter. (petty/MIXED)",
      "stamp the till — Vex would laugh. (petty/MIXED)",
      "swap the lobby — Pride lighter. (petty/MIXED)",
      "stamp the till — Vex would laugh. (petty/MIXED)",
      "swap the lobby — Pride lighter. (petty/MIXED)",
      "stamp the till — Vex would laugh. (petty/MIXED)",
      "swap the lobby — Pride lighter. (petty/MIXED)",
      "stamp the till — Vex would laugh. (petty/MIXED)",
      "swap the lobby — Pride lighter. (petty/MIXED)",
      "stamp the till — Vex would laugh. (petty/MIXED)",
      "swap the lobby — Pride lighter. (petty/MIXED)",
      "stamp the till — Vex would laugh. (petty/MIXED)",
      "swap the lobby — Pride lighter. (petty/MIXED)",
      "stamp the till — Vex would laugh. (petty/MIXED)",
      "swap the lobby — Pride lighter. (petty/MIXED)",
      "stamp the till — Vex would laugh. (petty/MIXED)",
      "swap the lobby — Pride lighter. (petty/MIXED)",
      "stamp the till — Vex would laugh. (petty/MIXED)",
      "swap the lobby — Pride lighter. (petty/MIXED)",
      "stamp the till — Vex would laugh. (petty/MIXED)",
      "swap the lobby — Pride lighter. (petty/MIXED)",
      "stamp the till — Vex would laugh. (petty/MIXED)",
      "swap the lobby — Pride lighter. (petty/MIXED)",
      "stamp the till — Vex would laugh. (petty/MIXED)",
      "swap the lobby — Pride lighter. (petty/MIXED)",
      "stamp the till — Vex would laugh. (petty/MIXED)",
      "Score sticks; elbow doesn't.",
      "Half the take, all the shove.",
      "Crowd helps then points.",
      "You keep cash and a new bruise map.",
      "Almost invisible. Almost."
    ],
    "FAILED": [
      "crack the tram — Newspaper will invent the rest. (petty/FAILED)",
      "slide the camera — Heat notices anyway. (petty/FAILED)",
      "crack the tram — Newspaper will invent the rest. (petty/FAILED)",
      "slide the camera — Heat notices anyway. (petty/FAILED)",
      "crack the tram — Newspaper will invent the rest. (petty/FAILED)",
      "slide the camera — Heat notices anyway. (petty/FAILED)",
      "crack the tram — Newspaper will invent the rest. (petty/FAILED)",
      "slide the camera — Heat notices anyway. (petty/FAILED)",
      "crack the tram — Newspaper will invent the rest. (petty/FAILED)",
      "slide the camera — Heat notices anyway. (petty/FAILED)",
      "crack the tram — Newspaper will invent the rest. (petty/FAILED)",
      "slide the camera — Heat notices anyway. (petty/FAILED)",
      "crack the tram — Newspaper will invent the rest. (petty/FAILED)",
      "slide the camera — Heat notices anyway. (petty/FAILED)",
      "crack the tram — Newspaper will invent the rest. (petty/FAILED)",
      "slide the camera — Heat notices anyway. (petty/FAILED)",
      "crack the tram — Newspaper will invent the rest. (petty/FAILED)",
      "slide the camera — Heat notices anyway. (petty/FAILED)",
      "crack the tram — Newspaper will invent the rest. (petty/FAILED)",
      "slide the camera — Heat notices anyway. (petty/FAILED)",
      "crack the tram — Newspaper will invent the rest. (petty/FAILED)",
      "slide the camera — Heat notices anyway. (petty/FAILED)",
      "crack the tram — Newspaper will invent the rest. (petty/FAILED)",
      "slide the camera — Heat notices anyway. (petty/FAILED)",
      "crack the tram — Newspaper will invent the rest. (petty/FAILED)",
      "slide the camera — Heat notices anyway. (petty/FAILED)",
      "crack the tram — Newspaper will invent the rest. (petty/FAILED)",
      "slide the camera — Heat notices anyway. (petty/FAILED)",
      "Aisle eyes arrive early.",
      "Hands too hungry for the shelf.",
      "Camera loves your worst second.",
      "Empty pockets, full heat.",
      "The corner files your face."
    ],
    "JAILED": [
      "fade the rope — Rain covers footsteps. (petty/JAILED)",
      "ghost the pier — Exit clean enough. (petty/JAILED)",
      "fade the rope — Rain covers footsteps. (petty/JAILED)",
      "ghost the pier — Exit clean enough. (petty/JAILED)",
      "fade the rope — Rain covers footsteps. (petty/JAILED)",
      "ghost the pier — Exit clean enough. (petty/JAILED)",
      "fade the rope — Rain covers footsteps. (petty/JAILED)",
      "ghost the pier — Exit clean enough. (petty/JAILED)",
      "fade the rope — Rain covers footsteps. (petty/JAILED)",
      "ghost the pier — Exit clean enough. (petty/JAILED)",
      "fade the rope — Rain covers footsteps. (petty/JAILED)",
      "ghost the pier — Exit clean enough. (petty/JAILED)",
      "fade the rope — Rain covers footsteps. (petty/JAILED)",
      "ghost the pier — Exit clean enough. (petty/JAILED)",
      "fade the rope — Rain covers footsteps. (petty/JAILED)",
      "ghost the pier — Exit clean enough. (petty/JAILED)",
      "fade the rope — Rain covers footsteps. (petty/JAILED)",
      "ghost the pier — Exit clean enough. (petty/JAILED)",
      "fade the rope — Rain covers footsteps. (petty/JAILED)",
      "ghost the pier — Exit clean enough. (petty/JAILED)",
      "fade the rope — Rain covers footsteps. (petty/JAILED)",
      "ghost the pier — Exit clean enough. (petty/JAILED)",
      "fade the rope — Rain covers footsteps. (petty/JAILED)",
      "ghost the pier — Exit clean enough. (petty/JAILED)",
      "fade the rope — Rain covers footsteps. (petty/JAILED)",
      "ghost the pier — Exit clean enough. (petty/JAILED)",
      "fade the rope — Rain covers footsteps. (petty/JAILED)",
      "ghost the pier — Exit clean enough. (petty/JAILED)",
      "Cuffs under neon — graduate energy.",
      "Holding cell smells like bad coffee.",
      "Uniforms already knew the aisle.",
      "Fresh mistake, stamped."
    ],
    "HOSPITALIZED": [
      "cut the yard — Pockets heavier. (petty/HOSPITALIZED)",
      "mute the crate — Mentor would approve. (petty/HOSPITALIZED)",
      "cut the yard — Pockets heavier. (petty/HOSPITALIZED)",
      "mute the crate — Mentor would approve. (petty/HOSPITALIZED)",
      "cut the yard — Pockets heavier. (petty/HOSPITALIZED)",
      "mute the crate — Mentor would approve. (petty/HOSPITALIZED)",
      "cut the yard — Pockets heavier. (petty/HOSPITALIZED)",
      "mute the crate — Mentor would approve. (petty/HOSPITALIZED)",
      "cut the yard — Pockets heavier. (petty/HOSPITALIZED)",
      "mute the crate — Mentor would approve. (petty/HOSPITALIZED)",
      "cut the yard — Pockets heavier. (petty/HOSPITALIZED)",
      "mute the crate — Mentor would approve. (petty/HOSPITALIZED)",
      "cut the yard — Pockets heavier. (petty/HOSPITALIZED)",
      "mute the crate — Mentor would approve. (petty/HOSPITALIZED)",
      "cut the yard — Pockets heavier. (petty/HOSPITALIZED)",
      "mute the crate — Mentor would approve. (petty/HOSPITALIZED)",
      "cut the yard — Pockets heavier. (petty/HOSPITALIZED)",
      "mute the crate — Mentor would approve. (petty/HOSPITALIZED)",
      "cut the yard — Pockets heavier. (petty/HOSPITALIZED)",
      "mute the crate — Mentor would approve. (petty/HOSPITALIZED)",
      "cut the yard — Pockets heavier. (petty/HOSPITALIZED)",
      "mute the crate — Mentor would approve. (petty/HOSPITALIZED)",
      "cut the yard — Pockets heavier. (petty/HOSPITALIZED)",
      "mute the crate — Mentor would approve. (petty/HOSPITALIZED)",
      "cut the yard — Pockets heavier. (petty/HOSPITALIZED)",
      "mute the crate — Mentor would approve. (petty/HOSPITALIZED)",
      "cut the yard — Pockets heavier. (petty/HOSPITALIZED)",
      "mute the crate — Mentor would approve. (petty/HOSPITALIZED)",
      "Concrete wins petty arguments.",
      "Clinic light replaces neon.",
      "You wake up billed for a shove.",
      "Soft crime, hard floor."
    ]
  },
  "street": {
    "SUCCESS": [
      "slide the camera — Heat notices anyway. (street/SUCCESS)",
      "crack the tram — Newspaper will invent the rest. (street/SUCCESS)",
      "slide the camera — Heat notices anyway. (street/SUCCESS)",
      "crack the tram — Newspaper will invent the rest. (street/SUCCESS)",
      "slide the camera — Heat notices anyway. (street/SUCCESS)",
      "crack the tram — Newspaper will invent the rest. (street/SUCCESS)",
      "slide the camera — Heat notices anyway. (street/SUCCESS)",
      "crack the tram — Newspaper will invent the rest. (street/SUCCESS)",
      "slide the camera — Heat notices anyway. (street/SUCCESS)",
      "crack the tram — Newspaper will invent the rest. (street/SUCCESS)",
      "slide the camera — Heat notices anyway. (street/SUCCESS)",
      "crack the tram — Newspaper will invent the rest. (street/SUCCESS)",
      "slide the camera — Heat notices anyway. (street/SUCCESS)",
      "crack the tram — Newspaper will invent the rest. (street/SUCCESS)",
      "slide the camera — Heat notices anyway. (street/SUCCESS)",
      "crack the tram — Newspaper will invent the rest. (street/SUCCESS)",
      "slide the camera — Heat notices anyway. (street/SUCCESS)",
      "crack the tram — Newspaper will invent the rest. (street/SUCCESS)",
      "slide the camera — Heat notices anyway. (street/SUCCESS)",
      "crack the tram — Newspaper will invent the rest. (street/SUCCESS)",
      "slide the camera — Heat notices anyway. (street/SUCCESS)",
      "crack the tram — Newspaper will invent the rest. (street/SUCCESS)",
      "slide the camera — Heat notices anyway. (street/SUCCESS)",
      "crack the tram — Newspaper will invent the rest. (street/SUCCESS)",
      "slide the camera — Heat notices anyway. (street/SUCCESS)",
      "crack the tram — Newspaper will invent the rest. (street/SUCCESS)",
      "slide the camera — Heat notices anyway. (street/SUCCESS)",
      "crack the tram — Newspaper will invent the rest. (street/SUCCESS)",
      "Alley math balances in your favor.",
      "Bag swap cleaner than the route sheet.",
      "Yard dogs choose silence tonight.",
      "Warehouse shadow does the heavy lifting.",
      "Chain feels longer by one honest link.",
      "Catalytic undercarriage says goodbye.",
      "Drop point empty when you arrive — on purpose.",
      "Street family nods without smiling."
    ],
    "MIXED": [
      "ghost the pier — Exit clean enough. (street/MIXED)",
      "fade the rope — Rain covers footsteps. (street/MIXED)",
      "ghost the pier — Exit clean enough. (street/MIXED)",
      "fade the rope — Rain covers footsteps. (street/MIXED)",
      "ghost the pier — Exit clean enough. (street/MIXED)",
      "fade the rope — Rain covers footsteps. (street/MIXED)",
      "ghost the pier — Exit clean enough. (street/MIXED)",
      "fade the rope — Rain covers footsteps. (street/MIXED)",
      "ghost the pier — Exit clean enough. (street/MIXED)",
      "fade the rope — Rain covers footsteps. (street/MIXED)",
      "ghost the pier — Exit clean enough. (street/MIXED)",
      "fade the rope — Rain covers footsteps. (street/MIXED)",
      "ghost the pier — Exit clean enough. (street/MIXED)",
      "fade the rope — Rain covers footsteps. (street/MIXED)",
      "ghost the pier — Exit clean enough. (street/MIXED)",
      "fade the rope — Rain covers footsteps. (street/MIXED)",
      "ghost the pier — Exit clean enough. (street/MIXED)",
      "fade the rope — Rain covers footsteps. (street/MIXED)",
      "ghost the pier — Exit clean enough. (street/MIXED)",
      "fade the rope — Rain covers footsteps. (street/MIXED)",
      "ghost the pier — Exit clean enough. (street/MIXED)",
      "fade the rope — Rain covers footsteps. (street/MIXED)",
      "ghost the pier — Exit clean enough. (street/MIXED)",
      "fade the rope — Rain covers footsteps. (street/MIXED)",
      "ghost the pier — Exit clean enough. (street/MIXED)",
      "fade the rope — Rain covers footsteps. (street/MIXED)",
      "ghost the pier — Exit clean enough. (street/MIXED)",
      "fade the rope — Rain covers footsteps. (street/MIXED)",
      "Loot yes; ribs maybe.",
      "Partial lift, full argument.",
      "You win the wallet and lose the tempo.",
      "Profitable limp home.",
      "Street tax paid in both currencies."
    ],
    "FAILED": [
      "mute the crate — Mentor would approve. (street/FAILED)",
      "cut the yard — Pockets heavier. (street/FAILED)",
      "mute the crate — Mentor would approve. (street/FAILED)",
      "cut the yard — Pockets heavier. (street/FAILED)",
      "mute the crate — Mentor would approve. (street/FAILED)",
      "cut the yard — Pockets heavier. (street/FAILED)",
      "mute the crate — Mentor would approve. (street/FAILED)",
      "cut the yard — Pockets heavier. (street/FAILED)",
      "mute the crate — Mentor would approve. (street/FAILED)",
      "cut the yard — Pockets heavier. (street/FAILED)",
      "mute the crate — Mentor would approve. (street/FAILED)",
      "cut the yard — Pockets heavier. (street/FAILED)",
      "mute the crate — Mentor would approve. (street/FAILED)",
      "cut the yard — Pockets heavier. (street/FAILED)",
      "mute the crate — Mentor would approve. (street/FAILED)",
      "cut the yard — Pockets heavier. (street/FAILED)",
      "mute the crate — Mentor would approve. (street/FAILED)",
      "cut the yard — Pockets heavier. (street/FAILED)",
      "mute the crate — Mentor would approve. (street/FAILED)",
      "cut the yard — Pockets heavier. (street/FAILED)",
      "mute the crate — Mentor would approve. (street/FAILED)",
      "cut the yard — Pockets heavier. (street/FAILED)",
      "mute the crate — Mentor would approve. (street/FAILED)",
      "cut the yard — Pockets heavier. (street/FAILED)",
      "mute the crate — Mentor would approve. (street/FAILED)",
      "cut the yard — Pockets heavier. (street/FAILED)",
      "mute the crate — Mentor would approve. (street/FAILED)",
      "cut the yard — Pockets heavier. (street/FAILED)",
      "Wrong alley owns you tonight.",
      "Lookout read you first.",
      "Empty hands, louder block.",
      "Yard remembers your last scent.",
      "Street spits you toward the tram."
    ],
    "JAILED": [
      "lift the crowd — City barely shrugs. (street/JAILED)",
      "skim the ward — Exit messy. (street/JAILED)",
      "lift the crowd — City barely shrugs. (street/JAILED)",
      "skim the ward — Exit messy. (street/JAILED)",
      "lift the crowd — City barely shrugs. (street/JAILED)",
      "skim the ward — Exit messy. (street/JAILED)",
      "lift the crowd — City barely shrugs. (street/JAILED)",
      "skim the ward — Exit messy. (street/JAILED)",
      "lift the crowd — City barely shrugs. (street/JAILED)",
      "skim the ward — Exit messy. (street/JAILED)",
      "lift the crowd — City barely shrugs. (street/JAILED)",
      "skim the ward — Exit messy. (street/JAILED)",
      "lift the crowd — City barely shrugs. (street/JAILED)",
      "skim the ward — Exit messy. (street/JAILED)",
      "lift the crowd — City barely shrugs. (street/JAILED)",
      "skim the ward — Exit messy. (street/JAILED)",
      "lift the crowd — City barely shrugs. (street/JAILED)",
      "skim the ward — Exit messy. (street/JAILED)",
      "lift the crowd — City barely shrugs. (street/JAILED)",
      "skim the ward — Exit messy. (street/JAILED)",
      "lift the crowd — City barely shrugs. (street/JAILED)",
      "skim the ward — Exit messy. (street/JAILED)",
      "lift the crowd — City barely shrugs. (street/JAILED)",
      "skim the ward — Exit messy. (street/JAILED)",
      "lift the crowd — City barely shrugs. (street/JAILED)",
      "skim the ward — Exit messy. (street/JAILED)",
      "lift the crowd — City barely shrugs. (street/JAILED)",
      "skim the ward — Exit messy. (street/JAILED)",
      "Patrol closes both ends of the brick.",
      "Street-to-cell commute is short.",
      "Cuffs over wet concrete.",
      "They booked the corner in advance."
    ],
    "HOSPITALIZED": [
      "swap the lobby — Pride lighter. (street/HOSPITALIZED)",
      "stamp the till — Vex would laugh. (street/HOSPITALIZED)",
      "swap the lobby — Pride lighter. (street/HOSPITALIZED)",
      "stamp the till — Vex would laugh. (street/HOSPITALIZED)",
      "swap the lobby — Pride lighter. (street/HOSPITALIZED)",
      "stamp the till — Vex would laugh. (street/HOSPITALIZED)",
      "swap the lobby — Pride lighter. (street/HOSPITALIZED)",
      "stamp the till — Vex would laugh. (street/HOSPITALIZED)",
      "swap the lobby — Pride lighter. (street/HOSPITALIZED)",
      "stamp the till — Vex would laugh. (street/HOSPITALIZED)",
      "swap the lobby — Pride lighter. (street/HOSPITALIZED)",
      "stamp the till — Vex would laugh. (street/HOSPITALIZED)",
      "swap the lobby — Pride lighter. (street/HOSPITALIZED)",
      "stamp the till — Vex would laugh. (street/HOSPITALIZED)",
      "swap the lobby — Pride lighter. (street/HOSPITALIZED)",
      "stamp the till — Vex would laugh. (street/HOSPITALIZED)",
      "swap the lobby — Pride lighter. (street/HOSPITALIZED)",
      "stamp the till — Vex would laugh. (street/HOSPITALIZED)",
      "swap the lobby — Pride lighter. (street/HOSPITALIZED)",
      "stamp the till — Vex would laugh. (street/HOSPITALIZED)",
      "swap the lobby — Pride lighter. (street/HOSPITALIZED)",
      "stamp the till — Vex would laugh. (street/HOSPITALIZED)",
      "swap the lobby — Pride lighter. (street/HOSPITALIZED)",
      "stamp the till — Vex would laugh. (street/HOSPITALIZED)",
      "swap the lobby — Pride lighter. (street/HOSPITALIZED)",
      "stamp the till — Vex would laugh. (street/HOSPITALIZED)",
      "swap the lobby — Pride lighter. (street/HOSPITALIZED)",
      "stamp the till — Vex would laugh. (street/HOSPITALIZED)",
      "Knuckles write the chart.",
      "Ward lights, not streetlights.",
      "Gravity collects street debts.",
      "You lose the argument horizontally."
    ]
  },
  "heavy": {
    "SUCCESS": [
      "cut the yard — Pockets heavier. (heavy/SUCCESS)",
      "mute the crate — Mentor would approve. (heavy/SUCCESS)",
      "cut the yard — Pockets heavier. (heavy/SUCCESS)",
      "mute the crate — Mentor would approve. (heavy/SUCCESS)",
      "cut the yard — Pockets heavier. (heavy/SUCCESS)",
      "mute the crate — Mentor would approve. (heavy/SUCCESS)",
      "cut the yard — Pockets heavier. (heavy/SUCCESS)",
      "mute the crate — Mentor would approve. (heavy/SUCCESS)",
      "cut the yard — Pockets heavier. (heavy/SUCCESS)",
      "mute the crate — Mentor would approve. (heavy/SUCCESS)",
      "cut the yard — Pockets heavier. (heavy/SUCCESS)",
      "mute the crate — Mentor would approve. (heavy/SUCCESS)",
      "cut the yard — Pockets heavier. (heavy/SUCCESS)",
      "mute the crate — Mentor would approve. (heavy/SUCCESS)",
      "cut the yard — Pockets heavier. (heavy/SUCCESS)",
      "mute the crate — Mentor would approve. (heavy/SUCCESS)",
      "cut the yard — Pockets heavier. (heavy/SUCCESS)",
      "mute the crate — Mentor would approve. (heavy/SUCCESS)",
      "cut the yard — Pockets heavier. (heavy/SUCCESS)",
      "mute the crate — Mentor would approve. (heavy/SUCCESS)",
      "cut the yard — Pockets heavier. (heavy/SUCCESS)",
      "mute the crate — Mentor would approve. (heavy/SUCCESS)",
      "cut the yard — Pockets heavier. (heavy/SUCCESS)",
      "mute the crate — Mentor would approve. (heavy/SUCCESS)",
      "cut the yard — Pockets heavier. (heavy/SUCCESS)",
      "mute the crate — Mentor would approve. (heavy/SUCCESS)",
      "cut the yard — Pockets heavier. (heavy/SUCCESS)",
      "mute the crate — Mentor would approve. (heavy/SUCCESS)",
      "Vault grammar fluent for one night.",
      "Manifests will never match — perfect.",
      "Spire carpets mute the right crime.",
      "Harbor container tells the truth quietly.",
      "Crew timing holds; city blinks.",
      "Private room opens like it owed you.",
      "Heavy take justifies the nerve math.",
      "Professional silence after loud tools."
    ],
    "MIXED": [
      "skim the ward — Exit messy. (heavy/MIXED)",
      "lift the crowd — City barely shrugs. (heavy/MIXED)",
      "skim the ward — Exit messy. (heavy/MIXED)",
      "lift the crowd — City barely shrugs. (heavy/MIXED)",
      "skim the ward — Exit messy. (heavy/MIXED)",
      "lift the crowd — City barely shrugs. (heavy/MIXED)",
      "skim the ward — Exit messy. (heavy/MIXED)",
      "lift the crowd — City barely shrugs. (heavy/MIXED)",
      "skim the ward — Exit messy. (heavy/MIXED)",
      "lift the crowd — City barely shrugs. (heavy/MIXED)",
      "skim the ward — Exit messy. (heavy/MIXED)",
      "lift the crowd — City barely shrugs. (heavy/MIXED)",
      "skim the ward — Exit messy. (heavy/MIXED)",
      "lift the crowd — City barely shrugs. (heavy/MIXED)",
      "skim the ward — Exit messy. (heavy/MIXED)",
      "lift the crowd — City barely shrugs. (heavy/MIXED)",
      "skim the ward — Exit messy. (heavy/MIXED)",
      "lift the crowd — City barely shrugs. (heavy/MIXED)",
      "skim the ward — Exit messy. (heavy/MIXED)",
      "lift the crowd — City barely shrugs. (heavy/MIXED)",
      "skim the ward — Exit messy. (heavy/MIXED)",
      "lift the crowd — City barely shrugs. (heavy/MIXED)",
      "skim the ward — Exit messy. (heavy/MIXED)",
      "lift the crowd — City barely shrugs. (heavy/MIXED)",
      "skim the ward — Exit messy. (heavy/MIXED)",
      "lift the crowd — City barely shrugs. (heavy/MIXED)",
      "skim the ward — Exit messy. (heavy/MIXED)",
      "lift the crowd — City barely shrugs. (heavy/MIXED)",
      "Half the vault, all the sirens.",
      "Rich exit, wrong temperature.",
      "Alarm late; bruises early.",
      "Board would stamp this messy green.",
      "Cash up, life negotiating."
    ],
    "FAILED": [
      "stamp the till — Vex would laugh. (heavy/FAILED)",
      "swap the lobby — Pride lighter. (heavy/FAILED)",
      "stamp the till — Vex would laugh. (heavy/FAILED)",
      "swap the lobby — Pride lighter. (heavy/FAILED)",
      "stamp the till — Vex would laugh. (heavy/FAILED)",
      "swap the lobby — Pride lighter. (heavy/FAILED)",
      "stamp the till — Vex would laugh. (heavy/FAILED)",
      "swap the lobby — Pride lighter. (heavy/FAILED)",
      "stamp the till — Vex would laugh. (heavy/FAILED)",
      "swap the lobby — Pride lighter. (heavy/FAILED)",
      "stamp the till — Vex would laugh. (heavy/FAILED)",
      "swap the lobby — Pride lighter. (heavy/FAILED)",
      "stamp the till — Vex would laugh. (heavy/FAILED)",
      "swap the lobby — Pride lighter. (heavy/FAILED)",
      "stamp the till — Vex would laugh. (heavy/FAILED)",
      "swap the lobby — Pride lighter. (heavy/FAILED)",
      "stamp the till — Vex would laugh. (heavy/FAILED)",
      "swap the lobby — Pride lighter. (heavy/FAILED)",
      "stamp the till — Vex would laugh. (heavy/FAILED)",
      "swap the lobby — Pride lighter. (heavy/FAILED)",
      "stamp the till — Vex would laugh. (heavy/FAILED)",
      "swap the lobby — Pride lighter. (heavy/FAILED)",
      "stamp the till — Vex would laugh. (heavy/FAILED)",
      "swap the lobby — Pride lighter. (heavy/FAILED)",
      "stamp the till — Vex would laugh. (heavy/FAILED)",
      "swap the lobby — Pride lighter. (heavy/FAILED)",
      "stamp the till — Vex would laugh. (heavy/FAILED)",
      "swap the lobby — Pride lighter. (heavy/FAILED)",
      "Vault stays shut; heat doesn't.",
      "Wrong tumbler, right consequences.",
      "Lobby silhouette filed forever.",
      "Crew timing snaps like cheap wire.",
      "Heavy hope gets expensive fast."
    ],
    "JAILED": [
      "slide the camera — Heat notices anyway. (heavy/JAILED)",
      "crack the tram — Newspaper will invent the rest. (heavy/JAILED)",
      "slide the camera — Heat notices anyway. (heavy/JAILED)",
      "crack the tram — Newspaper will invent the rest. (heavy/JAILED)",
      "slide the camera — Heat notices anyway. (heavy/JAILED)",
      "crack the tram — Newspaper will invent the rest. (heavy/JAILED)",
      "slide the camera — Heat notices anyway. (heavy/JAILED)",
      "crack the tram — Newspaper will invent the rest. (heavy/JAILED)",
      "slide the camera — Heat notices anyway. (heavy/JAILED)",
      "crack the tram — Newspaper will invent the rest. (heavy/JAILED)",
      "slide the camera — Heat notices anyway. (heavy/JAILED)",
      "crack the tram — Newspaper will invent the rest. (heavy/JAILED)",
      "slide the camera — Heat notices anyway. (heavy/JAILED)",
      "crack the tram — Newspaper will invent the rest. (heavy/JAILED)",
      "slide the camera — Heat notices anyway. (heavy/JAILED)",
      "crack the tram — Newspaper will invent the rest. (heavy/JAILED)",
      "slide the camera — Heat notices anyway. (heavy/JAILED)",
      "crack the tram — Newspaper will invent the rest. (heavy/JAILED)",
      "slide the camera — Heat notices anyway. (heavy/JAILED)",
      "crack the tram — Newspaper will invent the rest. (heavy/JAILED)",
      "slide the camera — Heat notices anyway. (heavy/JAILED)",
      "crack the tram — Newspaper will invent the rest. (heavy/JAILED)",
      "slide the camera — Heat notices anyway. (heavy/JAILED)",
      "crack the tram — Newspaper will invent the rest. (heavy/JAILED)",
      "slide the camera — Heat notices anyway. (heavy/JAILED)",
      "crack the tram — Newspaper will invent the rest. (heavy/JAILED)",
      "slide the camera — Heat notices anyway. (heavy/JAILED)",
      "crack the tram — Newspaper will invent the rest. (heavy/JAILED)",
      "Evidence drawer already labeled.",
      "Heavy cuffs, soft lobby lights.",
      "The case writes itself in ink.",
      "Jail priced into the attempt — due now."
    ],
    "HOSPITALIZED": [
      "ghost the pier — Exit clean enough. (heavy/HOSPITALIZED)",
      "fade the rope — Rain covers footsteps. (heavy/HOSPITALIZED)",
      "ghost the pier — Exit clean enough. (heavy/HOSPITALIZED)",
      "fade the rope — Rain covers footsteps. (heavy/HOSPITALIZED)",
      "ghost the pier — Exit clean enough. (heavy/HOSPITALIZED)",
      "fade the rope — Rain covers footsteps. (heavy/HOSPITALIZED)",
      "ghost the pier — Exit clean enough. (heavy/HOSPITALIZED)",
      "fade the rope — Rain covers footsteps. (heavy/HOSPITALIZED)",
      "ghost the pier — Exit clean enough. (heavy/HOSPITALIZED)",
      "fade the rope — Rain covers footsteps. (heavy/HOSPITALIZED)",
      "ghost the pier — Exit clean enough. (heavy/HOSPITALIZED)",
      "fade the rope — Rain covers footsteps. (heavy/HOSPITALIZED)",
      "ghost the pier — Exit clean enough. (heavy/HOSPITALIZED)",
      "fade the rope — Rain covers footsteps. (heavy/HOSPITALIZED)",
      "ghost the pier — Exit clean enough. (heavy/HOSPITALIZED)",
      "fade the rope — Rain covers footsteps. (heavy/HOSPITALIZED)",
      "ghost the pier — Exit clean enough. (heavy/HOSPITALIZED)",
      "fade the rope — Rain covers footsteps. (heavy/HOSPITALIZED)",
      "ghost the pier — Exit clean enough. (heavy/HOSPITALIZED)",
      "fade the rope — Rain covers footsteps. (heavy/HOSPITALIZED)",
      "ghost the pier — Exit clean enough. (heavy/HOSPITALIZED)",
      "fade the rope — Rain covers footsteps. (heavy/HOSPITALIZED)",
      "ghost the pier — Exit clean enough. (heavy/HOSPITALIZED)",
      "fade the rope — Rain covers footsteps. (heavy/HOSPITALIZED)",
      "ghost the pier — Exit clean enough. (heavy/HOSPITALIZED)",
      "fade the rope — Rain covers footsteps. (heavy/HOSPITALIZED)",
      "ghost the pier — Exit clean enough. (heavy/HOSPITALIZED)",
      "fade the rope — Rain covers footsteps. (heavy/HOSPITALIZED)",
      "Vault floor meets your skull.",
      "Armor fails the fall exam.",
      "You wake inventoried.",
      "Clinic ward, not count room."
    ]
  }
};

export const HEIST_RESULT_COPY_EXTRA: Record<"SUCCESS" | "MIXED" | "FAILED", string[]> = {
  "SUCCESS": [
    "Board closed before the desk invents adjectives.",
    "Prep spine sang; execute whispered.",
    "Organized quiet buys loud payouts.",
    "Window timing jealous of itself.",
    "Crew dissolves into cleaner numbers.",
    "Rank ink still wet; city already quoting.",
    "Newspaper late to a finished story.",
    "The take consolidates; egos don't.",
    "Harbor night, board daylight.",
    "You leave the spine cleaner than you found it."
  ],
  "MIXED": [
    "Board pays with footnotes and limps.",
    "Execute improvises; loot forgives.",
    "Mixed rank: profitable noise.",
    "Payout survives the panic.",
    "You close the board breathing hard.",
    "City noticed; wallet noticed more.",
    "Green stamp, yellow bruises.",
    "Crew argues; cash settles it."
  ],
  "FAILED": [
    "Board burns; cooldown still invoices.",
    "Window closes on expensive prep.",
    "Execute fails the audition.",
    "Humiliation column drafts itself.",
    "Organized noise without music.",
    "Spine snaps at the last vertebra.",
    "Cooldown clock starts laughing.",
    "You leave poorer in nerve and myth."
  ]
};
