import type { NpcDef } from "@/game/types";

/** Density pack — district attack pool volume. Slutty = female nightlife minority only. */
export const NPCS_EXTRA: NpcDef[] = [
  {
    id: "gr_hostess",
    name: "Neon Hostess",
    title: "Soft target",
    district: "glassrow",
    power: 16,
    str: 4,
    def: 3,
    spd: 9,
    dex: 7,
    life: 38,
    lootMin: 100,
    lootMax: 240,
    heatOnWin: 3,
    heatOnLose: 2,
    energyCost: 7,
    gender: "female",
    persona: "slutty",
    flavor: "Clipboard smile at the velvet rope.",
    flavorSlutty: "Clipboard smile, velvet voice — she clocks your pulse before your name.",
  },
  {
    id: "gr_dj",
    name: "Booth DJ",
    title: "Lookout",
    district: "glassrow",
    power: 23,
    str: 5,
    def: 5,
    spd: 11,
    dex: 10,
    life: 42,
    lootMin: 140,
    lootMax: 300,
    heatOnWin: 4,
    heatOnLose: 3,
    energyCost: 8,
    gender: "male",
    flavor: "Headphones half-on. Knows every side door.",
  },
  {
    id: "gr_valet",
    name: "Alley Valet",
    title: "Muscle",
    district: "glassrow",
    power: 36,
    str: 12,
    def: 10,
    spd: 7,
    dex: 6,
    life: 56,
    lootMin: 180,
    lootMax: 400,
    heatOnWin: 5,
    heatOnLose: 4,
    energyCost: 10,
    gender: "male",
    flavor: "Keys on a ring that isn't yours yet.",
  },
  {
    id: "gr_barista",
    name: "Late Barista",
    title: "Operator",
    district: "glassrow",
    power: 28,
    str: 8,
    def: 7,
    spd: 10,
    dex: 11,
    life: 48,
    lootMin: 200,
    lootMax: 440,
    heatOnWin: 5,
    heatOnLose: 3,
    energyCost: 9,
    gender: "female",
    flavor: "Steam and gossip in equal measure.",
  },
  {
    id: "gr_pickpocket",
    name: "Tram Pick",
    title: "Fixer",
    district: "glassrow",
    power: 31,
    str: 7,
    def: 8,
    spd: 9,
    dex: 12,
    life: 50,
    lootMin: 220,
    lootMax: 480,
    heatOnWin: 6,
    heatOnLose: 3,
    energyCost: 9,
    flavor: "Crowds are a second skin.",
  },
  {
    id: "gr_promoter_f",
    name: "Guest-list Girl",
    title: "Enforcer",
    district: "glassrow",
    power: 42,
    str: 14,
    def: 12,
    spd: 6,
    dex: 7,
    life: 62,
    lootMin: 260,
    lootMax: 560,
    heatOnWin: 7,
    heatOnLose: 5,
    energyCost: 11,
    gender: "female",
    persona: "slutty",
    flavor: "Wristbands and warmer promises.",
    flavorSlutty: "Wristbands, warmer promises — she stamps more than paper if you linger.",
  },
  {
    id: "gr_cam_tech",
    name: "Camera Tech",
    title: "Ghost",
    district: "glassrow",
    power: 26,
    str: 6,
    def: 6,
    spd: 13,
    dex: 12,
    life: 44,
    lootMin: 180,
    lootMax: 420,
    heatOnWin: 5,
    heatOnLose: 3,
    energyCost: 8,
    gender: "male",
    flavor: "Blind spots mapped in grease pencil.",
  },
  {
    id: "ms_crane_kid",
    name: "Crane Apprentice",
    title: "Soft target",
    district: "millstone",
    power: 16,
    str: 4,
    def: 3,
    spd: 9,
    dex: 7,
    life: 38,
    lootMin: 100,
    lootMax: 240,
    heatOnWin: 3,
    heatOnLose: 2,
    energyCost: 7,
    gender: "male",
    flavor: "Hard hat, soft nerves.",
  },
  {
    id: "ms_parts_girl",
    name: "Parts Counter Girl",
    title: "Lookout",
    district: "millstone",
    power: 23,
    str: 5,
    def: 5,
    spd: 11,
    dex: 10,
    life: 42,
    lootMin: 140,
    lootMax: 300,
    heatOnWin: 4,
    heatOnLose: 3,
    energyCost: 8,
    gender: "female",
    flavor: "Catalog smile, warehouse keys.",
  },
  {
    id: "ms_dog_man",
    name: "Yard Dog Handler",
    title: "Muscle",
    district: "millstone",
    power: 36,
    str: 12,
    def: 10,
    spd: 7,
    dex: 6,
    life: 56,
    lootMin: 180,
    lootMax: 400,
    heatOnWin: 5,
    heatOnLose: 4,
    energyCost: 10,
    gender: "male",
    flavor: "Whistle that ends arguments.",
  },
  {
    id: "ms_welder_f",
    name: "Night Welder",
    title: "Operator",
    district: "millstone",
    power: 28,
    str: 8,
    def: 7,
    spd: 10,
    dex: 11,
    life: 48,
    lootMin: 200,
    lootMax: 440,
    heatOnWin: 5,
    heatOnLose: 3,
    energyCost: 9,
    gender: "female",
    flavor: "Sparks and overtime.",
  },
  {
    id: "ms_scrap",
    name: "Scrap Runner",
    title: "Fixer",
    district: "millstone",
    power: 31,
    str: 7,
    def: 8,
    spd: 9,
    dex: 12,
    life: 50,
    lootMin: 220,
    lootMax: 480,
    heatOnWin: 6,
    heatOnLose: 3,
    energyCost: 9,
    flavor: "Copper in the bag, heat in the walk.",
  },
  {
    id: "ms_union",
    name: "Union Steward",
    title: "Enforcer",
    district: "millstone",
    power: 42,
    str: 14,
    def: 12,
    spd: 6,
    dex: 7,
    life: 62,
    lootMin: 260,
    lootMax: 560,
    heatOnWin: 7,
    heatOnLose: 5,
    energyCost: 11,
    gender: "male",
    flavor: "Clipboard that can freeze a shift.",
  },
  {
    id: "ms_forklift",
    name: "Forklift Ghost",
    title: "Ghost",
    district: "millstone",
    power: 26,
    str: 6,
    def: 6,
    spd: 13,
    dex: 12,
    life: 44,
    lootMin: 180,
    lootMax: 420,
    heatOnWin: 5,
    heatOnLose: 3,
    energyCost: 8,
    gender: "male",
    flavor: "Pallets that vanish on paper.",
  },
  {
    id: "dr_bosun",
    name: "Night Bosun",
    title: "Soft target",
    district: "docksreach",
    power: 16,
    str: 4,
    def: 3,
    spd: 9,
    dex: 7,
    life: 38,
    lootMin: 100,
    lootMax: 240,
    heatOnWin: 3,
    heatOnLose: 2,
    energyCost: 7,
    gender: "male",
    flavor: "Salt voice, crane radio.",
  },
  {
    id: "dr_manifest",
    name: "Manifest Clerk",
    title: "Lookout",
    district: "docksreach",
    power: 23,
    str: 5,
    def: 5,
    spd: 11,
    dex: 10,
    life: 42,
    lootMin: 140,
    lootMax: 300,
    heatOnWin: 4,
    heatOnLose: 3,
    energyCost: 8,
    gender: "female",
    flavor: "Stamps that never match crates.",
  },
  {
    id: "dr_smuggle_f",
    name: "Bay Smuggler",
    title: "Muscle",
    district: "docksreach",
    power: 36,
    str: 12,
    def: 10,
    spd: 7,
    dex: 6,
    life: 56,
    lootMin: 180,
    lootMax: 400,
    heatOnWin: 5,
    heatOnLose: 4,
    energyCost: 10,
    gender: "female",
    persona: "slutty",
    flavor: "Container smiles and salt perfume.",
    flavorSlutty: "Container smiles, salt perfume — she loads more than freight if you tip right.",
  },
  {
    id: "dr_rope",
    name: "Rope Hand",
    title: "Operator",
    district: "docksreach",
    power: 28,
    str: 8,
    def: 7,
    spd: 10,
    dex: 11,
    life: 48,
    lootMin: 200,
    lootMax: 440,
    heatOnWin: 5,
    heatOnLose: 3,
    energyCost: 9,
    gender: "male",
    flavor: "Knots faster than questions.",
  },
  {
    id: "dr_customs_f",
    name: "Soft Customs",
    title: "Fixer",
    district: "docksreach",
    power: 31,
    str: 7,
    def: 8,
    spd: 9,
    dex: 12,
    life: 50,
    lootMin: 220,
    lootMax: 480,
    heatOnWin: 6,
    heatOnLose: 3,
    energyCost: 9,
    gender: "female",
    flavor: "Badge that blinks for friends.",
  },
  {
    id: "dr_pilot",
    name: "Harbor Pilot",
    title: "Enforcer",
    district: "docksreach",
    power: 42,
    str: 14,
    def: 12,
    spd: 6,
    dex: 7,
    life: 62,
    lootMin: 260,
    lootMax: 560,
    heatOnWin: 7,
    heatOnLose: 5,
    energyCost: 11,
    gender: "male",
    flavor: "Knows every dark channel.",
  },
  {
    id: "dr_net",
    name: "Net Mender",
    title: "Ghost",
    district: "docksreach",
    power: 26,
    str: 6,
    def: 6,
    spd: 13,
    dex: 12,
    life: 44,
    lootMin: 180,
    lootMax: 420,
    heatOnWin: 5,
    heatOnLose: 3,
    energyCost: 8,
    flavor: "Quiet pier work after midnight.",
  },
  {
    id: "ac_nurse",
    name: "Night Nurse",
    title: "Soft target",
    district: "ashcourt",
    power: 16,
    str: 4,
    def: 3,
    spd: 9,
    dex: 7,
    life: 38,
    lootMin: 100,
    lootMax: 240,
    heatOnWin: 3,
    heatOnLose: 2,
    energyCost: 7,
    gender: "female",
    flavor: "Ward light and softer threats.",
  },
  {
    id: "ac_records",
    name: "Records Aide",
    title: "Lookout",
    district: "ashcourt",
    power: 23,
    str: 5,
    def: 5,
    spd: 11,
    dex: 10,
    life: 42,
    lootMin: 140,
    lootMax: 300,
    heatOnWin: 4,
    heatOnLose: 3,
    energyCost: 8,
    gender: "female",
    flavor: "Files that open doors.",
  },
  {
    id: "ac_porter",
    name: "Clinic Porter",
    title: "Muscle",
    district: "ashcourt",
    power: 36,
    str: 12,
    def: 10,
    spd: 7,
    dex: 6,
    life: 56,
    lootMin: 180,
    lootMax: 400,
    heatOnWin: 5,
    heatOnLose: 4,
    energyCost: 10,
    gender: "male",
    flavor: "Gurneys and side corridors.",
  },
  {
    id: "ac_advocate",
    name: "Civic Advocate",
    title: "Operator",
    district: "ashcourt",
    power: 28,
    str: 8,
    def: 7,
    spd: 10,
    dex: 11,
    life: 48,
    lootMin: 200,
    lootMax: 440,
    heatOnWin: 5,
    heatOnLose: 3,
    energyCost: 9,
    gender: "female",
    flavor: "Clipboard justice, expensive favors.",
  },
  {
    id: "ac_orderly_f",
    name: "Float Orderly",
    title: "Fixer",
    district: "ashcourt",
    power: 31,
    str: 7,
    def: 8,
    spd: 9,
    dex: 12,
    life: 50,
    lootMin: 220,
    lootMax: 480,
    heatOnWin: 6,
    heatOnLose: 3,
    energyCost: 9,
    gender: "female",
    flavor: "Codes for doors that shouldn't.",
  },
  {
    id: "ac_guard_night",
    name: "Night Desk Guard",
    title: "Enforcer",
    district: "ashcourt",
    power: 42,
    str: 14,
    def: 12,
    spd: 6,
    dex: 7,
    life: 62,
    lootMin: 260,
    lootMax: 560,
    heatOnWin: 7,
    heatOnLose: 5,
    energyCost: 11,
    gender: "male",
    flavor: "Metal detector boredom.",
  },
  {
    id: "ac_phlebotomy",
    name: "Phlebotomist",
    title: "Ghost",
    district: "ashcourt",
    power: 26,
    str: 6,
    def: 6,
    spd: 13,
    dex: 12,
    life: 44,
    lootMin: 180,
    lootMax: 420,
    heatOnWin: 5,
    heatOnLose: 3,
    energyCost: 8,
    gender: "female",
    flavor: "Needles and quiet rooms.",
  },
  {
    id: "sy_concierge",
    name: "Lobby Concierge",
    title: "Soft target",
    district: "spireyard",
    power: 16,
    str: 4,
    def: 3,
    spd: 9,
    dex: 7,
    life: 38,
    lootMin: 100,
    lootMax: 240,
    heatOnWin: 3,
    heatOnLose: 2,
    energyCost: 7,
    gender: "male",
    flavor: "Names filed by zip code.",
  },
  {
    id: "sy_pa",
    name: "Exec PA",
    title: "Lookout",
    district: "spireyard",
    power: 23,
    str: 5,
    def: 5,
    spd: 11,
    dex: 10,
    life: 42,
    lootMin: 140,
    lootMax: 300,
    heatOnWin: 4,
    heatOnLose: 3,
    energyCost: 8,
    gender: "female",
    flavor: "Calendar that moves vaults.",
  },
  {
    id: "sy_analyst_f",
    name: "Risk Analyst",
    title: "Muscle",
    district: "spireyard",
    power: 36,
    str: 12,
    def: 10,
    spd: 7,
    dex: 6,
    life: 56,
    lootMin: 180,
    lootMax: 400,
    heatOnWin: 5,
    heatOnLose: 4,
    energyCost: 10,
    gender: "female",
    flavor: "Numbers that smell like heat.",
  },
  {
    id: "sy_doorman",
    name: "Doorman",
    title: "Operator",
    district: "spireyard",
    power: 28,
    str: 8,
    def: 7,
    spd: 10,
    dex: 11,
    life: 48,
    lootMin: 200,
    lootMax: 440,
    heatOnWin: 5,
    heatOnLose: 3,
    energyCost: 9,
    gender: "male",
    flavor: "Umbrella and judgment.",
  },
  {
    id: "sy_intern_f",
    name: "Spire Intern",
    title: "Fixer",
    district: "spireyard",
    power: 31,
    str: 7,
    def: 8,
    spd: 9,
    dex: 12,
    life: 50,
    lootMin: 220,
    lootMax: 480,
    heatOnWin: 6,
    heatOnLose: 3,
    energyCost: 9,
    gender: "female",
    flavor: "Badge on a lanyard that opens soft floors.",
  },
  {
    id: "sy_courier_lux",
    name: "Lux Courier",
    title: "Enforcer",
    district: "spireyard",
    power: 42,
    str: 14,
    def: 12,
    spd: 6,
    dex: 7,
    life: 62,
    lootMin: 260,
    lootMax: 560,
    heatOnWin: 7,
    heatOnLose: 5,
    energyCost: 11,
    gender: "male",
    flavor: "Boxes that never go through mail.",
  },
  {
    id: "sy_host_f",
    name: "Penthouse Host",
    title: "Ghost",
    district: "spireyard",
    power: 26,
    str: 6,
    def: 6,
    spd: 13,
    dex: 12,
    life: 44,
    lootMin: 180,
    lootMax: 420,
    heatOnWin: 5,
    heatOnLose: 3,
    energyCost: 8,
    gender: "female",
    persona: "slutty",
    flavor: "Guest list with warmer footnotes.",
    flavorSlutty: "Guest list with warmer footnotes — she seats you closer if you ask nicely.",
  },
  {
    id: "oc_stoop",
    name: "Stoop Lookout",
    title: "Soft target",
    district: "oldcommons",
    power: 16,
    str: 4,
    def: 3,
    spd: 9,
    dex: 7,
    life: 38,
    lootMin: 100,
    lootMax: 240,
    heatOnWin: 3,
    heatOnLose: 2,
    energyCost: 7,
    gender: "male",
    flavor: "Sees every tram and tourist.",
  },
  {
    id: "oc_auntie",
    name: "Stoop Auntie",
    title: "Lookout",
    district: "oldcommons",
    power: 23,
    str: 5,
    def: 5,
    spd: 11,
    dex: 10,
    life: 42,
    lootMin: 140,
    lootMax: 300,
    heatOnWin: 4,
    heatOnLose: 3,
    energyCost: 8,
    gender: "female",
    flavor: "Tea and threats in one cup.",
  },
  {
    id: "oc_runner_f",
    name: "Alley Runner",
    title: "Muscle",
    district: "oldcommons",
    power: 36,
    str: 12,
    def: 10,
    spd: 7,
    dex: 6,
    life: 56,
    lootMin: 180,
    lootMax: 400,
    heatOnWin: 5,
    heatOnLose: 4,
    energyCost: 10,
    gender: "female",
    flavor: "Bags that change hands mid-block.",
  },
  {
    id: "oc_bookie",
    name: "Corner Bookie",
    title: "Operator",
    district: "oldcommons",
    power: 28,
    str: 8,
    def: 7,
    spd: 10,
    dex: 11,
    life: 48,
    lootMin: 200,
    lootMax: 440,
    heatOnWin: 5,
    heatOnLose: 3,
    energyCost: 9,
    gender: "male",
    flavor: "Odds written on a napkin.",
  },
  {
    id: "oc_mechanic",
    name: "Basement Mechanic",
    title: "Fixer",
    district: "oldcommons",
    power: 31,
    str: 7,
    def: 8,
    spd: 9,
    dex: 12,
    life: 50,
    lootMin: 220,
    lootMax: 480,
    heatOnWin: 6,
    heatOnLose: 3,
    energyCost: 9,
    gender: "male",
    flavor: "Engines and alibis.",
  },
  {
    id: "oc_vendor",
    name: "Night Vendor",
    title: "Enforcer",
    district: "oldcommons",
    power: 42,
    str: 14,
    def: 12,
    spd: 6,
    dex: 7,
    life: 62,
    lootMin: 260,
    lootMax: 560,
    heatOnWin: 7,
    heatOnLose: 5,
    energyCost: 11,
    gender: "female",
    flavor: "Steam cart, warmer rumors.",
  },
  {
    id: "oc_kid",
    name: "Message Kid",
    title: "Ghost",
    district: "oldcommons",
    power: 26,
    str: 6,
    def: 6,
    spd: 13,
    dex: 12,
    life: 44,
    lootMin: 180,
    lootMax: 420,
    heatOnWin: 5,
    heatOnLose: 3,
    energyCost: 8,
    flavor: "Fast feet, empty pockets on purpose.",
  },
  {
    id: "np_dealer_2",
    name: "Chip Runner",
    title: "Soft target",
    district: "neonpier",
    power: 16,
    str: 4,
    def: 3,
    spd: 9,
    dex: 7,
    life: 38,
    lootMin: 100,
    lootMax: 240,
    heatOnWin: 3,
    heatOnLose: 2,
    energyCost: 7,
    gender: "female",
    persona: "slutty",
    flavor: "Warm plastic, colder math.",
    flavorSlutty: "Warm plastic, colder math — she deals like the night owes her a dance.",
  },
  {
    id: "np_dancer",
    name: "Boardwalk Dancer",
    title: "Lookout",
    district: "neonpier",
    power: 23,
    str: 5,
    def: 5,
    spd: 11,
    dex: 10,
    life: 42,
    lootMin: 140,
    lootMax: 300,
    heatOnWin: 4,
    heatOnLose: 3,
    energyCost: 8,
    gender: "female",
    persona: "slutty",
    flavor: "Neon on skin, tips in pockets.",
    flavorSlutty: "Neon on skin, tips in pockets — she sells the smile before the song.",
  },
  {
    id: "np_barker",
    name: "Pier Barker",
    title: "Muscle",
    district: "neonpier",
    power: 36,
    str: 12,
    def: 10,
    spd: 7,
    dex: 6,
    life: 56,
    lootMin: 180,
    lootMax: 400,
    heatOnWin: 5,
    heatOnLose: 4,
    energyCost: 10,
    gender: "male",
    flavor: "Voice that pulls tourists sideways.",
  },
  {
    id: "np_bartender",
    name: "Neon Bartender",
    title: "Operator",
    district: "neonpier",
    power: 28,
    str: 8,
    def: 7,
    spd: 10,
    dex: 11,
    life: 48,
    lootMin: 200,
    lootMax: 440,
    heatOnWin: 5,
    heatOnLose: 3,
    energyCost: 9,
    gender: "female",
    persona: "slutty",
    flavor: "Drinks that double as invitations.",
    flavorSlutty: "Drinks that double as invitations — last call is a soft window if you linger.",
  },
  {
    id: "np_tech",
    name: "Arcade Tech",
    title: "Fixer",
    district: "neonpier",
    power: 31,
    str: 7,
    def: 8,
    spd: 9,
    dex: 12,
    life: 50,
    lootMin: 220,
    lootMax: 480,
    heatOnWin: 6,
    heatOnLose: 3,
    energyCost: 9,
    gender: "male",
    flavor: "Cabinets that pay sideways.",
  },
  {
    id: "np_photo",
    name: "Photo Booth Girl",
    title: "Enforcer",
    district: "neonpier",
    power: 42,
    str: 14,
    def: 12,
    spd: 6,
    dex: 7,
    life: 62,
    lootMin: 260,
    lootMax: 560,
    heatOnWin: 7,
    heatOnLose: 5,
    energyCost: 11,
    gender: "female",
    flavor: "Strips that never make the board.",
  },
  {
    id: "np_security_f",
    name: "Velvet Rope",
    title: "Ghost",
    district: "neonpier",
    power: 26,
    str: 6,
    def: 6,
    spd: 13,
    dex: 12,
    life: 44,
    lootMin: 180,
    lootMax: 420,
    heatOnWin: 5,
    heatOnLose: 3,
    energyCost: 8,
    gender: "female",
    flavor: "List in one hand, radio in the other.",
  },
  {
    id: "rc_triage",
    name: "Triage Nurse",
    title: "Soft target",
    district: "redclinic",
    power: 16,
    str: 4,
    def: 3,
    spd: 9,
    dex: 7,
    life: 38,
    lootMin: 100,
    lootMax: 240,
    heatOnWin: 3,
    heatOnLose: 2,
    energyCost: 7,
    gender: "female",
    flavor: "Sirens are her metronome.",
  },
  {
    id: "rc_emt",
    name: "Night EMT",
    title: "Lookout",
    district: "redclinic",
    power: 23,
    str: 5,
    def: 5,
    spd: 11,
    dex: 10,
    life: 42,
    lootMin: 140,
    lootMax: 300,
    heatOnWin: 4,
    heatOnLose: 3,
    energyCost: 8,
    gender: "male",
    flavor: "Kits that open more than veins.",
  },
  {
    id: "rc_admin",
    name: "Ward Admin",
    title: "Muscle",
    district: "redclinic",
    power: 36,
    str: 12,
    def: 10,
    spd: 7,
    dex: 6,
    life: 56,
    lootMin: 180,
    lootMax: 400,
    heatOnWin: 5,
    heatOnLose: 4,
    energyCost: 10,
    gender: "female",
    flavor: "Badge doors and quiet books.",
  },
  {
    id: "rc_janitor",
    name: "Night Janitor",
    title: "Operator",
    district: "redclinic",
    power: 28,
    str: 8,
    def: 7,
    spd: 10,
    dex: 11,
    life: 48,
    lootMin: 200,
    lootMax: 440,
    heatOnWin: 5,
    heatOnLose: 3,
    energyCost: 9,
    gender: "male",
    flavor: "Keys to every utility closet.",
  },
  {
    id: "rc_psych",
    name: "Psych Float",
    title: "Fixer",
    district: "redclinic",
    power: 31,
    str: 7,
    def: 8,
    spd: 9,
    dex: 12,
    life: 50,
    lootMin: 220,
    lootMax: 480,
    heatOnWin: 6,
    heatOnLose: 3,
    energyCost: 9,
    gender: "female",
    flavor: "Soft voice, hard files.",
  },
  {
    id: "rc_supply",
    name: "Supply Clerk",
    title: "Enforcer",
    district: "redclinic",
    power: 42,
    str: 14,
    def: 12,
    spd: 6,
    dex: 7,
    life: 62,
    lootMin: 260,
    lootMax: 560,
    heatOnWin: 7,
    heatOnLose: 5,
    energyCost: 11,
    flavor: "Morphine counts that almost match.",
  },
  {
    id: "rc_security_f",
    name: "Ward Security",
    title: "Ghost",
    district: "redclinic",
    power: 26,
    str: 6,
    def: 6,
    spd: 13,
    dex: 12,
    life: 44,
    lootMin: 180,
    lootMax: 420,
    heatOnWin: 5,
    heatOnLose: 3,
    energyCost: 8,
    gender: "female",
    flavor: "Badge and boredom after midnight.",
  },
];
