import type { PropertyDef } from "@/game/types";

export const PROPERTIES_EXTRA: PropertyDef[] = [
  {
    id: "gr_sublet",
    name: "Tram Sublet",
    district: "glassrow",
    cost: 9500,
    weeklyIncome: 150,
    weeklyUpkeep: 65,
    blurb: "Shared neon, shared excuses.",
    raidRisk: 0.85,
  },
  {
    id: "gr_booth",
    name: "Wire Booth Flat",
    district: "glassrow",
    cost: 21000,
    weeklyIncome: 300,
    weeklyUpkeep: 130,
    blurb: "Above the counter. Clean mail.",
    raidRisk: 0.55,
  },
  {
    id: "ms_loft",
    name: "Mill Loft Bay",
    district: "millstone",
    cost: 12500,
    weeklyIncome: 190,
    weeklyUpkeep: 80,
    blurb: "Winch access and dog treaties.",
    raidRisk: 1,
  },
  {
    id: "dr_office",
    name: "Pier Office Lease",
    district: "docksreach",
    cost: 18500,
    weeklyIncome: 250,
    weeklyUpkeep: 115,
    blurb: "Radios overnight. Salt in the vents.",
    raidRisk: 1.1,
  },
  {
    id: "ac_lab",
    name: "Ashcourt Lab Share",
    district: "ashcourt",
    cost: 16000,
    weeklyIncome: 240,
    weeklyUpkeep: 105,
    blurb: "White coats as cover rent.",
    raidRisk: 0.7,
  },
  {
    id: "sy_suite",
    name: "Spire Mid Suite",
    district: "spireyard",
    cost: 36000,
    weeklyIncome: 400,
    weeklyUpkeep: 190,
    blurb: "Not penthouse. Still invoices heat.",
    raidRisk: 0.45,
  },
  {
    id: "oc_basement",
    name: "Commons Basement",
    district: "oldcommons",
    cost: 5500,
    weeklyIncome: 95,
    weeklyUpkeep: 40,
    blurb: "Damp keys. Cheap silence.",
    raidRisk: 1.25,
  },
  {
    id: "oc_roof",
    name: "Roof Shed Keys",
    district: "oldcommons",
    cost: 7200,
    weeklyIncome: 120,
    weeklyUpkeep: 50,
    blurb: "Sightlines and pigeon diplomacy.",
    raidRisk: 1.1,
  },
  {
    id: "np_cabin",
    name: "Boardwalk Cabin",
    district: "neonpier",
    cost: 14000,
    weeklyIncome: 210,
    weeklyUpkeep: 95,
    blurb: "Neon through thin curtains.",
    raidRisk: 1.05,
  },
  {
    id: "np_vip",
    name: "Pier VIP Closet",
    district: "neonpier",
    cost: 26000,
    weeklyIncome: 320,
    weeklyUpkeep: 140,
    blurb: "Tiny, loud, expensive.",
    raidRisk: 0.85,
  },
  {
    id: "rc_staff",
    name: "Staff Housing Wing",
    district: "redclinic",
    cost: 11000,
    weeklyIncome: 170,
    weeklyUpkeep: 75,
    blurb: "Sirens included in rent.",
    raidRisk: 0.8,
  },
  {
    id: "rc_quiet",
    name: "Quiet Observation Flat",
    district: "redclinic",
    cost: 24000,
    weeklyIncome: 300,
    weeklyUpkeep: 130,
    blurb: "Badge doors, soft books.",
    raidRisk: 0.65,
  },
];
