import type {
  AwardDef,
  ContactDef,
  CourseDef,
  LicenseDef,
  GigDef,
  ItemDef,
  NpcDef,
  PropertyDef,
} from "@/game/types";

export { DISTRICTS } from "@/content/districts";
export { CRIMES } from "@/content/crimes";
export { JOBS } from "@/content/jobs";
export { HEISTS, getHeist } from "@/content/heists";
export {
  SAFEHOUSE_ROOMS,
  ARMORY_RECIPES,
  getSafehouseRoom,
} from "@/content/safehouse";

import { CRIMES } from "@/content/crimes";
import { DISTRICTS } from "@/content/districts";
import { JOBS } from "@/content/jobs";
import { COURSES_EXTRA, LICENSES_EXTRA } from "@/content/coursesExtra";
import {
  AWARDS_EXTRA,
  ITEMS_EXTRA,
  NPCS_EXTRA,
  PROPERTIES_EXTRA,
  RANK_TITLES_EXTRA,
} from "@/content/density";

export const GIGS: GigDef[] = [
  {
    id: "courier_drop",
    name: "Courier drop",
    blurb: "Bag A to B before the bag sweats. Clean cash, soft legs.",
    basePay: 280,
    energy: 3,
    districtBias: ["glassrow", "millstone"],
    legitimacyGain: 0.3,
    special: "Extra tip",
  },
  {
    id: "data_entry",
    name: "Data entry sprint",
    blurb: "Keys and coffee. No glory, honest hours.",
    basePay: 320,
    energy: 4,
    districtBias: ["glassrow"],
    legitimacyGain: 0.4,
    special: "Overtime stub",
  },
  {
    id: "night_watch",
    name: "Night watch",
    blurb: "Sit still, log shadows. Civic clients hate heat on your file.",
    basePay: 380,
    energy: 4,
    districtBias: ["millstone", "docksreach"],
    maxHeat: 45,
    legitimacyGain: 0.5,
    special: "Quiet bonus",
  },
  {
    id: "tutoring",
    name: "Tutoring hour",
    blurb: "Explain City Navigation to someone who still gets lost.",
    basePay: 340,
    energy: 3,
    districtBias: ["glassrow", "millstone"],
    requiresCourse: "se1",
    legitimacyGain: 0.6,
    special: "Grateful tip",
  },
  {
    id: "pier_walk",
    name: "Pier walk gig",
    blurb: "Escort tourists past the cranes. Stress bleeds into the water.",
    basePay: 220,
    energy: 3,
    districtBias: ["docksreach"],
    happyGain: 25,
    legitimacyGain: 0.2,
    special: "Calm stretch",
  },
  {
    id: "campus_filing",
    name: "Campus filing",
    blurb: "Work-study adjacent. Stacks of paper, stipend-adjacent pay.",
    basePay: 260,
    energy: 3,
    districtBias: ["millstone", "glassrow"],
    requiresStudy: true,
    legitimacyGain: 0.5,
    special: "Advisor nod",
  },
  {
    id: "freight_assist",
    name: "Freight assist",
    blurb: "Move crates without asking what’s inside. Dock hours.",
    basePay: 420,
    energy: 4,
    districtBias: ["docksreach"],
    requiresLevel: 2,
    legitimacyGain: 0.3,
    special: "Yard tip",
  },
  {
    id: "civic_clipboard",
    name: "Civic clipboard",
    blurb: "Survey forms for the city. Your heat must look boring.",
    basePay: 360,
    energy: 3,
    districtBias: ["glassrow"],
    maxHeat: 30,
    requiresLevel: 2,
    legitimacyGain: 0.8,
    special: "Civic stamp",
  },
  {
    id: "clinic_aide",
    name: "Clinic aide shift",
    blurb: "Ashcourt overflow desk. First-aid paper makes the clipboard legal.",
    basePay: 400,
    energy: 4,
    districtBias: ["ashcourt"],
    requiresCourse: "mc1",
    maxHeat: 40,
    legitimacyGain: 0.7,
    special: "Ward tip",
  },
  {
    id: "locksmith_call",
    name: "Legal locksmith call",
    blurb: "Locked out of a Glassrow walk-up. Cert in the bag, cash clean.",
    basePay: 480,
    energy: 4,
    districtBias: ["glassrow", "millstone"],
    requiresCourse: "le1",
    maxHeat: 35,
    legitimacyGain: 0.6,
    special: "Grateful tip",
  },
  {
    id: "bike_courier",
    name: "Bike courier sprint",
    blurb: "Pedals and rain. Glassrow lunch boxes that can't wait.",
    basePay: 250,
    energy: 3,
    districtBias: ["glassrow", "oldcommons"],
    legitimacyGain: 0.25,
    special: "Rush tip",
  },
  {
    id: "market_stall",
    name: "Market stall cover",
    blurb: "Watch tills while the owner grabs coffee. Soft eyes only.",
    basePay: 300,
    energy: 3,
    districtBias: ["oldcommons", "millstone"],
    maxHeat: 50,
    legitimacyGain: 0.35,
    special: "Till bonus",
  },
  {
    id: "trash_route",
    name: "Alley trash route",
    blurb: "Bags, bins, and early hours. Nobody asks for a résumé.",
    basePay: 240,
    energy: 4,
    districtBias: ["oldcommons", "millstone"],
    legitimacyGain: 0.2,
    special: "Found scrap",
  },
  {
    id: "neon_flyer",
    name: "Neon flyer stack",
    blurb: "Staple handbills under pier lights. Legs and wet ink.",
    basePay: 270,
    energy: 3,
    districtBias: ["neonpier", "glassrow"],
    happyGain: 10,
    legitimacyGain: 0.2,
    special: "Club tip",
  },
  {
    id: "ward_errands",
    name: "Ward errand run",
    blurb: "Forms between Red Clinic desks. Keep the clipboard dry.",
    basePay: 350,
    energy: 3,
    districtBias: ["redclinic", "ashcourt"],
    maxHeat: 40,
    requiresLevel: 2,
    legitimacyGain: 0.55,
    special: "Nurse tip",
  },
  {
    id: "spire_reception",
    name: "Spire desk cover",
    blurb: "Smile, badge, silence. Elite floors hate street noise.",
    basePay: 520,
    energy: 4,
    districtBias: ["spireyard"],
    maxHeat: 25,
    requiresLevel: 4,
    legitimacyGain: 0.9,
    special: "Envelope tip",
  },
  {
    id: "ledger_audit",
    name: "Ledger audit assist",
    blurb: "Tick boxes for a Commerce tutor. Numbers that stay clean.",
    basePay: 440,
    energy: 4,
    districtBias: ["glassrow", "spireyard"],
    requiresCourse: "cf1",
    legitimacyGain: 0.7,
    special: "Tutor bonus",
  },
  {
    id: "container_count",
    name: "Container count",
    blurb: "Bay numbers vs the sheet. Harbor cert helps the whistle.",
    basePay: 460,
    energy: 4,
    districtBias: ["docksreach"],
    requiresCourse: "hl1",
    requiresLevel: 2,
    legitimacyGain: 0.55,
    special: "Yard stamp",
  },
  {
    id: "lab_cleanup",
    name: "Lab cleanup shift",
    blurb: "Ashcourt glassware and gloves. Protocols before mop water.",
    basePay: 390,
    energy: 4,
    districtBias: ["ashcourt", "redclinic"],
    requiresCourse: "mc1",
    legitimacyGain: 0.6,
    special: "Lab tip",
  },
  {
    id: "parking_patrol",
    name: "Parking lot patrol",
    blurb: "Walk rows, note plates. Civic clients want a boring file.",
    basePay: 310,
    energy: 3,
    districtBias: ["millstone", "ashcourt"],
    maxHeat: 35,
    requiresLevel: 2,
    legitimacyGain: 0.5,
    special: "Quiet hour",
  },
  {
    id: "moving_crew",
    name: "Moving crew hour",
    blurb: "Sofas and stairs. Millstone flats that never fit elevators.",
    basePay: 360,
    energy: 5,
    districtBias: ["millstone", "oldcommons"],
    legitimacyGain: 0.3,
    special: "Cash tip",
  },
  {
    id: "food_runner",
    name: "Kitchen food runner",
    blurb: "Hot plates through a busy line. No heat on your apron.",
    basePay: 290,
    energy: 3,
    districtBias: ["glassrow", "neonpier"],
    maxHeat: 55,
    happyGain: 8,
    legitimacyGain: 0.25,
    special: "Kitchen tip",
  },
  {
    id: "library_shelve",
    name: "Library shelving",
    blurb: "Stacks and silence. Study track or finished credits only.",
    basePay: 255,
    energy: 3,
    districtBias: ["millstone", "ashcourt"],
    requiresStudy: true,
    legitimacyGain: 0.45,
    special: "Quiet bonus",
  },
  {
    id: "ferry_ticket",
    name: "Ferry ticket booth",
    blurb: "Stamps and smiles on the pier. Tourists tip if you're kind.",
    basePay: 330,
    energy: 3,
    districtBias: ["neonpier", "docksreach"],
    happyGain: 15,
    legitimacyGain: 0.35,
    special: "Tour tip",
  },
  {
    id: "event_setup",
    name: "Event chair setup",
    blurb: "Folding chairs before a Spire mixer. Clean hands preferred.",
    basePay: 410,
    energy: 4,
    districtBias: ["spireyard", "glassrow"],
    maxHeat: 40,
    requiresLevel: 3,
    legitimacyGain: 0.5,
    special: "Host tip",
  },
  {
    id: "blood_drive",
    name: "Blood drive clerk",
    blurb: "Clipboards and cotton. First aid paper makes it legal.",
    basePay: 370,
    energy: 3,
    districtBias: ["redclinic", "ashcourt"],
    requiresCourse: "mc1",
    maxHeat: 45,
    legitimacyGain: 0.65,
    special: "Clinic stamp",
  },
  {
    id: "yard_sweep",
    name: "Yard sweep contract",
    blurb: "Brooms and grit behind Millstone shops. Early shift, honest pay.",
    basePay: 275,
    energy: 4,
    districtBias: ["millstone"],
    legitimacyGain: 0.25,
    special: "Shop tip",
  },
  {
    id: "translate_desk",
    name: "Translate desk hour",
    blurb: "Forms for people who hate forms. Persuasion basics helps.",
    basePay: 380,
    energy: 3,
    districtBias: ["glassrow", "oldcommons"],
    requiresCourse: "se2",
    legitimacyGain: 0.55,
    special: "Grateful tip",
  },
  {
    id: "cold_storage",
    name: "Cold storage check",
    blurb: "Walk freezers, log temps. Harbor routing cert preferred.",
    basePay: 450,
    energy: 4,
    districtBias: ["docksreach", "neonpier"],
    requiresCourse: "hl2",
    requiresLevel: 4,
    legitimacyGain: 0.5,
    special: "Route tip",
  },
  {
    id: "shelter_shift",
    name: "Shelter night shift",
    blurb: "Cots and coffee in Old Commons. Heat must look boring.",
    basePay: 340,
    energy: 4,
    districtBias: ["oldcommons"],
    maxHeat: 30,
    requiresLevel: 2,
    legitimacyGain: 0.75,
    happyGain: 12,
    special: "Civic thanks",
  },
  {
    id: "press_run",
    name: "Press flyer run",
    blurb: "Bundle papers for the night edition. Legs before dawn.",
    basePay: 295,
    energy: 3,
    districtBias: ["glassrow", "ashcourt"],
    legitimacyGain: 0.3,
    special: "Editor tip",
  },
  {
    id: "tool_lend",
    name: "Tool library desk",
    blurb: "Check out drills without the drama. Locksmith paper helps.",
    basePay: 400,
    energy: 3,
    districtBias: ["millstone"],
    requiresCourse: "le1",
    maxHeat: 40,
    legitimacyGain: 0.55,
    special: "Member tip",
  },
  {
    id: "museum_rope",
    name: "Museum rope crew",
    blurb: "Velvet lines before opening. Soft shoes, softer heat.",
    basePay: 430,
    energy: 3,
    districtBias: ["glassrow", "spireyard"],
    requiresCourse: "se2",
    maxHeat: 35,
    requiresLevel: 3,
    legitimacyGain: 0.6,
    special: "Curator tip",
  },
  {
    id: "ambulance_stock",
    name: "Ambulance restock",
    blurb: "Kits and seals at Red Clinic bay. Protocols matter.",
    basePay: 470,
    energy: 4,
    districtBias: ["redclinic"],
    requiresCourse: "mc2",
    requiresLevel: 4,
    maxHeat: 40,
    legitimacyGain: 0.7,
    special: "Bay tip",
  },
  {
    id: "invoice_match",
    name: "Invoice match desk",
    blurb: "Shell-company homework for a clean client. Commerce track.",
    basePay: 500,
    energy: 4,
    districtBias: ["spireyard", "glassrow"],
    requiresCourse: "cf2",
    requiresLevel: 5,
    maxHeat: 30,
    legitimacyGain: 0.85,
    special: "Client bonus",
  },
];

const COURSES_CORE: CourseDef[] = [
  {
    id: "se1",
    school: "Street Electives",
    name: "City Navigation",
    hours: 12,
    fee: 200,
    stipendPerHour: 20,
    blurb: "Maps, cameras, and soft exits. Gates street warehouse/pharmacy work.",
    unlocks: ["warehouse", "pharmacy", "dock_pierce", "chop_shop", "chop_fleet"],
    oddsBonus: 5,
    oddsFamilies: ["street"],
  },
  {
    id: "se2",
    school: "Street Electives",
    name: "Persuasion Basics",
    hours: 24,
    fee: 400,
    stipendPerHour: 30,
    blurb: "Talk soft, walk hard. Kitchen promotion exam + museum after-hours gate.",
    requiresCourse: "se1",
    gigPayBonus: 10,
    oddsBonus: 3,
    oddsFamilies: ["petty", "street"],
    unlocks: ["museum"],
  },
  {
    id: "se3",
    school: "Street Electives",
    name: "Fitness Study",
    hours: 18,
    fee: 300,
    stipendPerHour: 25,
    blurb: "Classroom bulk. Raises gym soft cap permanently.",
    requiresCourse: "se1",
    softCapBonus: 5,
  },
  {
    id: "se4",
    school: "Street Electives",
    name: "Alley Networks",
    hours: 30,
    fee: 650,
    stipendPerHour: 35,
    blurb: "Who nods, who rats. Gig rates climb; street odds get sharper.",
    requiresCourse: "se2",
    requiresLevel: 3,
    gigPayBonus: 8,
    oddsBonus: 4,
    oddsFamilies: ["street"],
    unlocks: ["arson_scout", "jewel_case"],
  },
  {
    id: "cf1",
    school: "Commerce & Finance",
    name: "Bookkeeping",
    hours: 24,
    fee: 500,
    stipendPerHour: 40,
    blurb: "Clean ledgers. Job pay up, bank interest up, retail promotion exam.",
    requiresLevel: 2,
    jobPayBonus: 5,
    bankInterestBonus: 0.5,
    unlocks: ["badge_clone", "aide_blackmail", "evidence_locker", "casino_tip", "spire_mailroom", "news_archive"],
  },
  {
    id: "cf2",
    school: "Commerce & Finance",
    name: "Business Basics",
    hours: 48,
    fee: 1000,
    stipendPerHour: 50,
    blurb: "Fronts and floats. Unlocks cage, vault, and fraud heavies.",
    requiresCourse: "cf1",
    unlocks: ["casino_cage", "courier", "evidence_room", "private_vault", "evidence_swap", "bond_fraud", "armored_depot", "casino_count", "casino_armored", "bank_night", "mayor_safe"],
    oddsBonus: 4,
    oddsFamilies: ["heavy"],
  },
  {
    id: "cf3",
    school: "Commerce & Finance",
    name: "Shell Companies",
    hours: 36,
    fee: 1400,
    stipendPerHour: 55,
    blurb: "Paper walls that hold. Bank rate climbs; heavy fraud runs quieter.",
    requiresCourse: "cf2",
    requiresLevel: 5,
    jobPayBonus: 6,
    bankInterestBonus: 0.75,
    oddsBonus: 3,
    oddsFamilies: ["heavy"],
    unlocks: ["city_vault", "bond_warehouse", "embassy_bag"],
  },
  {
    id: "hl1",
    school: "Harbor & Logistics",
    name: "Dock Safety",
    hours: 18,
    fee: 400,
    stipendPerHour: 35,
    blurb: "Cert for cranes and containers. Unlocks harbor heist; dock promotion exam.",
    requiresLevel: 2,
    unlocks: ["harbor", "dock_pierce", "airport_cargo", "train_arms", "shipping_label", "harbor_fuel", "fuel_depot"],
    jobPayBonus: 10,
    oddsBonus: 5,
    oddsFamilies: ["heavy"],
  },
  {
    id: "hl2",
    school: "Harbor & Logistics",
    name: "Container Routing",
    hours: 28,
    fee: 750,
    stipendPerHour: 45,
    blurb: "Bay numbers that don’t match the sheet. Heavy odds and dock pay.",
    requiresCourse: "hl1",
    requiresLevel: 4,
    jobPayBonus: 8,
    oddsBonus: 4,
    oddsFamilies: ["heavy"],
    unlocks: ["rail_mail", "port_crane", "harbor_customs", "arms_barge", "rail_arms"],
  },
  {
    id: "hl3",
    school: "Harbor & Logistics",
    name: "Yard Boss Theory",
    hours: 40,
    fee: 1200,
    stipendPerHour: 55,
    blurb: "Who owns the whistle. Dock ladder exam + cleaner heavy exits.",
    requiresCourse: "hl2",
    requiresLevel: 6,
    jobPayBonus: 10,
    oddsBonus: 3,
    oddsFamilies: ["heavy"],
    unlocks: ["airport_vault"],
  },
  {
    id: "mc1",
    school: "Med & Civic",
    name: "First Aid",
    hours: 16,
    fee: 350,
    stipendPerHour: 30,
    blurb: "Tourniquets and ward clocks. Cuts hospital stays; orderly exam path.",
    requiresLevel: 2,
    hospitalTimeReduction: 15,
    jobPayBonus: 4,
    unlocks: ["ambulance_kit", "clinic_sample"],
  },
  {
    id: "mc2",
    school: "Med & Civic",
    name: "Clinic Protocols",
    hours: 28,
    fee: 700,
    stipendPerHour: 40,
    blurb: "Badge paths through Ashcourt. Unlocks hospital pharmacy vault.",
    requiresCourse: "mc1",
    requiresLevel: 4,
    hospitalTimeReduction: 10,
    unlocks: ["hospital_vault", "blood_bank", "ambulance_kit", "clinic_sample"],
    oddsBonus: 4,
    oddsFamilies: ["street", "heavy"],
  },
  {
    id: "mc3",
    school: "Med & Civic",
    name: "Know Your Rights",
    hours: 24,
    fee: 600,
    stipendPerHour: 35,
    blurb: "Civic exits under pressure. Legitimacy face + soft street odds.",
    requiresCourse: "mc1",
    requiresLevel: 3,
    gigPayBonus: 6,
    oddsBonus: 3,
    oddsFamilies: ["street"],
    jobPayBonus: 3,
    unlocks: ["lab_isolator"],
  },
  {
    id: "le1",
    school: "Locks & Entry",
    name: "Legal Locksmith",
    hours: 20,
    fee: 450,
    stipendPerHour: 32,
    blurb: "Pins and paperwork. Legal calls by day; sharper entry odds by night.",
    requiresLevel: 2,
    requiresCourse: "se1",
    oddsBonus: 4,
    oddsFamilies: ["petty", "street"],
    jobPayBonus: 3,
    unlocks: ["advanced_lock", "pawn_safe", "laundry_vault"],
  },
  {
    id: "le2",
    school: "Locks & Entry",
    name: "Safe Mechanics",
    hours: 36,
    fee: 900,
    stipendPerHour: 45,
    blurb: "Dial feel and drill patience. Hotel safes and vault work run cleaner.",
    requiresCourse: "le1",
    requiresLevel: 4,
    oddsBonus: 5,
    oddsFamilies: ["street", "heavy"],
    jobPayBonus: 4,
    unlocks: ["hotel_safe", "yacht_safe", "pier_vault"],
  },
  {
    id: "le3",
    school: "Locks & Entry",
    name: "Vault Dial Theory",
    hours: 42,
    fee: 1300,
    stipendPerHour: 50,
    blurb: "Feel the drop. Heavy vault work runs quieter with the right paper.",
    requiresCourse: "le2",
    requiresLevel: 6,
    oddsBonus: 4,
    oddsFamilies: ["heavy"],
    jobPayBonus: 5,
    unlocks: ["private_vault", "museum_vault", "spire_pent"],
  },
  {
    id: "se5",
    school: "Street Electives",
    name: "Fence Networks",
    hours: 36,
    fee: 900,
    stipendPerHour: 40,
    blurb: "Who buys quiet. Gig rates climb; street exits get cleaner.",
    requiresCourse: "se4",
    requiresLevel: 5,
    gigPayBonus: 10,
    oddsBonus: 3,
    oddsFamilies: ["street"],
    unlocks: ["syndicate_ledger"],
  },
  {
    id: "cf4",
    school: "Commerce & Finance",
    name: "Audit Defense",
    hours: 40,
    fee: 1600,
    stipendPerHour: 60,
    blurb: "Books that survive a knock. Bank rate and legitimacy face.",
    requiresCourse: "cf3",
    requiresLevel: 7,
    jobPayBonus: 5,
    bankInterestBonus: 0.5,
    oddsBonus: 2,
    oddsFamilies: ["heavy"],
  },
  {
    id: "hl4",
    school: "Harbor & Logistics",
    name: "Night Manifests",
    hours: 44,
    fee: 1500,
    stipendPerHour: 58,
    blurb: "Bay numbers that exist twice. Heavy dock odds and yard pay.",
    requiresCourse: "hl3",
    requiresLevel: 7,
    jobPayBonus: 8,
    oddsBonus: 4,
    oddsFamilies: ["heavy"],
  },
  {
    id: "mc4",
    school: "Med & Civic",
    name: "Trauma Desk",
    hours: 32,
    fee: 950,
    stipendPerHour: 45,
    blurb: "Ward overflow grammar. Hospital time softens further.",
    requiresCourse: "mc2",
    requiresLevel: 5,
    hospitalTimeReduction: 12,
    jobPayBonus: 4,
  },
  {
    id: "sy1",
    school: "Systems & Signals",
    name: "Radio Discipline",
    hours: 18,
    fee: 420,
    stipendPerHour: 32,
    blurb: "Scanner etiquette. Soft street odds and quieter sweeps.",
    requiresLevel: 2,
    oddsBonus: 3,
    oddsFamilies: ["street"],
    gigPayBonus: 5,
    unlocks: ["atm_skimmer", "wire_tap", "dock_radio"],
  },
  {
    id: "sy2",
    school: "Systems & Signals",
    name: "Camera Blind Spots",
    hours: 28,
    fee: 780,
    stipendPerHour: 42,
    blurb: "Where the lens lies. Petty and street edges.",
    requiresCourse: "sy1",
    requiresLevel: 3,
    oddsBonus: 4,
    oddsFamilies: ["petty", "street"],
    unlocks: ["office_server"],
  },
  {
    id: "sy3",
    school: "Systems & Signals",
    name: "Encrypted Drops",
    hours: 36,
    fee: 1100,
    stipendPerHour: 50,
    blurb: "Dead drops that stay dead. Heavy courier work runs cleaner.",
    requiresCourse: "sy2",
    requiresLevel: 5,
    oddsBonus: 4,
    oddsFamilies: ["heavy"],
    gigPayBonus: 8,
    unlocks: ["data_center", "telecom_hub", "federal_drop"],
  },
  {
    id: "sy4",
    school: "Systems & Signals",
    name: "City Mesh Ops",
    hours: 48,
    fee: 1700,
    stipendPerHour: 60,
    blurb: "Own the chatter. Soft caps on heat crits via better exits.",
    requiresCourse: "sy3",
    requiresLevel: 7,
    oddsBonus: 3,
    oddsFamilies: ["street", "heavy"],
    jobPayBonus: 5,
    unlocks: ["wire_exchange"],
  },
];

/** AAA live pack — 48 courses. */
export const COURSES: CourseDef[] = [...COURSES_CORE, ...COURSES_EXTRA];

/** One license per campus course — granted on complete; stacks with transcript perks */
const LICENSES_CORE: LicenseDef[] = [
  {
    id: "nav_permit",
    name: "Street Navigation Permit",
    courseId: "se1",
    blurb: "City maps stamped legal. Soft exits count as civic know-how.",
    oddsBonus: 2,
    oddsFamilies: ["street"],
    legitimacyGain: 3,
    weeklyStipend: 15,
  },
  {
    id: "persuasion_cert",
    name: "Civic Persuasion Cert",
    courseId: "se2",
    blurb: "Talk soft on paperwork. Opens cleaner freelance rates.",
    jobPayBonus: 2,
    legitimacyGain: 2,
    weeklyStipend: 20,
  },
  {
    id: "fitness_cert",
    name: "Campus Fitness Cert",
    courseId: "se3",
    blurb: "School gym card that still clears civic desk checks.",
    legitimacyGain: 1,
    weeklyStipend: 10,
  },
  {
    id: "alley_network_pass",
    name: "Alley Network Pass",
    courseId: "se4",
    blurb: "Introductions that stick. Freelance rates notice.",
    jobPayBonus: 2,
    oddsBonus: 2,
    oddsFamilies: ["street"],
    legitimacyGain: 2,
    weeklyStipend: 25,
  },
  {
    id: "commerce_cert",
    name: "Commerce Cert",
    courseId: "cf1",
    blurb: "Bookkeeping seal. Banks and landlords trust the ink.",
    jobPayBonus: 3,
    bankInterestBonus: 0.5,
    legitimacyGain: 4,
    weeklyStipend: 40,
  },
  {
    id: "business_license",
    name: "Business Operator License",
    courseId: "cf2",
    blurb: "Fronts and floats on the clean ledger. Pay scales up.",
    jobPayBonus: 5,
    bankInterestBonus: 0.25,
    legitimacyGain: 5,
    weeklyStipend: 60,
  },
  {
    id: "shell_operator",
    name: "Shell Operator Seal",
    courseId: "cf3",
    blurb: "Paper walls the city still stamps. Interest likes the structure.",
    jobPayBonus: 4,
    bankInterestBonus: 0.5,
    legitimacyGain: 5,
    weeklyStipend: 70,
  },
  {
    id: "harbor_safety",
    name: "Harbor Safety Cert",
    courseId: "hl1",
    blurb: "Crane and container clearance. Docks pay better; heavy work runs cleaner.",
    jobPayBonus: 4,
    oddsBonus: 3,
    oddsFamilies: ["heavy"],
    legitimacyGain: 3,
    weeklyStipend: 35,
  },
  {
    id: "container_routing",
    name: "Container Routing Cert",
    courseId: "hl2",
    blurb: "Bay grammar on a badge. Yard pay and heavy edges.",
    jobPayBonus: 5,
    oddsBonus: 2,
    oddsFamilies: ["heavy"],
    legitimacyGain: 3,
    weeklyStipend: 45,
  },
  {
    id: "yard_boss",
    name: "Yard Boss Endorsement",
    courseId: "hl3",
    blurb: "Whistle authority. Dock ladder respects the seal.",
    jobPayBonus: 6,
    oddsBonus: 2,
    oddsFamilies: ["heavy"],
    legitimacyGain: 4,
    weeklyStipend: 55,
  },
  {
    id: "med_aide",
    name: "Med Aide Cert",
    courseId: "mc1",
    blurb: "Clinic stamp. Ward clocks run shorter; orderly floors trust you.",
    hospitalTimeReduction: 10,
    jobPayBonus: 3,
    legitimacyGain: 4,
    weeklyStipend: 30,
  },
  {
    id: "clinic_protocols",
    name: "Clinic Protocols Seal",
    courseId: "mc2",
    blurb: "Ashcourt badge paths. Pharmacy doors and quieter heavy work.",
    hospitalTimeReduction: 5,
    oddsBonus: 2,
    oddsFamilies: ["street", "heavy"],
    legitimacyGain: 3,
    weeklyStipend: 40,
  },
  {
    id: "civic_rights",
    name: "Civic Rights Card",
    courseId: "mc3",
    blurb: "Know-your-rights ink. Clean exits and soft freelance rates.",
    jobPayBonus: 2,
    legitimacyGain: 5,
    weeklyStipend: 35,
  },
  {
    id: "locksmith_license",
    name: "Locksmith License",
    courseId: "le1",
    blurb: "Legal entry calls. Pins count as civic skill when stamped.",
    oddsBonus: 2,
    oddsFamilies: ["petty", "street"],
    jobPayBonus: 2,
    legitimacyGain: 3,
    weeklyStipend: 28,
  },
  {
    id: "safe_mech",
    name: "Safe Mechanics Endorsement",
    courseId: "le2",
    blurb: "Dial and drill paper. Vault work looks almost legitimate.",
    oddsBonus: 3,
    oddsFamilies: ["street", "heavy"],
    jobPayBonus: 3,
    legitimacyGain: 3,
    weeklyStipend: 42,
  },
  {
    id: "vault_dial",
    name: "Vault Dial Endorsement",
    courseId: "le3",
    blurb: "Heavy vault feel on a civic card. Quiet exits count.",
    oddsBonus: 3,
    oddsFamilies: ["heavy"],
    jobPayBonus: 4,
    legitimacyGain: 4,
    weeklyStipend: 50,
  },
  {
    id: "fence_network",
    name: "Fence Network Pass",
    courseId: "se5",
    blurb: "Buyers who stay quiet. Freelance rates notice.",
    oddsBonus: 2,
    oddsFamilies: ["street"],
    legitimacyGain: 2,
    weeklyStipend: 30,
  },
  {
    id: "audit_defense",
    name: "Audit Defense Seal",
    courseId: "cf4",
    blurb: "Books that survive a knock. Interest and legitimacy climb.",
    jobPayBonus: 4,
    bankInterestBonus: 0.5,
    legitimacyGain: 5,
    weeklyStipend: 75,
  },
  {
    id: "night_manifest",
    name: "Night Manifest Cert",
    courseId: "hl4",
    blurb: "Bay numbers that exist twice. Dock pay and heavy edges.",
    jobPayBonus: 6,
    oddsBonus: 3,
    oddsFamilies: ["heavy"],
    legitimacyGain: 3,
    weeklyStipend: 60,
  },
  {
    id: "trauma_desk",
    name: "Trauma Desk Cert",
    courseId: "mc4",
    blurb: "Ward overflow grammar. Hospital clocks soften further.",
    hospitalTimeReduction: 8,
    jobPayBonus: 3,
    legitimacyGain: 4,
    weeklyStipend: 42,
  },
  {
    id: "radio_discipline",
    name: "Radio Discipline Card",
    courseId: "sy1",
    blurb: "Scanner etiquette stamped. Soft street odds.",
    oddsBonus: 2,
    oddsFamilies: ["street"],
    legitimacyGain: 2,
    weeklyStipend: 22,
  },
  {
    id: "camera_blind",
    name: "Camera Blind Spot Cert",
    courseId: "sy2",
    blurb: "Where the lens lies. Petty and street edges.",
    oddsBonus: 3,
    oddsFamilies: ["petty", "street"],
    legitimacyGain: 2,
    weeklyStipend: 35,
  },
  {
    id: "encrypted_drops",
    name: "Encrypted Drops Seal",
    courseId: "sy3",
    blurb: "Dead drops that stay dead. Heavy courier edges.",
    oddsBonus: 3,
    oddsFamilies: ["heavy"],
    legitimacyGain: 3,
    weeklyStipend: 45,
  },
  {
    id: "city_mesh",
    name: "City Mesh Ops License",
    courseId: "sy4",
    blurb: "Own the chatter. Soft exits on street and heavy work.",
    oddsBonus: 2,
    oddsFamilies: ["street", "heavy"],
    jobPayBonus: 4,
    legitimacyGain: 4,
    weeklyStipend: 65,
  },
];

/** AAA live pack — 48 licenses (1:1 with courses). */
export const LICENSES: LicenseDef[] = [...LICENSES_CORE, ...LICENSES_EXTRA];

const ITEMS_CORE: ItemDef[] = [
  { id: "crowbar", name: "Crowbar", kind: "tool", baseValue: 100, toolMod: 4, description: "Opens car doors and stubborn crates." },
  { id: "shim_kit", name: "Shim kit", kind: "tool", baseValue: 150, toolMod: 5, description: "Quiet entry for street work." },
  { id: "lockpick", name: "Lockpick set", kind: "tool", baseValue: 400, toolMod: 8, description: "Serious entry kit." },
  { id: "vest", name: "Basic armor vest", kind: "armor", baseValue: 1000, description: "Takes the edge off a bad night." },
  { id: "street_meds", name: "Street meds", kind: "consumable", baseValue: 60, description: "+15 life." },
  { id: "happy_pills", name: "Happy pills", kind: "consumable", baseValue: 120, description: "+40 happy." },
  { id: "bike", name: "Used bike", kind: "misc", baseValue: 300, description: "Fenceable scrap with wheels." },
  { id: "courier_bag", name: "Courier bag", kind: "misc", baseValue: 600, description: "Looks legit. Isn’t." },
  { id: "harbor_key", name: "Harbor keycard", kind: "tool", baseValue: 2500, toolMod: 6, description: "Rare dock access." },
  { id: "chip_stack", name: "Casino chip stack", kind: "misc", baseValue: 1800, description: "Warm plastic money." },
  { id: "knife", name: "Folding knife", kind: "weapon", baseValue: 200, description: "Close work." },
  { id: "bat", name: "Weighted bat", kind: "weapon", baseValue: 350, description: "Negotiation aid." },
  { id: "painkillers", name: "Painkillers", kind: "consumable", baseValue: 40, description: "+10 life, -5 stress." },
  { id: "evidence_burn", name: "Burn kit", kind: "consumable", baseValue: 500, description: "Drops investigation one stage." },
  { id: "threads", name: "Basic threads", kind: "flex", baseValue: 2000, description: "Respect starter kit." },
  { id: "suit", name: "Custom suit", kind: "flex", baseValue: 15000, description: "Looks like money." },
  { id: "food", name: "Leftover kit", kind: "consumable", baseValue: 30, description: "+20 happy." },
  { id: "lawyer_retainer", name: "Lawyer card", kind: "misc", baseValue: 2000, description: "One investigation stage down." },
  { id: "radio", name: "Scanner radio", kind: "tool", baseValue: 450, toolMod: 2, description: "Hear sweeps coming." },
  { id: "gloves", name: "Grip gloves", kind: "tool", baseValue: 80, toolMod: 1, description: "Fewer prints, better grip." },
  { id: "badge_blank", name: "Badge blank", kind: "tool", baseValue: 900, toolMod: 3, description: "Clone office access when the ink is warm." },
  { id: "drill_bit", name: "Quiet drill bit", kind: "tool", baseValue: 3200, toolMod: 7, description: "Vault work. Loud if you rush." },
  // AAA expansion
  { id: "flashbang", name: "Street flashbang", kind: "consumable", baseValue: 800, description: "Noise and light. Escape window on a bad roll." },
  { id: "smoke_can", name: "Smoke canister", kind: "consumable", baseValue: 350, description: "Cheap cover for alley exits." },
  { id: "wire_cutters", name: "Wire cutters", kind: "tool", baseValue: 180, toolMod: 2, description: "Fences, seals, and stubborn copper." },
  { id: "stethoscope", name: "Safe stethoscope", kind: "tool", baseValue: 600, toolMod: 4, description: "Hear the drop before you feel it." },
  { id: "fake_id", name: "Fake civic ID", kind: "tool", baseValue: 1200, toolMod: 3, description: "Soft doors that check faces." },
  { id: "thermal_lance", name: "Pocket thermal lance", kind: "tool", baseValue: 4500, toolMod: 9, description: "Quiet until it isn’t. Vault specialty." },
  { id: "brass_knuckles", name: "Brass knuckles", kind: "weapon", baseValue: 280, description: "Close-range persuasion." },
  { id: "tactical_baton", name: "Tactical baton", kind: "weapon", baseValue: 550, description: "Reach without a gun charge." },
  { id: "kevlar_liner", name: "Kevlar liner", kind: "armor", baseValue: 2800, description: "Under a jacket. Takes real hits." },
  { id: "riot_plate", name: "Riot plate insert", kind: "armor", baseValue: 5200, description: "Heavy. Survives the wrong alley." },
  { id: "adrenaline", name: "Adrenaline shot", kind: "consumable", baseValue: 200, description: "+25 life, +10 energy feel." },
  { id: "focus_tabs", name: "Focus tabs", kind: "consumable", baseValue: 160, description: "-10 stress, sharper odds window." },
  { id: "disguise_kit", name: "Disguise kit", kind: "misc", baseValue: 900, description: "Face that isn’t yours for one sweep." },
  { id: "fence_ledger", name: "Fence ledger", kind: "misc", baseValue: 1500, description: "Names that buy quiet." },
  { id: "skip_tracer", name: "Skip-tracer notes", kind: "misc", baseValue: 700, description: "Who owes whom. Useful leverage." },
  { id: "gold_chain", name: "Gold chain", kind: "flex", baseValue: 4500, description: "Respect that catches light." },
  { id: "watch_lux", name: "Lobby watch", kind: "flex", baseValue: 9000, description: "Looks like SpireYard money." },
  { id: "night_vision", name: "Compact night scope", kind: "tool", baseValue: 2100, toolMod: 5, description: "Roof work and dark bays." },
  { id: "emp_fob", name: "EMP key fob", kind: "tool", baseValue: 3800, toolMod: 6, description: "Softens electronic locks briefly." },
  { id: "med_foam", name: "Trauma foam", kind: "consumable", baseValue: 90, description: "+20 life, sticky and loud." },
  { id: "stim_pack", name: "Stim pack", kind: "consumable", baseValue: 250, description: "+15 life, -8 stress." },
  { id: "crowbar_pro", name: "Titanium pry bar", kind: "tool", baseValue: 750, toolMod: 6, description: "Crowbar’s meaner cousin." },
  { id: "silencer_rag", name: "Suppressor wrap", kind: "misc", baseValue: 1100, description: "Quieter close work. Not magic." },
  { id: "police_scanner", name: "Encrypted scanner", kind: "tool", baseValue: 1600, toolMod: 4, description: "Sweeps and codes before they hit your block." },
  { id: "bolt_cutters", name: "Bolt cutters", kind: "tool", baseValue: 220, toolMod: 3, description: "Chains, pads, and stubborn gates." },
  { id: "graffiti_kit", name: "Tag kit", kind: "misc", baseValue: 80, description: "Mark territory. Cheap respect." },
  { id: "energy_drink", name: "Wire cola", kind: "consumable", baseValue: 25, description: "+10 happy, slight buzz." },
];

/** Density pack merges EXTRA modules into live catalogs. */
export const ITEMS: ItemDef[] = [...ITEMS_CORE, ...ITEMS_EXTRA];

export const RANK_TITLES = [
  "Nobody",
  "Street Rookie",
  "Hustler",
  "Operator",
  "Fixer",
  "Shadow",
  "Alley King",
  "Night Broker",
  "District Ghost",
  "Kingpin",
  ...RANK_TITLES_EXTRA,
];

/** V0 NPC attack pool — district-scoped, not a coin-flip sandbox */
const NPCS_CORE: NpcDef[] = [
  {
    id: "gr_courier",
    name: "Glassrow Courier",
    title: "Soft target",
    district: "glassrow",
    power: 18,
    str: 4,
    def: 3,
    spd: 8,
    dex: 6,
    life: 40,
    lootMin: 120,
    lootMax: 280,
    heatOnWin: 4,
    heatOnLose: 2,
    energyCost: 8,
    flavor: "Late drop run. Bag looks heavy.",
  },
  {
    id: "gr_bouncer",
    name: "Neon Door Bouncer",
    title: "Muscle",
    district: "glassrow",
    power: 42,
    str: 14,
    def: 12,
    spd: 6,
    dex: 5,
    life: 70,
    lootMin: 200,
    lootMax: 450,
    heatOnWin: 8,
    heatOnLose: 4,
    energyCost: 12,
    flavor: "Cuts the line with a look. Cuts you if you miss.",
  },
  {
    id: "gr_tourist",
    name: "Festival Tourist",
    title: "Easy mark",
    district: "glassrow",
    power: 12,
    str: 3,
    def: 2,
    spd: 5,
    dex: 4,
    life: 30,
    lootMin: 80,
    lootMax: 200,
    heatOnWin: 3,
    heatOnLose: 1,
    energyCost: 6,
    flavor: "Camera out. Wallet out. Awareness out.",
  },
  {
    id: "ms_loader",
    name: "Yard Loader",
    title: "Shift muscle",
    district: "millstone",
    power: 28,
    str: 10,
    def: 8,
    spd: 5,
    dex: 5,
    life: 55,
    lootMin: 150,
    lootMax: 320,
    heatOnWin: 5,
    heatOnLose: 3,
    energyCost: 10,
    flavor: "Ends a shift with steel-toed boots and bad temper.",
  },
  {
    id: "ms_scout",
    name: "Roof Scout",
    title: "Fast",
    district: "millstone",
    power: 34,
    str: 6,
    def: 5,
    spd: 14,
    dex: 11,
    life: 45,
    lootMin: 180,
    lootMax: 400,
    heatOnWin: 6,
    heatOnLose: 3,
    energyCost: 10,
    flavor: "Watches alleys. Might be watching you.",
  },
  {
    id: "ms_foreman",
    name: "Night Foreman",
    title: "Hard",
    district: "millstone",
    power: 50,
    str: 16,
    def: 14,
    spd: 7,
    dex: 6,
    life: 80,
    lootMin: 280,
    lootMax: 600,
    heatOnWin: 10,
    heatOnLose: 5,
    energyCost: 14,
    flavor: "Clipboard and a tire iron. Equal opportunity.",
  },
  {
    id: "dr_smuggler",
    name: "Pier Smuggler",
    title: "Armed",
    district: "docksreach",
    power: 48,
    str: 12,
    def: 10,
    spd: 10,
    dex: 12,
    life: 65,
    lootMin: 350,
    lootMax: 750,
    heatOnWin: 12,
    heatOnLose: 6,
    energyCost: 14,
    flavor: "Crate manifests that don’t match the crates.",
  },
  {
    id: "dr_longshore",
    name: "Longshore Brute",
    title: "Tank",
    district: "docksreach",
    power: 55,
    str: 18,
    def: 16,
    spd: 5,
    dex: 4,
    life: 90,
    lootMin: 300,
    lootMax: 650,
    heatOnWin: 11,
    heatOnLose: 5,
    energyCost: 15,
    flavor: "Moves containers. Moves people who get in the way.",
  },
  {
    id: "dr_lookout",
    name: "Harbor Lookout",
    title: "Skittish",
    district: "docksreach",
    power: 22,
    str: 5,
    def: 4,
    spd: 12,
    dex: 10,
    life: 35,
    lootMin: 200,
    lootMax: 420,
    heatOnWin: 7,
    heatOnLose: 4,
    energyCost: 9,
    flavor: "Whistle and a radio. Hit hard before the call goes out.",
  },
  {
    id: "ac_intern",
    name: "Clinic Intern",
    title: "Soft",
    district: "ashcourt",
    power: 16,
    str: 4,
    def: 3,
    spd: 7,
    dex: 6,
    life: 35,
    lootMin: 100,
    lootMax: 240,
    heatOnWin: 3,
    heatOnLose: 2,
    energyCost: 7,
    gender: "female",
    persona: "noir",
    flavor: "Badge on a lanyard. Mind on the next shift.",
  },
  {
    id: "ac_security",
    name: "Ward Security",
    title: "Guard",
    district: "ashcourt",
    power: 40,
    str: 12,
    def: 11,
    spd: 6,
    dex: 6,
    life: 70,
    lootMin: 220,
    lootMax: 480,
    heatOnWin: 8,
    heatOnLose: 4,
    energyCost: 12,
    flavor: "Radio clipped. Eyes on every badge that doesn't belong.",
  },
  {
    id: "sy_exec",
    name: "Tower Courier",
    title: "Rich bag",
    district: "spireyard",
    power: 20,
    str: 5,
    def: 4,
    spd: 9,
    dex: 8,
    life: 40,
    lootMin: 300,
    lootMax: 700,
    heatOnWin: 6,
    heatOnLose: 3,
    energyCost: 9,
    flavor: "Locked briefcase. Soft shoes. Wrong neighborhood tonight.",
  },
  {
    id: "sy_guard",
    name: "Lobby Guard",
    title: "Hard",
    district: "spireyard",
    power: 52,
    str: 15,
    def: 14,
    spd: 7,
    dex: 7,
    life: 85,
    lootMin: 350,
    lootMax: 800,
    heatOnWin: 11,
    heatOnLose: 5,
    energyCost: 14,
    flavor: "Earpiece and a stare that invoices you.",
  },
  {
    id: "oc_thug",
    name: "Commons Thug",
    title: "Street",
    district: "oldcommons",
    power: 30,
    str: 11,
    def: 8,
    spd: 8,
    dex: 7,
    life: 55,
    lootMin: 140,
    lootMax: 320,
    heatOnWin: 5,
    heatOnLose: 3,
    energyCost: 10,
    flavor: "Knows every stairwell. Collects rent that isn't rent.",
  },
  {
    id: "oc_runner",
    name: "Night Runner",
    title: "Fast",
    district: "oldcommons",
    power: 26,
    str: 6,
    def: 5,
    spd: 15,
    dex: 12,
    life: 40,
    lootMin: 160,
    lootMax: 360,
    heatOnWin: 5,
    heatOnLose: 3,
    energyCost: 9,
    flavor: "Bag in the hoodie. Already gone if you blink.",
  },
  {
    id: "np_dealer",
    name: "Pier Chip Dealer",
    title: "Neon",
    district: "neonpier",
    power: 28,
    str: 7,
    def: 6,
    spd: 12,
    dex: 11,
    life: 42,
    lootMin: 200,
    lootMax: 420,
    heatOnWin: 6,
    heatOnLose: 3,
    energyCost: 9,
    gender: "female",
    persona: "slutty",
    flavor: "Warm plastic and colder eyes. Tourists tip; locals don't.",
    flavorSlutty:
      "Warm plastic, warmer smile. She deals chips like invitations — tourists tip; locals linger.",
  },
  {
    id: "np_bouncer",
    name: "Boardwalk Bouncer",
    title: "Velvet rope",
    district: "neonpier",
    power: 34,
    str: 12,
    def: 10,
    spd: 8,
    dex: 7,
    life: 55,
    lootMin: 180,
    lootMax: 380,
    heatOnWin: 5,
    heatOnLose: 4,
    energyCost: 10,
    flavor: "Keeps the pier quiet after midnight. Your face is on the list.",
  },
  {
    id: "rc_orderly",
    name: "Ward Orderly",
    title: "Clipboard",
    district: "redclinic",
    power: 24,
    str: 6,
    def: 8,
    spd: 9,
    dex: 10,
    life: 44,
    lootMin: 140,
    lootMax: 300,
    heatOnWin: 4,
    heatOnLose: 3,
    energyCost: 8,
    flavor: "Knows every door code. Pretends not to.",
  },
  {
    id: "rc_security",
    name: "Clinic Security",
    title: "Badge",
    district: "redclinic",
    power: 36,
    str: 11,
    def: 12,
    spd: 7,
    dex: 8,
    life: 58,
    lootMin: 220,
    lootMax: 450,
    heatOnWin: 6,
    heatOnLose: 4,
    energyCost: 11,
    flavor: "Sirens close. Armor under the white coat.",
  },
  // AAA expansion — denser attack pools per district
  {
    id: "gr_dealer",
    name: "Glassrow Chip Runner",
    title: "Neon",
    district: "glassrow",
    power: 26,
    str: 7,
    def: 6,
    spd: 11,
    dex: 10,
    life: 42,
    lootMin: 160,
    lootMax: 340,
    heatOnWin: 5,
    heatOnLose: 3,
    energyCost: 9,
    flavor: "Warm plastic in a cold jacket. Moves between tables.",
  },
  {
    id: "gr_pit",
    name: "Pit Runner",
    title: "Fast money",
    district: "glassrow",
    power: 38,
    str: 10,
    def: 9,
    spd: 12,
    dex: 11,
    life: 58,
    lootMin: 280,
    lootMax: 560,
    heatOnWin: 8,
    heatOnLose: 4,
    energyCost: 11,
    flavor: "Chips in the socks. Eyes on every camera.",
  },
  {
    id: "ms_welder",
    name: "Night Welder",
    title: "Sparks",
    district: "millstone",
    power: 36,
    str: 13,
    def: 11,
    spd: 6,
    dex: 8,
    life: 62,
    lootMin: 200,
    lootMax: 440,
    heatOnWin: 7,
    heatOnLose: 4,
    energyCost: 11,
    gender: "male",
    persona: "noir",
    flavor: "Torch and temper. Yard dogs know his boots.",
  },
  {
    id: "ms_parts",
    name: "Parts Runner",
    title: "Chop",
    district: "millstone",
    power: 24,
    str: 8,
    def: 6,
    spd: 13,
    dex: 10,
    life: 40,
    lootMin: 150,
    lootMax: 330,
    heatOnWin: 5,
    heatOnLose: 3,
    energyCost: 9,
    flavor: "Catalytics in a duffel. Already late for a buyer.",
  },
  {
    id: "dr_customs",
    name: "Corrupt Customs Clerk",
    title: "Stamp",
    district: "docksreach",
    power: 30,
    str: 6,
    def: 8,
    spd: 8,
    dex: 12,
    life: 48,
    lootMin: 320,
    lootMax: 680,
    heatOnWin: 9,
    heatOnLose: 5,
    energyCost: 10,
    flavor: "Manifests that lie for a fee. Wallet thick with bribes.",
  },
  {
    id: "dr_crane",
    name: "Crane Cab Tough",
    title: "Height",
    district: "docksreach",
    power: 46,
    str: 15,
    def: 13,
    spd: 7,
    dex: 7,
    life: 78,
    lootMin: 280,
    lootMax: 620,
    heatOnWin: 10,
    heatOnLose: 5,
    energyCost: 13,
    flavor: "Works the sky. Hits like a dropped container.",
  },
  {
    id: "ac_clerk",
    name: "Bond Office Clerk",
    title: "Paper",
    district: "ashcourt",
    power: 18,
    str: 4,
    def: 5,
    spd: 7,
    dex: 9,
    life: 36,
    lootMin: 180,
    lootMax: 400,
    heatOnWin: 4,
    heatOnLose: 2,
    energyCost: 8,
    flavor: "Rubber stamps and soft hands. Bag has clean cash.",
  },
  {
    id: "ac_detective",
    name: "Tired Detective",
    title: "Badge",
    district: "ashcourt",
    power: 48,
    str: 12,
    def: 13,
    spd: 9,
    dex: 10,
    life: 75,
    lootMin: 300,
    lootMax: 650,
    heatOnWin: 14,
    heatOnLose: 7,
    energyCost: 14,
    flavor: "Off-duty. Still armed. Still curious.",
  },
  {
    id: "sy_analyst",
    name: "Tower Analyst",
    title: "Soft target",
    district: "spireyard",
    power: 22,
    str: 4,
    def: 4,
    spd: 8,
    dex: 11,
    life: 38,
    lootMin: 350,
    lootMax: 750,
    heatOnWin: 6,
    heatOnLose: 3,
    energyCost: 9,
    gender: "female",
    persona: "noir",
    flavor: "Laptop bag and lobby badge. Wrong elevator tonight.",
  },
  {
    id: "sy_contractor",
    name: "Private Contractor",
    title: "Hard",
    district: "spireyard",
    power: 58,
    str: 16,
    def: 15,
    spd: 10,
    dex: 9,
    life: 92,
    lootMin: 400,
    lootMax: 900,
    heatOnWin: 12,
    heatOnLose: 6,
    energyCost: 15,
    flavor: "Earpiece, dark suit, no name tag. Expensive problem.",
  },
  {
    id: "oc_fence",
    name: "Commons Fence",
    title: "Buyer",
    district: "oldcommons",
    power: 28,
    str: 8,
    def: 7,
    spd: 9,
    dex: 10,
    life: 50,
    lootMin: 220,
    lootMax: 480,
    heatOnWin: 6,
    heatOnLose: 3,
    energyCost: 10,
    flavor: "Buys quiet. Sometimes collects loud.",
  },
  {
    id: "oc_enforcer",
    name: "Stairwell Enforcer",
    title: "Rent",
    district: "oldcommons",
    power: 44,
    str: 15,
    def: 12,
    spd: 7,
    dex: 6,
    life: 72,
    lootMin: 200,
    lootMax: 450,
    heatOnWin: 8,
    heatOnLose: 4,
    energyCost: 12,
    flavor: "Collects what isn’t rent. Knuckles first.",
  },
  {
    id: "np_hustler",
    name: "Boardwalk Hustler",
    title: "Shell game",
    district: "neonpier",
    power: 20,
    str: 5,
    def: 4,
    spd: 14,
    dex: 13,
    life: 36,
    lootMin: 140,
    lootMax: 320,
    heatOnWin: 4,
    heatOnLose: 2,
    energyCost: 8,
    gender: "female",
    persona: "slutty",
    flavor: "Three cups, one wallet. Already counting yours.",
    flavorSlutty:
      "Three cups, one wink. She counts your wallet like she’s already spent it with you.",
  },
  {
    id: "np_promoter",
    name: "Club Promoter",
    title: "Velvet",
    district: "neonpier",
    power: 32,
    str: 9,
    def: 8,
    spd: 11,
    dex: 10,
    life: 52,
    lootMin: 240,
    lootMax: 500,
    heatOnWin: 6,
    heatOnLose: 3,
    energyCost: 10,
    gender: "male",
    persona: "noir",
    flavor: "Guest list and a knife. Smiles until he doesn’t.",
  },
  {
    id: "rc_pharmacist",
    name: "Night Pharmacist",
    title: "Keys",
    district: "redclinic",
    power: 26,
    str: 5,
    def: 7,
    spd: 8,
    dex: 11,
    life: 46,
    lootMin: 200,
    lootMax: 420,
    heatOnWin: 5,
    heatOnLose: 3,
    energyCost: 9,
    flavor: "Cage keys on a lanyard. Exhausted and armed with knowledge.",
  },
  {
    id: "rc_paramedic",
    name: "Rogue Paramedic",
    title: "Siren",
    district: "redclinic",
    power: 40,
    str: 11,
    def: 10,
    spd: 12,
    dex: 9,
    life: 64,
    lootMin: 260,
    lootMax: 540,
    heatOnWin: 8,
    heatOnLose: 4,
    energyCost: 12,
    flavor: "Ambulance kit that isn’t for patients tonight.",
  },
];

export const NPCS: NpcDef[] = [...NPCS_CORE, ...NPCS_EXTRA];

export { HEADLINES } from "@/content/lore";

/** V0 properties — buy in-district only; rent − upkeep on tick */
const PROPERTIES_CORE: PropertyDef[] = [
  {
    id: "gr_walkup",
    name: "Glassrow Walk-up",
    district: "glassrow",
    cost: 6000,
    weeklyIncome: 90,
    weeklyUpkeep: 40,
    blurb: "Third floor, thin walls, good sightlines on the tram.",
    raidRisk: 0.8,
  },
  {
    id: "gr_loft",
    name: "Neon Loft Share",
    district: "glassrow",
    cost: 14000,
    weeklyIncome: 220,
    weeklyUpkeep: 95,
    blurb: "Clean address. Mail that looks legitimate.",
    raidRisk: 0.6,
  },
  {
    id: "ms_flat",
    name: "Millstone Flat",
    district: "millstone",
    cost: 4500,
    weeklyIncome: 75,
    weeklyUpkeep: 35,
    blurb: "Cheap keys. Yard dogs know your scent.",
    raidRisk: 1,
  },
  {
    id: "ms_row",
    name: "Brick Rowhouse",
    district: "millstone",
    cost: 11000,
    weeklyIncome: 175,
    weeklyUpkeep: 70,
    blurb: "Basement storage. Tenants who don’t ask.",
    raidRisk: 0.9,
  },
  {
    id: "ms_shed",
    name: "Yard Shed Unit",
    district: "millstone",
    cost: 8000,
    weeklyIncome: 130,
    weeklyUpkeep: 55,
    blurb: "Corrugated roof, padlock theater, real lock elsewhere.",
    raidRisk: 1.1,
  },
  {
    id: "dr_cot",
    name: "Pier Cot",
    district: "docksreach",
    cost: 5000,
    weeklyIncome: 100,
    weeklyUpkeep: 55,
    blurb: "Salt air and night radios. Heat sticks here.",
    raidRisk: 1.3,
  },
  {
    id: "dr_bay",
    name: "Side Bay Lease",
    district: "docksreach",
    cost: 16000,
    weeklyIncome: 260,
    weeklyUpkeep: 110,
    blurb: "Half a bay for crates that never appear on manifests.",
    raidRisk: 1.2,
  },
  {
    id: "dr_safe",
    name: "Harbor Soft-House",
    district: "docksreach",
    cost: 22000,
    weeklyIncome: 200,
    weeklyUpkeep: 120,
    blurb: "Quiet front. Better when the sweep rolls past.",
    raidRisk: 0.7,
  },
  {
    id: "ac_studio",
    name: "Ashcourt Studio",
    district: "ashcourt",
    cost: 7000,
    weeklyIncome: 110,
    weeklyUpkeep: 50,
    blurb: "Near the clinic. Mail that looks civic.",
    raidRisk: 0.75,
  },
  {
    id: "ac_wardflat",
    name: "Ward-Adjacent Flat",
    district: "ashcourt",
    cost: 15000,
    weeklyIncome: 230,
    weeklyUpkeep: 100,
    blurb: "Quiet nights. Badge readers blink friendly.",
    raidRisk: 0.65,
  },
  {
    id: "sy_condo",
    name: "SpireYard Condo Share",
    district: "spireyard",
    cost: 28000,
    weeklyIncome: 340,
    weeklyUpkeep: 160,
    blurb: "Glass lobby. Interest likes this zip code.",
    raidRisk: 0.5,
  },
  {
    id: "sy_pent",
    name: "Lower Pent Lease",
    district: "spireyard",
    cost: 45000,
    weeklyIncome: 480,
    weeklyUpkeep: 220,
    blurb: "Not the top floor. Still too expensive to raid casually.",
    raidRisk: 0.4,
  },
  {
    id: "oc_room",
    name: "Commons Room",
    district: "oldcommons",
    cost: 3500,
    weeklyIncome: 60,
    weeklyUpkeep: 25,
    blurb: "Thin door, thick neighbors. Cheap start.",
    raidRisk: 1.2,
  },
  {
    id: "oc_walkup",
    name: "Commons Walk-up",
    district: "oldcommons",
    cost: 9000,
    weeklyIncome: 140,
    weeklyUpkeep: 55,
    blurb: "Four flights. Tenants who tip in street cash.",
    raidRisk: 1.05,
  },
  {
    id: "np_booth",
    name: "Boardwalk Booth",
    district: "neonpier",
    cost: 8000,
    weeklyIncome: 130,
    weeklyUpkeep: 70,
    blurb: "Neon lease, tourist hours. Heat rides the boardwalk.",
    raidRisk: 1.15,
  },
  {
    id: "np_loft",
    name: "Pier Neon Loft",
    district: "neonpier",
    cost: 18000,
    weeklyIncome: 240,
    weeklyUpkeep: 100,
    blurb: "Glass over water. Clean money likes the view.",
    raidRisk: 0.9,
  },
  {
    id: "rc_bunk",
    name: "Ward Bunk Room",
    district: "redclinic",
    cost: 6500,
    weeklyIncome: 100,
    weeklyUpkeep: 55,
    blurb: "Staff housing adjacent. Sirens are the soundtrack.",
    raidRisk: 0.85,
  },
  {
    id: "rc_suite",
    name: "Clinic Admin Suite",
    district: "redclinic",
    cost: 20000,
    weeklyIncome: 280,
    weeklyUpkeep: 120,
    blurb: "Badge doors and quiet books. Civic cover when heat climbs.",
    raidRisk: 0.7,
  },
];

export const PROPERTIES: PropertyDef[] = [...PROPERTIES_CORE, ...PROPERTIES_EXTRA];

/** Original Nightwire awards — not Torn titles */
const AWARDS_CORE: AwardDef[] = [
  { id: "neon_scratch", name: "Neon Scratch", blurb: "First clean lift under the wires.", category: "crime" },
  { id: "first_fail", name: "Burn Mark", blurb: "Empty hands. Still breathing.", category: "crime" },
  { id: "corner_habit", name: "Corner Habit", blurb: "Petty work until it feels like muscle memory.", category: "crime" },
  { id: "alley_ledger", name: "Alley Ledger", blurb: "Street scores logged in sweat.", category: "crime" },
  { id: "heavy_breath", name: "Heavy Breath", blurb: "A heavy score that actually paid.", category: "crime" },
  { id: "punch_card", name: "Punch Card", blurb: "First legal shift on the books.", category: "work" },
  { id: "side_hustle", name: "Side Hustle", blurb: "First short contract. Clean cash without a boss.", category: "work" },
  { id: "gig_circuit", name: "Gig Circuit", blurb: "Eight contracts. The city knows your rate.", category: "work" },
  { id: "steady_hands", name: "Steady Hands", blurb: "Ten shifts. Still showing up.", category: "work" },
  { id: "name_on_roster", name: "Name on the Roster", blurb: "Someone wrote a promotion next to yours.", category: "work" },
  { id: "campus_ghost", name: "Campus Ghost", blurb: "Finished a course without vanishing.", category: "work" },
  { id: "ledger_clean", name: "Ledger Clean", blurb: "Bookkeeping cert. Interest likes you now.", category: "work" },
  { id: "dock_cert", name: "Dock Cert", blurb: "Harbor paper that opens heavier doors.", category: "work" },
  { id: "med_wing", name: "Med Wing", blurb: "First Aid stamped. Ward clocks notice.", category: "work" },
  { id: "pins_licensed", name: "Pins Licensed", blurb: "Locksmith paper. Doors answer cleaner.", category: "work" },
  { id: "keys_on_hook", name: "Keys on the Hook", blurb: "First property. Rent starts whispering.", category: "money" },
  { id: "rent_collector", name: "Rent Collector", blurb: "Two roofs. One ledger.", category: "money" },
  { id: "night_deposit", name: "Night Deposit", blurb: "Clean cash under glass.", category: "money" },
  { id: "nest_under_glass", name: "Nest Under Glass", blurb: "Five grand sleeping at the bank.", category: "money" },
  { id: "interest_drip", name: "Interest Drip", blurb: "The bank paid you for waiting.", category: "money" },
  { id: "ten_grand_glow", name: "Ten-Grand Glow", blurb: "Networth hits five figures.", category: "money" },
  { id: "iron_hours", name: "Iron Hours", blurb: "Ten gym sessions. Soft caps notice.", category: "body" },
  { id: "alley_mark", name: "Alley Mark", blurb: "Won a street fight that wasn’t a coin flip.", category: "body" },
  { id: "holding_cell_grad", name: "Holding Cell Grad", blurb: "Jailed once. Story material.", category: "body" },
  { id: "three_rails", name: "Three Rails", blurb: "Walked three districts on the wire.", category: "city" },
  { id: "six_rails", name: "Eight Rails", blurb: "Neon Pier to Red Clinic — every district underfoot.", category: "city" },
  { id: "wire_climber", name: "Wire Climber", blurb: "Level 5 on the Nightwire climb.", category: "city" },
  { id: "too_loud", name: "Too Loud", blurb: "Heat past 80. The city heard you.", category: "city" },
  { id: "vex_noticed", name: "Vex Noticed", blurb: "Rival ink in the paper. You’re on their board.", category: "story" },
  { id: "first_favor", name: "First Favor", blurb: "Someone on the wire answered when you asked.", category: "story" },
  { id: "tip_bought", name: "Warm Tip", blurb: "Paid for intel that still smelled like the street.", category: "story" },
  { id: "wide_rolodex", name: "Wide Rolodex", blurb: "Six different voices answered. The city got smaller.", category: "story" },
  { id: "first_board", name: "First Board", blurb: "Finished an organized prep and walked out with the take.", category: "crime" },
  { id: "board_collector", name: "Board Collector", blurb: "Three organized ops in the bag.", category: "crime" },
  // AAA expansion
  { id: "petty_fifty", name: "Fifty Petty", blurb: "Fifty petty attempts. Muscle memory paid rent.", category: "crime" },
  { id: "street_twenty", name: "Twenty Street", blurb: "Twenty street scores logged.", category: "crime" },
  { id: "heavy_five", name: "Five Heavies", blurb: "Five heavy takes that cleared.", category: "crime" },
  { id: "crime_century", name: "Century Wire", blurb: "One hundred crime attempts under the wires.", category: "crime" },
  { id: "board_five", name: "Five Boards", blurb: "Five organized ops complete.", category: "crime" },
  { id: "shift_fifty", name: "Fifty Shifts", blurb: "Fifty legal shifts. Still punching in.", category: "work" },
  { id: "gig_twenty", name: "Twenty Gigs", blurb: "Twenty short contracts done.", category: "work" },
  { id: "promote_three", name: "Triple Promote", blurb: "Three promotions. Name climbs the roster.", category: "work" },
  { id: "campus_five", name: "Five Transcripts", blurb: "Five courses finished.", category: "work" },
  { id: "systems_cert", name: "Signal Certified", blurb: "Radio Discipline stamped.", category: "work" },
  { id: "fence_grad", name: "Fence Graduate", blurb: "Fence Networks finished.", category: "work" },
  { id: "property_four", name: "Four Roofs", blurb: "Four properties on the ledger.", category: "money" },
  { id: "bank_25k", name: "Glass Nest 25k", blurb: "Twenty-five grand under glass.", category: "money" },
  { id: "networth_50k", name: "Fifty-Grand Glow", blurb: "Networth hits fifty thousand.", category: "money" },
  { id: "interest_500", name: "Interest River", blurb: "Five hundred in bank interest earned.", category: "money" },
  { id: "gym_fifty", name: "Fifty Iron", blurb: "Fifty gym sessions.", category: "body" },
  { id: "attack_ten", name: "Ten Marks", blurb: "Ten NPC fights won.", category: "body" },
  { id: "hospital_grad", name: "Ward Stay", blurb: "Hospitalized once. Story material.", category: "body" },
  { id: "level_ten", name: "Wire Ten", blurb: "Level 10 on the climb.", category: "city" },
  { id: "heat_100", name: "City Siren", blurb: "Heat past 100. Sirens know your name.", category: "city" },
  { id: "contact_twelve", name: "Full Rolodex", blurb: "Used twelve different contacts.", category: "story" },
  { id: "favor_ten", name: "Ten Favors", blurb: "Ten contact uses on the wire.", category: "story" },
  { id: "tip_five", name: "Five Warm Tips", blurb: "Bought five tips that still smelled like street.", category: "story" },
];

export const AWARDS: AwardDef[] = [...AWARDS_CORE, ...AWARDS_EXTRA];

/** V2 contacts — 12 people; unlock by district/job/edu; tips/favors matter */
export const CONTACTS: ContactDef[] = [
  {
    id: "reed",
    name: "Reed",
    role: "Mentor",
    homeDistrict: "glassrow",
    gender: "male",
    persona: "noir",
    blurb: "Older voice on a cheap line. Keeps you from burning out early.",
    unlockHint: "Always available",
    actions: [
      {
        id: "ping",
        label: "Check in",
        blurb: "+happy, −stress. Soft pep talk.",
      },
      {
        id: "ask_favor",
        label: "Ask favor",
        blurb: "Spend favor for a small XP nudge.",
        favorCost: 2,
      },
    ],
  },
  {
    id: "mara",
    name: "Mara Vale",
    role: "Counsel",
    homeDistrict: "glassrow",
    gender: "female",
    persona: "noir",
    blurb: "Clean suit, dirty Rolodex. Investigation is her language.",
    unlockHint: "Jail once, investigation open, or level 2+",
    actions: [
      {
        id: "retain",
        label: "Retain hour",
        blurb: "Cheaper lawyer: drop investigation one stage ($1200 clean).",
        cleanCost: 1200,
      },
      {
        id: "cool_case",
        label: "Cool the case",
        blurb: "Spend favor + $800 clean to drop two stages.",
        favorCost: 2,
        cleanCost: 800,
      },
    ],
  },
  {
    id: "kilo",
    name: "Kilo",
    role: "Pier tipster",
    homeDistrict: "docksreach",
    gender: "male",
    persona: "noir",
    blurb: "Whistles when containers move. Harbor windows are his product.",
    unlockHint: "Visit DocksReach",
    actions: [
      {
        id: "tip",
        label: "Buy pier tip",
        blurb: "+heavy odds for 4h (harbor window). Costs street cash.",
        streetCost: 350,
      },
      {
        id: "ping",
        label: "Radio check",
        blurb: "Soft heat bleed if you’re near the water.",
      },
    ],
  },
  {
    id: "ivy",
    name: "Ivy Chen",
    role: "Campus voice",
    homeDistrict: "millstone",
    gender: "female",
    persona: "noir",
    blurb: "Advisor who notices when your schedule and your heat don’t match.",
    unlockHint: "Enroll or finish a course",
    actions: [
      {
        id: "office_hours",
        label: "Office hours",
        blurb: "−stress, +happy. Study nerves settle.",
      },
      {
        id: "ping",
        label: "Heat warning",
        blurb: "If heat is high, she talks you down (−heat soft).",
      },
    ],
  },
  {
    id: "nix",
    name: "Nix",
    role: "Alley broker",
    homeDistrict: "millstone",
    gender: "female",
    persona: "slutty",
    blurb: "Sells timing, not tools. Tips expire when the street forgets.",
    blurbSlutty:
      "Sells timing with a smile that lingers. Tips warm; so does the hush after.",
    unlockHint: "5+ crime attempts",
    actions: [
      {
        id: "tip",
        label: "Street tip",
        blurb: "+street-family odds for 3h. Street cash.",
        streetCost: 250,
      },
      {
        id: "ask_favor",
        label: "Call marker",
        blurb: "Spend favor: petty odds bump for 2h.",
        favorCost: 1,
      },
    ],
  },
  {
    id: "soot",
    name: "Soot",
    role: "Iron contact",
    homeDistrict: "millstone",
    gender: "male",
    persona: "noir",
    blurb: "Spotter who knows when your form is lying about your head.",
    unlockHint: "3+ gym sessions",
    actions: [
      {
        id: "walk_off",
        label: "Walk it off",
        blurb: "−stress, +happy. Body reset.",
      },
      {
        id: "ping",
        label: "Spot me",
        blurb: "Tiny favor gain if you’re not fried.",
      },
    ],
  },
  {
    id: "wren",
    name: "Wren",
    role: "Commons fence",
    homeDistrict: "oldcommons",
    gender: "female",
    persona: "noir",
    blurb: "Buys what the street won’t claim. Pays ugly, pays fast.",
    unlockHint: "Visit OldCommons",
    actions: [
      {
        id: "tip",
        label: "Buy window tip",
        blurb: "+petty odds for 3h. Street cash.",
        streetCost: 200,
      },
      {
        id: "ask_favor",
        label: "Fence skim",
        blurb: "Spend favor: turn $400 street into ~$260 clean.",
        favorCost: 2,
        streetCost: 400,
      },
    ],
  },
  {
    id: "calder",
    name: "Calder",
    role: "Ward whisper",
    homeDistrict: "ashcourt",
    gender: "male",
    persona: "noir",
    blurb: "Orderly who never writes what he can forget. Clinic doors open sideways.",
    unlockHint: "Visit Ashcourt",
    actions: [
      {
        id: "walk_off",
        label: "Quiet discharge",
        blurb: "In ward: cut remaining hospital time in half ($500 clean). Else: life/wounds soft.",
        cleanCost: 500,
      },
      {
        id: "ping",
        label: "Hall check",
        blurb: "−stress, soft life if you’re upright.",
      },
    ],
  },
  {
    id: "quill",
    name: "Quill",
    role: "Spire clerk",
    homeDistrict: "spireyard",
    gender: "male",
    persona: "noir",
    blurb: "Stamps forms like they owe him. Legitimacy is a filing cabinet.",
    unlockHint: "Visit SpireYard or bank once",
    actions: [
      {
        id: "ping",
        label: "File a note",
        blurb: "+legitimacy soft. Paper trail that helps.",
      },
      {
        id: "ask_favor",
        label: "Rush stamp",
        blurb: "Spend favor: small clean stipend + legitimacy.",
        favorCost: 2,
      },
    ],
  },
  {
    id: "joss",
    name: "Joss",
    role: "Shift fixer",
    homeDistrict: "glassrow",
    gender: "female",
    persona: "noir",
    blurb: "Knows which managers need a body and which need a story.",
    unlockHint: "Work 5 job shifts",
    actions: [
      {
        id: "ask_favor",
        label: "Odd job",
        blurb: "Spend favor: quick clean cash off the books.",
        favorCost: 1,
      },
      {
        id: "ping",
        label: "Swap shifts",
        blurb: "+energy if you’ve got room. Soft favor.",
      },
    ],
  },
  {
    id: "haze",
    name: "Haze",
    role: "Heat broker",
    homeDistrict: "docksreach",
    gender: "male",
    persona: "noir",
    blurb: "Sells cool air and bad alibis. Smoke follows the money.",
    unlockHint: "Peak heat 40+",
    actions: [
      {
        id: "tip",
        label: "Buy cool",
        blurb: "−15 heat. Street cash for silence.",
        streetCost: 450,
      },
      {
        id: "ping",
        label: "Smoke check",
        blurb: "Soft −heat near the pier; else nerves only.",
      },
    ],
  },
  {
    id: "pike",
    name: "Pike",
    role: "Bail runner",
    homeDistrict: "oldcommons",
    gender: "male",
    persona: "noir",
    blurb: "Shows up with a clipboard and a clock. Time is his inventory.",
    unlockHint: "Jail once",
    actions: [
      {
        id: "retain",
        label: "Cut time",
        blurb: "While jailed: halve remaining lockup ($700 clean).",
        cleanCost: 700,
      },
      {
        id: "ping",
        label: "Walk free talk",
        blurb: "Outside: −stress, soft heat bleed. Favor if clean.",
      },
    ],
  },
];

export function getCrime(id: string) {
  return CRIMES.find((c) => c.id === id);
}
export function getJob(id: string) {
  return JOBS.find((j) => j.id === id);
}
export function getGig(id: string) {
  return GIGS.find((g) => g.id === id);
}
export function getCourse(id: string) {
  return COURSES.find((c) => c.id === id);
}
export function getLicense(id: string) {
  return LICENSES.find((l) => l.id === id);
}
export function getItem(id: string) {
  return ITEMS.find((i) => i.id === id);
}
export function getDistrict(id: string) {
  return DISTRICTS.find((d) => d.id === id);
}
export function getNpc(id: string) {
  return NPCS.find((n) => n.id === id);
}
export function getProperty(id: string) {
  return PROPERTIES.find((p) => p.id === id);
}
export function getAward(id: string) {
  return AWARDS.find((a) => a.id === id);
}
export function getContact(id: string) {
  return CONTACTS.find((c) => c.id === id);
}
export function npcsInDistrict(district: string) {
  return NPCS.filter((n) => n.district === district);
}
export function propertiesInDistrict(district: string) {
  return PROPERTIES.filter((p) => p.district === district);
}
