import type {
  AwardDef,
  ContactDef,
  CourseDef,
  LicenseDef,
  GigDef,
  ItemDef,
  NpcDef,
  PropertyDef,
} from "@/game/types";

export { DISTRICTS } from "@/content/districts";
export { CRIMES } from "@/content/crimes";
export { JOBS } from "@/content/jobs";
export { HEISTS, getHeist } from "@/content/heists";
export {
  SAFEHOUSE_ROOMS,
  ARMORY_RECIPES,
  getSafehouseRoom,
} from "@/content/safehouse";

import { CRIMES } from "@/content/crimes";
import { DISTRICTS } from "@/content/districts";
import { JOBS } from "@/content/jobs";

export const GIGS: GigDef[] = [
  {
    id: "courier_drop",
    name: "Courier drop",
    blurb: "Bag A to B before the bag sweats. Clean cash, soft legs.",
    basePay: 280,
    energy: 3,
    districtBias: ["glassrow", "millstone"],
    legitimacyGain: 0.3,
    special: "Extra tip",
  },
  {
    id: "data_entry",
    name: "Data entry sprint",
    blurb: "Keys and coffee. No glory, honest hours.",
    basePay: 320,
    energy: 4,
    districtBias: ["glassrow"],
    legitimacyGain: 0.4,
    special: "Overtime stub",
  },
  {
    id: "night_watch",
    name: "Night watch",
    blurb: "Sit still, log shadows. Civic clients hate heat on your file.",
    basePay: 380,
    energy: 4,
    districtBias: ["millstone", "docksreach"],
    maxHeat: 45,
    legitimacyGain: 0.5,
    special: "Quiet bonus",
  },
  {
    id: "tutoring",
    name: "Tutoring hour",
    blurb: "Explain City Navigation to someone who still gets lost.",
    basePay: 340,
    energy: 3,
    districtBias: ["glassrow", "millstone"],
    requiresCourse: "se1",
    legitimacyGain: 0.6,
    special: "Grateful tip",
  },
  {
    id: "pier_walk",
    name: "Pier walk gig",
    blurb: "Escort tourists past the cranes. Stress bleeds into the water.",
    basePay: 220,
    energy: 3,
    districtBias: ["docksreach"],
    happyGain: 25,
    legitimacyGain: 0.2,
    special: "Calm stretch",
  },
  {
    id: "campus_filing",
    name: "Campus filing",
    blurb: "Work-study adjacent. Stacks of paper, stipend-adjacent pay.",
    basePay: 260,
    energy: 3,
    districtBias: ["millstone", "glassrow"],
    requiresStudy: true,
    legitimacyGain: 0.5,
    special: "Advisor nod",
  },
  {
    id: "freight_assist",
    name: "Freight assist",
    blurb: "Move crates without asking what’s inside. Dock hours.",
    basePay: 420,
    energy: 4,
    districtBias: ["docksreach"],
    requiresLevel: 2,
    legitimacyGain: 0.3,
    special: "Yard tip",
  },
  {
    id: "civic_clipboard",
    name: "Civic clipboard",
    blurb: "Survey forms for the city. Your heat must look boring.",
    basePay: 360,
    energy: 3,
    districtBias: ["glassrow"],
    maxHeat: 30,
    requiresLevel: 2,
    legitimacyGain: 0.8,
    special: "Civic stamp",
  },
  {
    id: "clinic_aide",
    name: "Clinic aide shift",
    blurb: "Ashcourt overflow desk. First-aid paper makes the clipboard legal.",
    basePay: 400,
    energy: 4,
    districtBias: ["ashcourt"],
    requiresCourse: "mc1",
    maxHeat: 40,
    legitimacyGain: 0.7,
    special: "Ward tip",
  },
  {
    id: "locksmith_call",
    name: "Legal locksmith call",
    blurb: "Locked out of a Glassrow walk-up. Cert in the bag, cash clean.",
    basePay: 480,
    energy: 4,
    districtBias: ["glassrow", "millstone"],
    requiresCourse: "le1",
    maxHeat: 35,
    legitimacyGain: 0.6,
    special: "Grateful tip",
  },
  {
    id: "bike_courier",
    name: "Bike courier sprint",
    blurb: "Pedals and rain. Glassrow lunch boxes that can't wait.",
    basePay: 250,
    energy: 3,
    districtBias: ["glassrow", "oldcommons"],
    legitimacyGain: 0.25,
    special: "Rush tip",
  },
  {
    id: "market_stall",
    name: "Market stall cover",
    blurb: "Watch tills while the owner grabs coffee. Soft eyes only.",
    basePay: 300,
    energy: 3,
    districtBias: ["oldcommons", "millstone"],
    maxHeat: 50,
    legitimacyGain: 0.35,
    special: "Till bonus",
  },
  {
    id: "trash_route",
    name: "Alley trash route",
    blurb: "Bags, bins, and early hours. Nobody asks for a résumé.",
    basePay: 240,
    energy: 4,
    districtBias: ["oldcommons", "millstone"],
    legitimacyGain: 0.2,
    special: "Found scrap",
  },
  {
    id: "neon_flyer",
    name: "Neon flyer stack",
    blurb: "Staple handbills under pier lights. Legs and wet ink.",
    basePay: 270,
    energy: 3,
    districtBias: ["neonpier", "glassrow"],
    happyGain: 10,
    legitimacyGain: 0.2,
    special: "Club tip",
  },
  {
    id: "ward_errands",
    name: "Ward errand run",
    blurb: "Forms between Red Clinic desks. Keep the clipboard dry.",
    basePay: 350,
    energy: 3,
    districtBias: ["redclinic", "ashcourt"],
    maxHeat: 40,
    requiresLevel: 2,
    legitimacyGain: 0.55,
    special: "Nurse tip",
  },
  {
    id: "spire_reception",
    name: "Spire desk cover",
    blurb: "Smile, badge, silence. Elite floors hate street noise.",
    basePay: 520,
    energy: 4,
    districtBias: ["spireyard"],
    maxHeat: 25,
    requiresLevel: 4,
    legitimacyGain: 0.9,
    special: "Envelope tip",
  },
  {
    id: "ledger_audit",
    name: "Ledger audit assist",
    blurb: "Tick boxes for a Commerce tutor. Numbers that stay clean.",
    basePay: 440,
    energy: 4,
    districtBias: ["glassrow", "spireyard"],
    requiresCourse: "cf1",
    legitimacyGain: 0.7,
    special: "Tutor bonus",
  },
  {
    id: "container_count",
    name: "Container count",
    blurb: "Bay numbers vs the sheet. Harbor cert helps the whistle.",
    basePay: 460,
    energy: 4,
    districtBias: ["docksreach"],
    requiresCourse: "hl1",
    requiresLevel: 2,
    legitimacyGain: 0.55,
    special: "Yard stamp",
  },
  {
    id: "lab_cleanup",
    name: "Lab cleanup shift",
    blurb: "Ashcourt glassware and gloves. Protocols before mop water.",
    basePay: 390,
    energy: 4,
    districtBias: ["ashcourt", "redclinic"],
    requiresCourse: "mc1",
    legitimacyGain: 0.6,
    special: "Lab tip",
  },
  {
    id: "parking_patrol",
    name: "Parking lot patrol",
    blurb: "Walk rows, note plates. Civic clients want a boring file.",
    basePay: 310,
    energy: 3,
    districtBias: ["millstone", "ashcourt"],
    maxHeat: 35,
    requiresLevel: 2,
    legitimacyGain: 0.5,
    special: "Quiet hour",
  },
  {
    id: "moving_crew",
    name: "Moving crew hour",
    blurb: "Sofas and stairs. Millstone flats that never fit elevators.",
    basePay: 360,
    energy: 5,
    districtBias: ["millstone", "oldcommons"],
    legitimacyGain: 0.3,
    special: "Cash tip",
  },
  {
    id: "food_runner",
    name: "Kitchen food runner",
    blurb: "Hot plates through a busy line. No heat on your apron.",
    basePay: 290,
    energy: 3,
    districtBias: ["glassrow", "neonpier"],
    maxHeat: 55,
    happyGain: 8,
    legitimacyGain: 0.25,
    special: "Kitchen tip",
  },
  {
    id: "library_shelve",
    name: "Library shelving",
    blurb: "Stacks and silence. Study track or finished credits only.",
    basePay: 255,
    energy: 3,
    districtBias: ["millstone", "ashcourt"],
    requiresStudy: true,
    legitimacyGain: 0.45,
    special: "Quiet bonus",
  },
  {
    id: "ferry_ticket",
    name: "Ferry ticket booth",
    blurb: "Stamps and smiles on the pier. Tourists tip if you're kind.",
    basePay: 330,
    energy: 3,
    districtBias: ["neonpier", "docksreach"],
    happyGain: 15,
    legitimacyGain: 0.35,
    special: "Tour tip",
  },
  {
    id: "event_setup",
    name: "Event chair setup",
    blurb: "Folding chairs before a Spire mixer. Clean hands preferred.",
    basePay: 410,
    energy: 4,
    districtBias: ["spireyard", "glassrow"],
    maxHeat: 40,
    requiresLevel: 3,
    legitimacyGain: 0.5,
    special: "Host tip",
  },
  {
    id: "blood_drive",
    name: "Blood drive clerk",
    blurb: "Clipboards and cotton. First aid paper makes it legal.",
    basePay: 370,
    energy: 3,
    districtBias: ["redclinic", "ashcourt"],
    requiresCourse: "mc1",
    maxHeat: 45,
    legitimacyGain: 0.65,
    special: "Clinic stamp",
  },
  {
    id: "yard_sweep",
    name: "Yard sweep contract",
    blurb: "Brooms and grit behind Millstone shops. Early shift, honest pay.",
    basePay: 275,
    energy: 4,
    districtBias: ["millstone"],
    legitimacyGain: 0.25,
    special: "Shop tip",
  },
  {
    id: "translate_desk",
    name: "Translate desk hour",
    blurb: "Forms for people who hate forms. Persuasion basics helps.",
    basePay: 380,
    energy: 3,
    districtBias: ["glassrow", "oldcommons"],
    requiresCourse: "se2",
    legitimacyGain: 0.55,
    special: "Grateful tip",
  },
  {
    id: "cold_storage",
    name: "Cold storage check",
    blurb: "Walk freezers, log temps. Harbor routing cert preferred.",
    basePay: 450,
    energy: 4,
    districtBias: ["docksreach", "neonpier"],
    requiresCourse: "hl2",
    requiresLevel: 4,
    legitimacyGain: 0.5,
    special: "Route tip",
  },
  {
    id: "shelter_shift",
    name: "Shelter night shift",
    blurb: "Cots and coffee in Old Commons. Heat must look boring.",
    basePay: 340,
    energy: 4,
    districtBias: ["oldcommons"],
    maxHeat: 30,
    requiresLevel: 2,
    legitimacyGain: 0.75,
    happyGain: 12,
    special: "Civic thanks",
  },
  {
    id: "press_run",
    name: "Press flyer run",
    blurb: "Bundle papers for the night edition. Legs before dawn.",
    basePay: 295,
    energy: 3,
    districtBias: ["glassrow", "ashcourt"],
    legitimacyGain: 0.3,
    special: "Editor tip",
  },
  {
    id: "tool_lend",
    name: "Tool library desk",
    blurb: "Check out drills without the drama. Locksmith paper helps.",
    basePay: 400,
    energy: 3,
    districtBias: ["millstone"],
    requiresCourse: "le1",
    maxHeat: 40,
    legitimacyGain: 0.55,
    special: "Member tip",
  },
  {
    id: "museum_rope",
    name: "Museum rope crew",
    blurb: "Velvet lines before opening. Soft shoes, softer heat.",
    basePay: 430,
    energy: 3,
    districtBias: ["glassrow", "spireyard"],
    requiresCourse: "se2",
    maxHeat: 35,
    requiresLevel: 3,
    legitimacyGain: 0.6,
    special: "Curator tip",
  },
  {
    id: "ambulance_stock",
    name: "Ambulance restock",
    blurb: "Kits and seals at Red Clinic bay. Protocols matter.",
    basePay: 470,
    energy: 4,
    districtBias: ["redclinic"],
    requiresCourse: "mc2",
    requiresLevel: 4,
    maxHeat: 40,
    legitimacyGain: 0.7,
    special: "Bay tip",
  },
  {
    id: "invoice_match",
    name: "Invoice match desk",
    blurb: "Shell-company homework for a clean client. Commerce track.",
    basePay: 500,
    energy: 4,
    districtBias: ["spireyard", "glassrow"],
    requiresCourse: "cf2",
    requiresLevel: 5,
    maxHeat: 30,
    legitimacyGain: 0.85,
    special: "Client bonus",
  },
];

export const COURSES: CourseDef[] = [
  {
    id: "se1",
    school: "Street Electives",
    name: "City Navigation",
    hours: 12,
    fee: 200,
    stipendPerHour: 20,
    blurb: "Maps, cameras, and soft exits. Gates street warehouse/pharmacy work.",
    unlocks: ["warehouse", "pharmacy", "dock_pierce", "chop_shop"],
    oddsBonus: 5,
    oddsFamilies: ["street"],
  },
  {
    id: "se2",
    school: "Street Electives",
    name: "Persuasion Basics",
    hours: 24,
    fee: 400,
    stipendPerHour: 30,
    blurb: "Talk soft, walk hard. Kitchen promotion exam + museum after-hours gate.",
    requiresCourse: "se1",
    gigPayBonus: 10,
    oddsBonus: 3,
    oddsFamilies: ["petty", "street"],
    unlocks: ["museum"],
  },
  {
    id: "se3",
    school: "Street Electives",
    name: "Fitness Study",
    hours: 18,
    fee: 300,
    stipendPerHour: 25,
    blurb: "Classroom bulk. Raises gym soft cap permanently.",
    requiresCourse: "se1",
    softCapBonus: 5,
  },
  {
    id: "se4",
    school: "Street Electives",
    name: "Alley Networks",
    hours: 30,
    fee: 650,
    stipendPerHour: 35,
    blurb: "Who nods, who rats. Gig rates climb; street odds get sharper.",
    requiresCourse: "se2",
    requiresLevel: 3,
    gigPayBonus: 8,
    oddsBonus: 4,
    oddsFamilies: ["street"],
    unlocks: ["arson_scout", "jewel_case"],
  },
  {
    id: "cf1",
    school: "Commerce & Finance",
    name: "Bookkeeping",
    hours: 24,
    fee: 500,
    stipendPerHour: 40,
    blurb: "Clean ledgers. Job pay up, bank interest up, retail promotion exam.",
    requiresLevel: 2,
    jobPayBonus: 5,
    bankInterestBonus: 0.5,
    unlocks: ["badge_clone", "aide_blackmail"],
  },
  {
    id: "cf2",
    school: "Commerce & Finance",
    name: "Business Basics",
    hours: 48,
    fee: 1000,
    stipendPerHour: 50,
    blurb: "Fronts and floats. Unlocks cage, vault, and fraud heavies.",
    requiresCourse: "cf1",
    unlocks: ["casino_cage", "courier", "evidence_room", "private_vault", "evidence_swap", "bond_fraud"],
    oddsBonus: 4,
    oddsFamilies: ["heavy"],
  },
  {
    id: "cf3",
    school: "Commerce & Finance",
    name: "Shell Companies",
    hours: 36,
    fee: 1400,
    stipendPerHour: 55,
    blurb: "Paper walls that hold. Bank rate climbs; heavy fraud runs quieter.",
    requiresCourse: "cf2",
    requiresLevel: 5,
    jobPayBonus: 6,
    bankInterestBonus: 0.75,
    oddsBonus: 3,
    oddsFamilies: ["heavy"],
  },
  {
    id: "hl1",
    school: "Harbor & Logistics",
    name: "Dock Safety",
    hours: 18,
    fee: 400,
    stipendPerHour: 35,
    blurb: "Cert for cranes and containers. Unlocks harbor heist; dock promotion exam.",
    requiresLevel: 2,
    unlocks: ["harbor", "dock_pierce", "airport_cargo", "train_arms"],
    jobPayBonus: 10,
    oddsBonus: 5,
    oddsFamilies: ["heavy"],
  },
  {
    id: "hl2",
    school: "Harbor & Logistics",
    name: "Container Routing",
    hours: 28,
    fee: 750,
    stipendPerHour: 45,
    blurb: "Bay numbers that don’t match the sheet. Heavy odds and dock pay.",
    requiresCourse: "hl1",
    requiresLevel: 4,
    jobPayBonus: 8,
    oddsBonus: 4,
    oddsFamilies: ["heavy"],
  },
  {
    id: "hl3",
    school: "Harbor & Logistics",
    name: "Yard Boss Theory",
    hours: 40,
    fee: 1200,
    stipendPerHour: 55,
    blurb: "Who owns the whistle. Dock ladder exam + cleaner heavy exits.",
    requiresCourse: "hl2",
    requiresLevel: 6,
    jobPayBonus: 10,
    oddsBonus: 3,
    oddsFamilies: ["heavy"],
  },
  {
    id: "mc1",
    school: "Med & Civic",
    name: "First Aid",
    hours: 16,
    fee: 350,
    stipendPerHour: 30,
    blurb: "Tourniquets and ward clocks. Cuts hospital stays; orderly exam path.",
    requiresLevel: 2,
    hospitalTimeReduction: 15,
    jobPayBonus: 4,
  },
  {
    id: "mc2",
    school: "Med & Civic",
    name: "Clinic Protocols",
    hours: 28,
    fee: 700,
    stipendPerHour: 40,
    blurb: "Badge paths through Ashcourt. Unlocks hospital pharmacy vault.",
    requiresCourse: "mc1",
    requiresLevel: 4,
    hospitalTimeReduction: 10,
    unlocks: ["hospital_vault"],
    oddsBonus: 4,
    oddsFamilies: ["street", "heavy"],
  },
  {
    id: "mc3",
    school: "Med & Civic",
    name: "Know Your Rights",
    hours: 24,
    fee: 600,
    stipendPerHour: 35,
    blurb: "Civic exits under pressure. Legitimacy face + soft street odds.",
    requiresCourse: "mc1",
    requiresLevel: 3,
    gigPayBonus: 6,
    oddsBonus: 3,
    oddsFamilies: ["street"],
    jobPayBonus: 3,
  },
  {
    id: "le1",
    school: "Locks & Entry",
    name: "Legal Locksmith",
    hours: 20,
    fee: 450,
    stipendPerHour: 32,
    blurb: "Pins and paperwork. Legal calls by day; sharper entry odds by night.",
    requiresLevel: 2,
    requiresCourse: "se1",
    oddsBonus: 4,
    oddsFamilies: ["petty", "street"],
    jobPayBonus: 3,
    unlocks: ["advanced_lock"],
  },
  {
    id: "le2",
    school: "Locks & Entry",
    name: "Safe Mechanics",
    hours: 36,
    fee: 900,
    stipendPerHour: 45,
    blurb: "Dial feel and drill patience. Hotel safes and vault work run cleaner.",
    requiresCourse: "le1",
    requiresLevel: 4,
    oddsBonus: 5,
    oddsFamilies: ["street", "heavy"],
    jobPayBonus: 4,
    unlocks: ["hotel_safe"],
  },
];

/** One license per campus course — granted on complete; stacks with transcript perks */
export const LICENSES: LicenseDef[] = [
  {
    id: "nav_permit",
    name: "Street Navigation Permit",
    courseId: "se1",
    blurb: "City maps stamped legal. Soft exits count as civic know-how.",
    oddsBonus: 2,
    oddsFamilies: ["street"],
    legitimacyGain: 3,
    weeklyStipend: 15,
  },
  {
    id: "persuasion_cert",
    name: "Civic Persuasion Cert",
    courseId: "se2",
    blurb: "Talk soft on paperwork. Opens cleaner freelance rates.",
    jobPayBonus: 2,
    legitimacyGain: 2,
    weeklyStipend: 20,
  },
  {
    id: "fitness_cert",
    name: "Campus Fitness Cert",
    courseId: "se3",
    blurb: "School gym card that still clears civic desk checks.",
    legitimacyGain: 1,
    weeklyStipend: 10,
  },
  {
    id: "alley_network_pass",
    name: "Alley Network Pass",
    courseId: "se4",
    blurb: "Introductions that stick. Freelance rates notice.",
    jobPayBonus: 2,
    oddsBonus: 2,
    oddsFamilies: ["street"],
    legitimacyGain: 2,
    weeklyStipend: 25,
  },
  {
    id: "commerce_cert",
    name: "Commerce Cert",
    courseId: "cf1",
    blurb: "Bookkeeping seal. Banks and landlords trust the ink.",
    jobPayBonus: 3,
    bankInterestBonus: 0.5,
    legitimacyGain: 4,
    weeklyStipend: 40,
  },
  {
    id: "business_license",
    name: "Business Operator License",
    courseId: "cf2",
    blurb: "Fronts and floats on the clean ledger. Pay scales up.",
    jobPayBonus: 5,
    bankInterestBonus: 0.25,
    legitimacyGain: 5,
    weeklyStipend: 60,
  },
  {
    id: "shell_operator",
    name: "Shell Operator Seal",
    courseId: "cf3",
    blurb: "Paper walls the city still stamps. Interest likes the structure.",
    jobPayBonus: 4,
    bankInterestBonus: 0.5,
    legitimacyGain: 5,
    weeklyStipend: 70,
  },
  {
    id: "harbor_safety",
    name: "Harbor Safety Cert",
    courseId: "hl1",
    blurb: "Crane and container clearance. Docks pay better; heavy work runs cleaner.",
    jobPayBonus: 4,
    oddsBonus: 3,
    oddsFamilies: ["heavy"],
    legitimacyGain: 3,
    weeklyStipend: 35,
  },
  {
    id: "container_routing",
    name: "Container Routing Cert",
    courseId: "hl2",
    blurb: "Bay grammar on a badge. Yard pay and heavy edges.",
    jobPayBonus: 5,
    oddsBonus: 2,
    oddsFamilies: ["heavy"],
    legitimacyGain: 3,
    weeklyStipend: 45,
  },
  {
    id: "yard_boss",
    name: "Yard Boss Endorsement",
    courseId: "hl3",
    blurb: "Whistle authority. Dock ladder respects the seal.",
    jobPayBonus: 6,
    oddsBonus: 2,
    oddsFamilies: ["heavy"],
    legitimacyGain: 4,
    weeklyStipend: 55,
  },
  {
    id: "med_aide",
    name: "Med Aide Cert",
    courseId: "mc1",
    blurb: "Clinic stamp. Ward clocks run shorter; orderly floors trust you.",
    hospitalTimeReduction: 10,
    jobPayBonus: 3,
    legitimacyGain: 4,
    weeklyStipend: 30,
  },
  {
    id: "clinic_protocols",
    name: "Clinic Protocols Seal",
    courseId: "mc2",
    blurb: "Ashcourt badge paths. Pharmacy doors and quieter heavy work.",
    hospitalTimeReduction: 5,
    oddsBonus: 2,
    oddsFamilies: ["street", "heavy"],
    legitimacyGain: 3,
    weeklyStipend: 40,
  },
  {
    id: "civic_rights",
    name: "Civic Rights Card",
    courseId: "mc3",
    blurb: "Know-your-rights ink. Clean exits and soft freelance rates.",
    jobPayBonus: 2,
    legitimacyGain: 5,
    weeklyStipend: 35,
  },
  {
    id: "locksmith_license",
    name: "Locksmith License",
    courseId: "le1",
    blurb: "Legal entry calls. Pins count as civic skill when stamped.",
    oddsBonus: 2,
    oddsFamilies: ["petty", "street"],
    jobPayBonus: 2,
    legitimacyGain: 3,
    weeklyStipend: 28,
  },
  {
    id: "safe_mech",
    name: "Safe Mechanics Endorsement",
    courseId: "le2",
    blurb: "Dial and drill paper. Vault work looks almost legitimate.",
    oddsBonus: 3,
    oddsFamilies: ["street", "heavy"],
    jobPayBonus: 3,
    legitimacyGain: 3,
    weeklyStipend: 42,
  },
];

export const ITEMS: ItemDef[] = [
  { id: "crowbar", name: "Crowbar", kind: "tool", baseValue: 100, toolMod: 4, description: "Opens car doors and stubborn crates." },
  { id: "shim_kit", name: "Shim kit", kind: "tool", baseValue: 150, toolMod: 5, description: "Quiet entry for street work." },
  { id: "lockpick", name: "Lockpick set", kind: "tool", baseValue: 400, toolMod: 8, description: "Serious entry kit." },
  { id: "vest", name: "Basic armor vest", kind: "armor", baseValue: 1000, description: "Takes the edge off a bad night." },
  { id: "street_meds", name: "Street meds", kind: "consumable", baseValue: 60, description: "+15 life." },
  { id: "happy_pills", name: "Happy pills", kind: "consumable", baseValue: 120, description: "+40 happy." },
  { id: "bike", name: "Used bike", kind: "misc", baseValue: 300, description: "Fenceable scrap with wheels." },
  { id: "courier_bag", name: "Courier bag", kind: "misc", baseValue: 600, description: "Looks legit. Isn’t." },
  { id: "harbor_key", name: "Harbor keycard", kind: "tool", baseValue: 2500, toolMod: 6, description: "Rare dock access." },
  { id: "chip_stack", name: "Casino chip stack", kind: "misc", baseValue: 1800, description: "Warm plastic money." },
  { id: "knife", name: "Folding knife", kind: "weapon", baseValue: 200, description: "Close work." },
  { id: "bat", name: "Weighted bat", kind: "weapon", baseValue: 350, description: "Negotiation aid." },
  { id: "painkillers", name: "Painkillers", kind: "consumable", baseValue: 40, description: "+10 life, -5 stress." },
  { id: "evidence_burn", name: "Burn kit", kind: "consumable", baseValue: 500, description: "Drops investigation one stage." },
  { id: "threads", name: "Basic threads", kind: "flex", baseValue: 2000, description: "Respect starter kit." },
  { id: "suit", name: "Custom suit", kind: "flex", baseValue: 15000, description: "Looks like money." },
  { id: "food", name: "Leftover kit", kind: "consumable", baseValue: 30, description: "+20 happy." },
  { id: "lawyer_retainer", name: "Lawyer card", kind: "misc", baseValue: 2000, description: "One investigation stage down." },
  { id: "radio", name: "Scanner radio", kind: "tool", baseValue: 450, toolMod: 2, description: "Hear sweeps coming." },
  { id: "gloves", name: "Grip gloves", kind: "tool", baseValue: 80, toolMod: 1, description: "Fewer prints, better grip." },
  { id: "badge_blank", name: "Badge blank", kind: "tool", baseValue: 900, toolMod: 3, description: "Clone office access when the ink is warm." },
  { id: "drill_bit", name: "Quiet drill bit", kind: "tool", baseValue: 3200, toolMod: 7, description: "Vault work. Loud if you rush." },
];

export const RANK_TITLES = [
  "Nobody",
  "Street Rookie",
  "Hustler",
  "Operator",
  "Fixer",
  "Shadow",
  "Alley King",
  "Night Broker",
  "District Ghost",
  "Kingpin",
];

/** V0 NPC attack pool — district-scoped, not a coin-flip sandbox */
export const NPCS: NpcDef[] = [
  {
    id: "gr_courier",
    name: "Glassrow Courier",
    title: "Soft target",
    district: "glassrow",
    power: 18,
    str: 4,
    def: 3,
    spd: 8,
    dex: 6,
    life: 40,
    lootMin: 120,
    lootMax: 280,
    heatOnWin: 4,
    heatOnLose: 2,
    energyCost: 8,
    flavor: "Late drop run. Bag looks heavy.",
  },
  {
    id: "gr_bouncer",
    name: "Neon Door Bouncer",
    title: "Muscle",
    district: "glassrow",
    power: 42,
    str: 14,
    def: 12,
    spd: 6,
    dex: 5,
    life: 70,
    lootMin: 200,
    lootMax: 450,
    heatOnWin: 8,
    heatOnLose: 4,
    energyCost: 12,
    flavor: "Cuts the line with a look. Cuts you if you miss.",
  },
  {
    id: "gr_tourist",
    name: "Festival Tourist",
    title: "Easy mark",
    district: "glassrow",
    power: 12,
    str: 3,
    def: 2,
    spd: 5,
    dex: 4,
    life: 30,
    lootMin: 80,
    lootMax: 200,
    heatOnWin: 3,
    heatOnLose: 1,
    energyCost: 6,
    flavor: "Camera out. Wallet out. Awareness out.",
  },
  {
    id: "ms_loader",
    name: "Yard Loader",
    title: "Shift muscle",
    district: "millstone",
    power: 28,
    str: 10,
    def: 8,
    spd: 5,
    dex: 5,
    life: 55,
    lootMin: 150,
    lootMax: 320,
    heatOnWin: 5,
    heatOnLose: 3,
    energyCost: 10,
    flavor: "Ends a shift with steel-toed boots and bad temper.",
  },
  {
    id: "ms_scout",
    name: "Roof Scout",
    title: "Fast",
    district: "millstone",
    power: 34,
    str: 6,
    def: 5,
    spd: 14,
    dex: 11,
    life: 45,
    lootMin: 180,
    lootMax: 400,
    heatOnWin: 6,
    heatOnLose: 3,
    energyCost: 10,
    flavor: "Watches alleys. Might be watching you.",
  },
  {
    id: "ms_foreman",
    name: "Night Foreman",
    title: "Hard",
    district: "millstone",
    power: 50,
    str: 16,
    def: 14,
    spd: 7,
    dex: 6,
    life: 80,
    lootMin: 280,
    lootMax: 600,
    heatOnWin: 10,
    heatOnLose: 5,
    energyCost: 14,
    flavor: "Clipboard and a tire iron. Equal opportunity.",
  },
  {
    id: "dr_smuggler",
    name: "Pier Smuggler",
    title: "Armed",
    district: "docksreach",
    power: 48,
    str: 12,
    def: 10,
    spd: 10,
    dex: 12,
    life: 65,
    lootMin: 350,
    lootMax: 750,
    heatOnWin: 12,
    heatOnLose: 6,
    energyCost: 14,
    flavor: "Crate manifests that don’t match the crates.",
  },
  {
    id: "dr_longshore",
    name: "Longshore Brute",
    title: "Tank",
    district: "docksreach",
    power: 55,
    str: 18,
    def: 16,
    spd: 5,
    dex: 4,
    life: 90,
    lootMin: 300,
    lootMax: 650,
    heatOnWin: 11,
    heatOnLose: 5,
    energyCost: 15,
    flavor: "Moves containers. Moves people who get in the way.",
  },
  {
    id: "dr_lookout",
    name: "Harbor Lookout",
    title: "Skittish",
    district: "docksreach",
    power: 22,
    str: 5,
    def: 4,
    spd: 12,
    dex: 10,
    life: 35,
    lootMin: 200,
    lootMax: 420,
    heatOnWin: 7,
    heatOnLose: 4,
    energyCost: 9,
    flavor: "Whistle and a radio. Hit hard before the call goes out.",
  },
  {
    id: "ac_intern",
    name: "Clinic Intern",
    title: "Soft",
    district: "ashcourt",
    power: 16,
    str: 4,
    def: 3,
    spd: 7,
    dex: 6,
    life: 35,
    lootMin: 100,
    lootMax: 240,
    heatOnWin: 3,
    heatOnLose: 2,
    energyCost: 7,
    flavor: "Badge on a lanyard. Mind on the next shift.",
  },
  {
    id: "ac_security",
    name: "Ward Security",
    title: "Guard",
    district: "ashcourt",
    power: 40,
    str: 12,
    def: 11,
    spd: 6,
    dex: 6,
    life: 70,
    lootMin: 220,
    lootMax: 480,
    heatOnWin: 8,
    heatOnLose: 4,
    energyCost: 12,
    flavor: "Radio clipped. Eyes on every badge that doesn't belong.",
  },
  {
    id: "sy_exec",
    name: "Tower Courier",
    title: "Rich bag",
    district: "spireyard",
    power: 20,
    str: 5,
    def: 4,
    spd: 9,
    dex: 8,
    life: 40,
    lootMin: 300,
    lootMax: 700,
    heatOnWin: 6,
    heatOnLose: 3,
    energyCost: 9,
    flavor: "Locked briefcase. Soft shoes. Wrong neighborhood tonight.",
  },
  {
    id: "sy_guard",
    name: "Lobby Guard",
    title: "Hard",
    district: "spireyard",
    power: 52,
    str: 15,
    def: 14,
    spd: 7,
    dex: 7,
    life: 85,
    lootMin: 350,
    lootMax: 800,
    heatOnWin: 11,
    heatOnLose: 5,
    energyCost: 14,
    flavor: "Earpiece and a stare that invoices you.",
  },
  {
    id: "oc_thug",
    name: "Commons Thug",
    title: "Street",
    district: "oldcommons",
    power: 30,
    str: 11,
    def: 8,
    spd: 8,
    dex: 7,
    life: 55,
    lootMin: 140,
    lootMax: 320,
    heatOnWin: 5,
    heatOnLose: 3,
    energyCost: 10,
    flavor: "Knows every stairwell. Collects rent that isn't rent.",
  },
  {
    id: "oc_runner",
    name: "Night Runner",
    title: "Fast",
    district: "oldcommons",
    power: 26,
    str: 6,
    def: 5,
    spd: 15,
    dex: 12,
    life: 40,
    lootMin: 160,
    lootMax: 360,
    heatOnWin: 5,
    heatOnLose: 3,
    energyCost: 9,
    flavor: "Bag in the hoodie. Already gone if you blink.",
  },
];

export { HEADLINES } from "@/content/lore";

/** V0 properties — buy in-district only; rent − upkeep on tick */
export const PROPERTIES: PropertyDef[] = [
  {
    id: "gr_walkup",
    name: "Glassrow Walk-up",
    district: "glassrow",
    cost: 6000,
    weeklyIncome: 90,
    weeklyUpkeep: 40,
    blurb: "Third floor, thin walls, good sightlines on the tram.",
    raidRisk: 0.8,
  },
  {
    id: "gr_loft",
    name: "Neon Loft Share",
    district: "glassrow",
    cost: 14000,
    weeklyIncome: 220,
    weeklyUpkeep: 95,
    blurb: "Clean address. Mail that looks legitimate.",
    raidRisk: 0.6,
  },
  {
    id: "ms_flat",
    name: "Millstone Flat",
    district: "millstone",
    cost: 4500,
    weeklyIncome: 75,
    weeklyUpkeep: 35,
    blurb: "Cheap keys. Yard dogs know your scent.",
    raidRisk: 1,
  },
  {
    id: "ms_row",
    name: "Brick Rowhouse",
    district: "millstone",
    cost: 11000,
    weeklyIncome: 175,
    weeklyUpkeep: 70,
    blurb: "Basement storage. Tenants who don’t ask.",
    raidRisk: 0.9,
  },
  {
    id: "ms_shed",
    name: "Yard Shed Unit",
    district: "millstone",
    cost: 8000,
    weeklyIncome: 130,
    weeklyUpkeep: 55,
    blurb: "Corrugated roof, padlock theater, real lock elsewhere.",
    raidRisk: 1.1,
  },
  {
    id: "dr_cot",
    name: "Pier Cot",
    district: "docksreach",
    cost: 5000,
    weeklyIncome: 100,
    weeklyUpkeep: 55,
    blurb: "Salt air and night radios. Heat sticks here.",
    raidRisk: 1.3,
  },
  {
    id: "dr_bay",
    name: "Side Bay Lease",
    district: "docksreach",
    cost: 16000,
    weeklyIncome: 260,
    weeklyUpkeep: 110,
    blurb: "Half a bay for crates that never appear on manifests.",
    raidRisk: 1.2,
  },
  {
    id: "dr_safe",
    name: "Harbor Soft-House",
    district: "docksreach",
    cost: 22000,
    weeklyIncome: 200,
    weeklyUpkeep: 120,
    blurb: "Quiet front. Better when the sweep rolls past.",
    raidRisk: 0.7,
  },
  {
    id: "ac_studio",
    name: "Ashcourt Studio",
    district: "ashcourt",
    cost: 7000,
    weeklyIncome: 110,
    weeklyUpkeep: 50,
    blurb: "Near the clinic. Mail that looks civic.",
    raidRisk: 0.75,
  },
  {
    id: "ac_wardflat",
    name: "Ward-Adjacent Flat",
    district: "ashcourt",
    cost: 15000,
    weeklyIncome: 230,
    weeklyUpkeep: 100,
    blurb: "Quiet nights. Badge readers blink friendly.",
    raidRisk: 0.65,
  },
  {
    id: "sy_condo",
    name: "SpireYard Condo Share",
    district: "spireyard",
    cost: 28000,
    weeklyIncome: 340,
    weeklyUpkeep: 160,
    blurb: "Glass lobby. Interest likes this zip code.",
    raidRisk: 0.5,
  },
  {
    id: "sy_pent",
    name: "Lower Pent Lease",
    district: "spireyard",
    cost: 45000,
    weeklyIncome: 480,
    weeklyUpkeep: 220,
    blurb: "Not the top floor. Still too expensive to raid casually.",
    raidRisk: 0.4,
  },
  {
    id: "oc_room",
    name: "Commons Room",
    district: "oldcommons",
    cost: 3500,
    weeklyIncome: 60,
    weeklyUpkeep: 25,
    blurb: "Thin door, thick neighbors. Cheap start.",
    raidRisk: 1.2,
  },
  {
    id: "oc_walkup",
    name: "Commons Walk-up",
    district: "oldcommons",
    cost: 9000,
    weeklyIncome: 140,
    weeklyUpkeep: 55,
    blurb: "Four flights. Tenants who tip in street cash.",
    raidRisk: 1.05,
  },
];

/** Original Nightwire awards — not Torn titles */
export const AWARDS: AwardDef[] = [
  { id: "neon_scratch", name: "Neon Scratch", blurb: "First clean lift under the wires.", category: "crime" },
  { id: "first_fail", name: "Burn Mark", blurb: "Empty hands. Still breathing.", category: "crime" },
  { id: "corner_habit", name: "Corner Habit", blurb: "Petty work until it feels like muscle memory.", category: "crime" },
  { id: "alley_ledger", name: "Alley Ledger", blurb: "Street scores logged in sweat.", category: "crime" },
  { id: "heavy_breath", name: "Heavy Breath", blurb: "A heavy score that actually paid.", category: "crime" },
  { id: "punch_card", name: "Punch Card", blurb: "First legal shift on the books.", category: "work" },
  { id: "side_hustle", name: "Side Hustle", blurb: "First short contract. Clean cash without a boss.", category: "work" },
  { id: "gig_circuit", name: "Gig Circuit", blurb: "Eight contracts. The city knows your rate.", category: "work" },
  { id: "steady_hands", name: "Steady Hands", blurb: "Ten shifts. Still showing up.", category: "work" },
  { id: "name_on_roster", name: "Name on the Roster", blurb: "Someone wrote a promotion next to yours.", category: "work" },
  { id: "campus_ghost", name: "Campus Ghost", blurb: "Finished a course without vanishing.", category: "work" },
  { id: "ledger_clean", name: "Ledger Clean", blurb: "Bookkeeping cert. Interest likes you now.", category: "work" },
  { id: "dock_cert", name: "Dock Cert", blurb: "Harbor paper that opens heavier doors.", category: "work" },
  { id: "med_wing", name: "Med Wing", blurb: "First Aid stamped. Ward clocks notice.", category: "work" },
  { id: "pins_licensed", name: "Pins Licensed", blurb: "Locksmith paper. Doors answer cleaner.", category: "work" },
  { id: "keys_on_hook", name: "Keys on the Hook", blurb: "First property. Rent starts whispering.", category: "money" },
  { id: "rent_collector", name: "Rent Collector", blurb: "Two roofs. One ledger.", category: "money" },
  { id: "night_deposit", name: "Night Deposit", blurb: "Clean cash under glass.", category: "money" },
  { id: "nest_under_glass", name: "Nest Under Glass", blurb: "Five grand sleeping at the bank.", category: "money" },
  { id: "interest_drip", name: "Interest Drip", blurb: "The bank paid you for waiting.", category: "money" },
  { id: "ten_grand_glow", name: "Ten-Grand Glow", blurb: "Networth hits five figures.", category: "money" },
  { id: "iron_hours", name: "Iron Hours", blurb: "Ten gym sessions. Soft caps notice.", category: "body" },
  { id: "alley_mark", name: "Alley Mark", blurb: "Won a street fight that wasn’t a coin flip.", category: "body" },
  { id: "holding_cell_grad", name: "Holding Cell Grad", blurb: "Jailed once. Story material.", category: "body" },
  { id: "three_rails", name: "Three Rails", blurb: "Walked three districts on the wire.", category: "city" },
  { id: "six_rails", name: "Six Rails", blurb: "Glassrow to OldCommons — the whole V1 map underfoot.", category: "city" },
  { id: "wire_climber", name: "Wire Climber", blurb: "Level 5 on the Nightwire climb.", category: "city" },
  { id: "too_loud", name: "Too Loud", blurb: "Heat past 80. The city heard you.", category: "city" },
  { id: "vex_noticed", name: "Vex Noticed", blurb: "Rival ink in the paper. You’re on their board.", category: "story" },
  { id: "first_favor", name: "First Favor", blurb: "Someone on the wire answered when you asked.", category: "story" },
  { id: "tip_bought", name: "Warm Tip", blurb: "Paid for intel that still smelled like the street.", category: "story" },
  { id: "wide_rolodex", name: "Wide Rolodex", blurb: "Six different voices answered. The city got smaller.", category: "story" },
  { id: "first_board", name: "First Board", blurb: "Finished an organized prep and walked out with the take.", category: "crime" },
  { id: "board_collector", name: "Board Collector", blurb: "Three organized ops in the bag.", category: "crime" },
];

/** V2 contacts — 12 people; unlock by district/job/edu; tips/favors matter */
export const CONTACTS: ContactDef[] = [
  {
    id: "reed",
    name: "Reed",
    role: "Mentor",
    homeDistrict: "glassrow",
    blurb: "Older voice on a cheap line. Keeps you from burning out early.",
    unlockHint: "Always available",
    actions: [
      {
        id: "ping",
        label: "Check in",
        blurb: "+happy, −stress. Soft pep talk.",
      },
      {
        id: "ask_favor",
        label: "Ask favor",
        blurb: "Spend favor for a small XP nudge.",
        favorCost: 2,
      },
    ],
  },
  {
    id: "mara",
    name: "Mara Vale",
    role: "Counsel",
    homeDistrict: "glassrow",
    blurb: "Clean suit, dirty Rolodex. Investigation is her language.",
    unlockHint: "Jail once, investigation open, or level 2+",
    actions: [
      {
        id: "retain",
        label: "Retain hour",
        blurb: "Cheaper lawyer: drop investigation one stage ($1200 clean).",
        cleanCost: 1200,
      },
      {
        id: "cool_case",
        label: "Cool the case",
        blurb: "Spend favor + $800 clean to drop two stages.",
        favorCost: 2,
        cleanCost: 800,
      },
    ],
  },
  {
    id: "kilo",
    name: "Kilo",
    role: "Pier tipster",
    homeDistrict: "docksreach",
    blurb: "Whistles when containers move. Harbor windows are his product.",
    unlockHint: "Visit DocksReach",
    actions: [
      {
        id: "tip",
        label: "Buy pier tip",
        blurb: "+heavy odds for 4h (harbor window). Costs street cash.",
        streetCost: 350,
      },
      {
        id: "ping",
        label: "Radio check",
        blurb: "Soft heat bleed if you’re near the water.",
      },
    ],
  },
  {
    id: "ivy",
    name: "Ivy Chen",
    role: "Campus voice",
    homeDistrict: "millstone",
    blurb: "Advisor who notices when your schedule and your heat don’t match.",
    unlockHint: "Enroll or finish a course",
    actions: [
      {
        id: "office_hours",
        label: "Office hours",
        blurb: "−stress, +happy. Study nerves settle.",
      },
      {
        id: "ping",
        label: "Heat warning",
        blurb: "If heat is high, she talks you down (−heat soft).",
      },
    ],
  },
  {
    id: "nix",
    name: "Nix",
    role: "Alley broker",
    homeDistrict: "millstone",
    blurb: "Sells timing, not tools. Tips expire when the street forgets.",
    unlockHint: "5+ crime attempts",
    actions: [
      {
        id: "tip",
        label: "Street tip",
        blurb: "+street-family odds for 3h. Street cash.",
        streetCost: 250,
      },
      {
        id: "ask_favor",
        label: "Call marker",
        blurb: "Spend favor: petty odds bump for 2h.",
        favorCost: 1,
      },
    ],
  },
  {
    id: "soot",
    name: "Soot",
    role: "Iron contact",
    homeDistrict: "millstone",
    blurb: "Spotter who knows when your form is lying about your head.",
    unlockHint: "3+ gym sessions",
    actions: [
      {
        id: "walk_off",
        label: "Walk it off",
        blurb: "−stress, +happy. Body reset.",
      },
      {
        id: "ping",
        label: "Spot me",
        blurb: "Tiny favor gain if you’re not fried.",
      },
    ],
  },
  {
    id: "wren",
    name: "Wren",
    role: "Commons fence",
    homeDistrict: "oldcommons",
    blurb: "Buys what the street won’t claim. Pays ugly, pays fast.",
    unlockHint: "Visit OldCommons",
    actions: [
      {
        id: "tip",
        label: "Buy window tip",
        blurb: "+petty odds for 3h. Street cash.",
        streetCost: 200,
      },
      {
        id: "ask_favor",
        label: "Fence skim",
        blurb: "Spend favor: turn $400 street into ~$260 clean.",
        favorCost: 2,
        streetCost: 400,
      },
    ],
  },
  {
    id: "calder",
    name: "Calder",
    role: "Ward whisper",
    homeDistrict: "ashcourt",
    blurb: "Orderly who never writes what he can forget. Clinic doors open sideways.",
    unlockHint: "Visit Ashcourt",
    actions: [
      {
        id: "walk_off",
        label: "Quiet discharge",
        blurb: "In ward: cut remaining hospital time in half ($500 clean). Else: life/wounds soft.",
        cleanCost: 500,
      },
      {
        id: "ping",
        label: "Hall check",
        blurb: "−stress, soft life if you’re upright.",
      },
    ],
  },
  {
    id: "quill",
    name: "Quill",
    role: "Spire clerk",
    homeDistrict: "spireyard",
    blurb: "Stamps forms like they owe him. Legitimacy is a filing cabinet.",
    unlockHint: "Visit SpireYard or bank once",
    actions: [
      {
        id: "ping",
        label: "File a note",
        blurb: "+legitimacy soft. Paper trail that helps.",
      },
      {
        id: "ask_favor",
        label: "Rush stamp",
        blurb: "Spend favor: small clean stipend + legitimacy.",
        favorCost: 2,
      },
    ],
  },
  {
    id: "joss",
    name: "Joss",
    role: "Shift fixer",
    homeDistrict: "glassrow",
    blurb: "Knows which managers need a body and which need a story.",
    unlockHint: "Work 5 job shifts",
    actions: [
      {
        id: "ask_favor",
        label: "Odd job",
        blurb: "Spend favor: quick clean cash off the books.",
        favorCost: 1,
      },
      {
        id: "ping",
        label: "Swap shifts",
        blurb: "+energy if you’ve got room. Soft favor.",
      },
    ],
  },
  {
    id: "haze",
    name: "Haze",
    role: "Heat broker",
    homeDistrict: "docksreach",
    blurb: "Sells cool air and bad alibis. Smoke follows the money.",
    unlockHint: "Peak heat 40+",
    actions: [
      {
        id: "tip",
        label: "Buy cool",
        blurb: "−15 heat. Street cash for silence.",
        streetCost: 450,
      },
      {
        id: "ping",
        label: "Smoke check",
        blurb: "Soft −heat near the pier; else nerves only.",
      },
    ],
  },
  {
    id: "pike",
    name: "Pike",
    role: "Bail runner",
    homeDistrict: "oldcommons",
    blurb: "Shows up with a clipboard and a clock. Time is his inventory.",
    unlockHint: "Jail once",
    actions: [
      {
        id: "retain",
        label: "Cut time",
        blurb: "While jailed: halve remaining lockup ($700 clean).",
        cleanCost: 700,
      },
      {
        id: "ping",
        label: "Walk free talk",
        blurb: "Outside: −stress, soft heat bleed. Favor if clean.",
      },
    ],
  },
];

export function getCrime(id: string) {
  return CRIMES.find((c) => c.id === id);
}
export function getJob(id: string) {
  return JOBS.find((j) => j.id === id);
}
export function getGig(id: string) {
  return GIGS.find((g) => g.id === id);
}
export function getCourse(id: string) {
  return COURSES.find((c) => c.id === id);
}
export function getLicense(id: string) {
  return LICENSES.find((l) => l.id === id);
}
export function getItem(id: string) {
  return ITEMS.find((i) => i.id === id);
}
export function getDistrict(id: string) {
  return DISTRICTS.find((d) => d.id === id);
}
export function getNpc(id: string) {
  return NPCS.find((n) => n.id === id);
}
export function getProperty(id: string) {
  return PROPERTIES.find((p) => p.id === id);
}
export function getAward(id: string) {
  return AWARDS.find((a) => a.id === id);
}
export function getContact(id: string) {
  return CONTACTS.find((c) => c.id === id);
}
export function npcsInDistrict(district: string) {
  return NPCS.filter((n) => n.district === district);
}
export function propertiesInDistrict(district: string) {
  return PROPERTIES.filter((p) => p.district === district);
}
