import type {
  AwardDef,
  ContactDef,
  CourseDef,
  CrimeDef,
  DistrictDef,
  GigDef,
  ItemDef,
  JobDef,
  NpcDef,
  PropertyDef,
} from "@/game/types";

export const DISTRICTS: DistrictDef[] = [
  {
    id: "glassrow",
    name: "Glassrow",
    crimeBias: { petty: 10, heavy: -10 },
    travelCost: 50,
    travelSeconds: 120,
    shopStyle: "elite",
    risk: "Low jail",
  },
  {
    id: "millstone",
    name: "Millstone",
    crimeBias: { street: 15 },
    travelCost: 30,
    travelSeconds: 150,
    shopStyle: "tools",
    risk: "Medium",
  },
  {
    id: "docksreach",
    name: "DocksReach",
    crimeBias: { heavy: 20 },
    travelCost: 40,
    travelSeconds: 180,
    shopStyle: "black",
    risk: "High heat",
  },
];

export const CRIMES: CrimeDef[] = [
  { id: "shoplift", name: "Shoplift corner store", tier: "petty", family: "petty", nerve: 1, difficulty: 28, cashMin: 80, cashMax: 150, xp: 5, heat: 1, failDamage: 4, favoredDistricts: ["glassrow"] },
  { id: "pickpocket", name: "Pick pocket tram", tier: "petty", family: "petty", nerve: 1, difficulty: 30, cashMin: 100, cashMax: 200, xp: 6, heat: 1, failDamage: 5, favoredDistricts: ["glassrow", "millstone"] },
  { id: "vending", name: "Siphon vending machine", tier: "petty", family: "petty", nerve: 2, difficulty: 32, cashMin: 150, cashMax: 300, xp: 8, heat: 2, failDamage: 6, favoredDistricts: ["millstone"] },
  { id: "bicycle", name: "Steal bicycle", tier: "petty", family: "petty", nerve: 2, difficulty: 34, cashMin: 200, cashMax: 400, xp: 10, heat: 2, failDamage: 7, favoredDistricts: ["millstone"] },
  { id: "mug", name: "Mug alley tourist", tier: "street", family: "street", nerve: 3, difficulty: 48, cashMin: 400, cashMax: 800, xp: 20, heat: 4, failDamage: 12, favoredDistricts: ["glassrow"] },
  { id: "car_breakin", name: "Car break-in", tier: "street", family: "street", nerve: 3, difficulty: 52, cashMin: 600, cashMax: 1200, xp: 25, heat: 5, failDamage: 14, requiresTool: "crowbar", favoredDistricts: ["millstone"] },
  { id: "warehouse", name: "Warehouse snatch", tier: "street", family: "street", nerve: 4, difficulty: 58, cashMin: 800, cashMax: 1500, xp: 30, heat: 6, failDamage: 16, requiresCourse: "se1", favoredDistricts: ["millstone", "docksreach"] },
  { id: "pharmacy", name: "Pharmacy till grab", tier: "street", family: "street", nerve: 4, difficulty: 62, cashMin: 1000, cashMax: 2000, xp: 35, heat: 7, failDamage: 18, requiresCourse: "se1", favoredDistricts: ["glassrow"] },
  { id: "armored", name: "Armored lobby distraction", tier: "heavy", family: "heavy", nerve: 6, difficulty: 90, cashMin: 2500, cashMax: 5000, xp: 60, heat: 12, failDamage: 28, requiresLevel: 5, favoredDistricts: ["glassrow"] },
  { id: "casino_cage", name: "Casino cage probe", tier: "heavy", family: "heavy", nerve: 7, difficulty: 110, cashMin: 4000, cashMax: 8000, xp: 80, heat: 15, failDamage: 32, requiresLevel: 7, requiresCourse: "cf2", favoredDistricts: ["glassrow"] },
  { id: "harbor", name: "Harbor container heist", tier: "heavy", family: "heavy", nerve: 7, difficulty: 120, cashMin: 5000, cashMax: 10000, xp: 100, heat: 18, failDamage: 35, requiresLevel: 8, requiresCourse: "hl1", favoredDistricts: ["docksreach"] },
  { id: "courier", name: "Federal courier intercept", tier: "heavy", family: "heavy", nerve: 8, difficulty: 150, cashMin: 8000, cashMax: 15000, xp: 150, heat: 25, failDamage: 40, requiresLevel: 10, requiresCourse: "cf2", favoredDistricts: ["docksreach", "glassrow"] },
];

export const JOBS: JobDef[] = [
  {
    id: "retail_1",
    career: "retail",
    rank: 1,
    title: "Retail Clerk",
    basePay: 800,
    energy: 5,
    districtBias: ["glassrow"],
    special: "Shrinkage cover",
    blurb: "Glassrow floors. Watch cameras, move product, keep heat quiet.",
    specialtyFamilies: ["petty"],
    specialtyCrimeIds: ["shoplift", "vending"],
  },
  {
    id: "retail_2",
    career: "retail",
    rank: 2,
    title: "Shift Lead",
    basePay: 1400,
    energy: 5,
    districtBias: ["glassrow"],
    special: "Shrinkage cover",
    blurb: "Keys, schedules, and cover stories when inventory walks.",
    promoteXp: 300,
    promoteCourse: "cf1",
    specialtyFamilies: ["petty"],
    specialtyCrimeIds: ["shoplift", "vending", "pickpocket"],
  },
  {
    id: "kitchen_1",
    career: "kitchen",
    rank: 1,
    title: "Kitchen Hand",
    basePay: 700,
    energy: 5,
    districtBias: ["millstone"],
    special: "Leftover kit",
    blurb: "Millstone heat and grease. Stable clean pay when the street runs hot.",
    specialtyCrimeIds: ["pharmacy"],
  },
  {
    id: "kitchen_2",
    career: "kitchen",
    rank: 2,
    title: "Line Cook",
    basePay: 1200,
    energy: 5,
    districtBias: ["millstone"],
    special: "Leftover kit",
    blurb: "Own the line. Better tips, better leftovers, better cover.",
    promoteXp: 300,
    promoteCourse: "se2",
    specialtyCrimeIds: ["pharmacy"],
  },
  {
    id: "dock_1",
    career: "dockhand",
    rank: 1,
    title: "Dockhand",
    basePay: 900,
    energy: 5,
    districtBias: ["docksreach"],
    special: "Mislabel",
    blurb: "Cranes and crates. Harbor work opens container ops later.",
    requiresLevel: 2,
    specialtyFamilies: ["heavy", "street"],
    specialtyCrimeIds: ["harbor", "warehouse"],
  },
  {
    id: "dock_2",
    career: "dockhand",
    rank: 2,
    title: "Crane Assistant",
    basePay: 1600,
    energy: 5,
    districtBias: ["docksreach"],
    special: "Mislabel",
    blurb: "Yard access and miscount opportunities. Harbor specialty deepens.",
    promoteXp: 300,
    promoteCourse: "hl1",
    specialtyFamilies: ["heavy", "street"],
    specialtyCrimeIds: ["harbor", "warehouse", "courier"],
  },
  {
    id: "driver_1",
    career: "driver",
    rank: 1,
    title: "Driver",
    basePay: 750,
    energy: 5,
    districtBias: ["millstone", "glassrow"],
    special: "Fare tip",
    blurb: "Wheels and routes. Learn the city by meter.",
    specialtyFamilies: ["street"],
    specialtyCrimeIds: ["car_breakin", "mug"],
  },
  {
    id: "driver_2",
    career: "driver",
    rank: 2,
    title: "Night Driver",
    basePay: 1300,
    energy: 5,
    districtBias: ["millstone", "glassrow"],
    special: "Fare tip",
    blurb: "After-dark fares pay more. You know every alley camera.",
    promoteXp: 280,
    promoteCourse: "se1",
    specialtyFamilies: ["street"],
    specialtyCrimeIds: ["car_breakin", "mug", "bicycle"],
  },
];

/** V0 short legal contracts — playable unemployed; education boosts pay */
export const GIGS: GigDef[] = [
  {
    id: "courier_drop",
    name: "Courier drop",
    blurb: "Bag A to B before the bag sweats. Clean cash, soft legs.",
    basePay: 280,
    energy: 3,
    districtBias: ["glassrow", "millstone"],
    legitimacyGain: 0.3,
    special: "Extra tip",
  },
  {
    id: "data_entry",
    name: "Data entry sprint",
    blurb: "Keys and coffee. No glory, honest hours.",
    basePay: 320,
    energy: 4,
    districtBias: ["glassrow"],
    legitimacyGain: 0.4,
    special: "Overtime stub",
  },
  {
    id: "night_watch",
    name: "Night watch",
    blurb: "Sit still, log shadows. Civic clients hate heat on your file.",
    basePay: 380,
    energy: 4,
    districtBias: ["millstone", "docksreach"],
    maxHeat: 45,
    legitimacyGain: 0.5,
    special: "Quiet bonus",
  },
  {
    id: "tutoring",
    name: "Tutoring hour",
    blurb: "Explain City Navigation to someone who still gets lost.",
    basePay: 340,
    energy: 3,
    districtBias: ["glassrow", "millstone"],
    requiresCourse: "se1",
    legitimacyGain: 0.6,
    special: "Grateful tip",
  },
  {
    id: "pier_walk",
    name: "Pier walk gig",
    blurb: "Escort tourists past the cranes. Stress bleeds into the water.",
    basePay: 220,
    energy: 3,
    districtBias: ["docksreach"],
    happyGain: 25,
    legitimacyGain: 0.2,
    special: "Calm stretch",
  },
  {
    id: "campus_filing",
    name: "Campus filing",
    blurb: "Work-study adjacent. Stacks of paper, stipend-adjacent pay.",
    basePay: 260,
    energy: 3,
    districtBias: ["millstone", "glassrow"],
    requiresStudy: true,
    legitimacyGain: 0.5,
    special: "Advisor nod",
  },
  {
    id: "freight_assist",
    name: "Freight assist",
    blurb: "Move crates without asking what’s inside. Dock hours.",
    basePay: 420,
    energy: 4,
    districtBias: ["docksreach"],
    requiresLevel: 2,
    legitimacyGain: 0.3,
    special: "Yard tip",
  },
  {
    id: "civic_clipboard",
    name: "Civic clipboard",
    blurb: "Survey forms for the city. Your heat must look boring.",
    basePay: 360,
    energy: 3,
    districtBias: ["glassrow"],
    maxHeat: 30,
    requiresLevel: 2,
    legitimacyGain: 0.8,
    special: "Civic stamp",
  },
];

export const COURSES: CourseDef[] = [
  {
    id: "se1",
    school: "Street Electives",
    name: "City Navigation",
    hours: 12,
    fee: 200,
    stipendPerHour: 20,
    blurb: "Maps, cameras, and soft exits. Gates street warehouse/pharmacy work.",
    unlocks: ["warehouse", "pharmacy"],
    oddsBonus: 5,
    oddsFamilies: ["street"],
  },
  {
    id: "se2",
    school: "Street Electives",
    name: "Persuasion Basics",
    hours: 24,
    fee: 400,
    stipendPerHour: 30,
    blurb: "Talk soft, walk hard. Kitchen promotion exam + gig pay.",
    requiresCourse: "se1",
    gigPayBonus: 10,
    oddsBonus: 3,
    oddsFamilies: ["petty", "street"],
  },
  {
    id: "se3",
    school: "Street Electives",
    name: "Fitness Study",
    hours: 18,
    fee: 300,
    stipendPerHour: 25,
    blurb: "Classroom bulk. Raises gym soft cap permanently.",
    requiresCourse: "se1",
    softCapBonus: 5,
  },
  {
    id: "cf1",
    school: "Commerce & Finance",
    name: "Bookkeeping",
    hours: 24,
    fee: 500,
    stipendPerHour: 40,
    blurb: "Clean ledgers. Job pay up, bank interest up, retail promotion exam.",
    requiresLevel: 2,
    jobPayBonus: 5,
    bankInterestBonus: 0.5,
  },
  {
    id: "cf2",
    school: "Commerce & Finance",
    name: "Business Basics",
    hours: 48,
    fee: 1000,
    stipendPerHour: 50,
    blurb: "Fronts and floats. Unlocks casino cage (and courier with level).",
    requiresCourse: "cf1",
    unlocks: ["casino_cage", "courier"],
    oddsBonus: 4,
    oddsFamilies: ["heavy"],
  },
  {
    id: "hl1",
    school: "Harbor & Logistics",
    name: "Dock Safety",
    hours: 18,
    fee: 400,
    stipendPerHour: 35,
    blurb: "Cert for cranes and containers. Unlocks harbor heist; dock promotion exam.",
    requiresLevel: 2,
    unlocks: ["harbor"],
    jobPayBonus: 10,
    oddsBonus: 5,
    oddsFamilies: ["heavy"],
  },
];

export const ITEMS: ItemDef[] = [
  { id: "crowbar", name: "Crowbar", kind: "tool", baseValue: 100, toolMod: 4, description: "Opens car doors and stubborn crates." },
  { id: "shim_kit", name: "Shim kit", kind: "tool", baseValue: 150, toolMod: 5, description: "Quiet entry for street work." },
  { id: "lockpick", name: "Lockpick set", kind: "tool", baseValue: 400, toolMod: 8, description: "Serious entry kit." },
  { id: "vest", name: "Basic armor vest", kind: "armor", baseValue: 1000, description: "Takes the edge off a bad night." },
  { id: "street_meds", name: "Street meds", kind: "consumable", baseValue: 60, description: "+15 life." },
  { id: "happy_pills", name: "Happy pills", kind: "consumable", baseValue: 120, description: "+40 happy." },
  { id: "bike", name: "Used bike", kind: "misc", baseValue: 300, description: "Fenceable scrap with wheels." },
  { id: "courier_bag", name: "Courier bag", kind: "misc", baseValue: 600, description: "Looks legit. Isn’t." },
  { id: "harbor_key", name: "Harbor keycard", kind: "tool", baseValue: 2500, toolMod: 6, description: "Rare dock access." },
  { id: "chip_stack", name: "Casino chip stack", kind: "misc", baseValue: 1800, description: "Warm plastic money." },
  { id: "knife", name: "Folding knife", kind: "weapon", baseValue: 200, description: "Close work." },
  { id: "bat", name: "Weighted bat", kind: "weapon", baseValue: 350, description: "Negotiation aid." },
  { id: "painkillers", name: "Painkillers", kind: "consumable", baseValue: 40, description: "+10 life, -5 stress." },
  { id: "evidence_burn", name: "Burn kit", kind: "consumable", baseValue: 500, description: "Drops investigation one stage." },
  { id: "threads", name: "Basic threads", kind: "flex", baseValue: 2000, description: "Respect starter kit." },
  { id: "suit", name: "Custom suit", kind: "flex", baseValue: 15000, description: "Looks like money." },
  { id: "food", name: "Leftover kit", kind: "consumable", baseValue: 30, description: "+20 happy." },
  { id: "lawyer_retainer", name: "Lawyer card", kind: "misc", baseValue: 2000, description: "One investigation stage down." },
  { id: "radio", name: "Scanner radio", kind: "tool", baseValue: 450, toolMod: 2, description: "Hear sweeps coming." },
  { id: "gloves", name: "Grip gloves", kind: "tool", baseValue: 80, toolMod: 1, description: "Fewer prints, better grip." },
];

export const RANK_TITLES = [
  "Nobody",
  "Street Rookie",
  "Hustler",
  "Operator",
  "Fixer",
  "Shadow",
  "Alley King",
  "Night Broker",
  "District Ghost",
  "Kingpin",
];

/** V0 NPC attack pool — district-scoped, not a coin-flip sandbox */
export const NPCS: NpcDef[] = [
  {
    id: "gr_courier",
    name: "Glassrow Courier",
    title: "Soft target",
    district: "glassrow",
    power: 18,
    str: 4,
    def: 3,
    spd: 8,
    dex: 6,
    life: 40,
    lootMin: 120,
    lootMax: 280,
    heatOnWin: 4,
    heatOnLose: 2,
    energyCost: 8,
    flavor: "Late drop run. Bag looks heavy.",
  },
  {
    id: "gr_bouncer",
    name: "Neon Door Bouncer",
    title: "Muscle",
    district: "glassrow",
    power: 42,
    str: 14,
    def: 12,
    spd: 6,
    dex: 5,
    life: 70,
    lootMin: 200,
    lootMax: 450,
    heatOnWin: 8,
    heatOnLose: 4,
    energyCost: 12,
    flavor: "Cuts the line with a look. Cuts you if you miss.",
  },
  {
    id: "gr_tourist",
    name: "Festival Tourist",
    title: "Easy mark",
    district: "glassrow",
    power: 12,
    str: 3,
    def: 2,
    spd: 5,
    dex: 4,
    life: 30,
    lootMin: 80,
    lootMax: 200,
    heatOnWin: 3,
    heatOnLose: 1,
    energyCost: 6,
    flavor: "Camera out. Wallet out. Awareness out.",
  },
  {
    id: "ms_loader",
    name: "Yard Loader",
    title: "Shift muscle",
    district: "millstone",
    power: 28,
    str: 10,
    def: 8,
    spd: 5,
    dex: 5,
    life: 55,
    lootMin: 150,
    lootMax: 320,
    heatOnWin: 5,
    heatOnLose: 3,
    energyCost: 10,
    flavor: "Ends a shift with steel-toed boots and bad temper.",
  },
  {
    id: "ms_scout",
    name: "Roof Scout",
    title: "Fast",
    district: "millstone",
    power: 34,
    str: 6,
    def: 5,
    spd: 14,
    dex: 11,
    life: 45,
    lootMin: 180,
    lootMax: 400,
    heatOnWin: 6,
    heatOnLose: 3,
    energyCost: 10,
    flavor: "Watches alleys. Might be watching you.",
  },
  {
    id: "ms_foreman",
    name: "Night Foreman",
    title: "Hard",
    district: "millstone",
    power: 50,
    str: 16,
    def: 14,
    spd: 7,
    dex: 6,
    life: 80,
    lootMin: 280,
    lootMax: 600,
    heatOnWin: 10,
    heatOnLose: 5,
    energyCost: 14,
    flavor: "Clipboard and a tire iron. Equal opportunity.",
  },
  {
    id: "dr_smuggler",
    name: "Pier Smuggler",
    title: "Armed",
    district: "docksreach",
    power: 48,
    str: 12,
    def: 10,
    spd: 10,
    dex: 12,
    life: 65,
    lootMin: 350,
    lootMax: 750,
    heatOnWin: 12,
    heatOnLose: 6,
    energyCost: 14,
    flavor: "Crate manifests that don’t match the crates.",
  },
  {
    id: "dr_longshore",
    name: "Longshore Brute",
    title: "Tank",
    district: "docksreach",
    power: 55,
    str: 18,
    def: 16,
    spd: 5,
    dex: 4,
    life: 90,
    lootMin: 300,
    lootMax: 650,
    heatOnWin: 11,
    heatOnLose: 5,
    energyCost: 15,
    flavor: "Moves containers. Moves people who get in the way.",
  },
  {
    id: "dr_lookout",
    name: "Harbor Lookout",
    title: "Skittish",
    district: "docksreach",
    power: 22,
    str: 5,
    def: 4,
    spd: 12,
    dex: 10,
    life: 35,
    lootMin: 200,
    lootMax: 420,
    heatOnWin: 7,
    heatOnLose: 4,
    energyCost: 9,
    flavor: "Whistle and a radio. Hit hard before the call goes out.",
  },
];

export const HEADLINES = [
  "Glassrow lights flicker again — petty theft spikes",
  "Millstone warehouse cameras go dark for an hour",
  "Dockhands walk out — harbor slowdown",
  "Festival crowds thicken Glassrow alleys",
  "Police sweep announced across midtown",
  "Vex hits jewelry score in Glassrow",
  "New grad on the street. Competition?",
  "Amateur hour. Someone took a corner.",
  "Bazaar restock: tools and warm chips",
  "City council debates late-night patrol budgets",
];

/** V0 properties — buy in-district only; rent − upkeep on tick */
export const PROPERTIES: PropertyDef[] = [
  {
    id: "gr_walkup",
    name: "Glassrow Walk-up",
    district: "glassrow",
    cost: 6000,
    weeklyIncome: 90,
    weeklyUpkeep: 40,
    blurb: "Third floor, thin walls, good sightlines on the tram.",
    raidRisk: 0.8,
  },
  {
    id: "gr_loft",
    name: "Neon Loft Share",
    district: "glassrow",
    cost: 14000,
    weeklyIncome: 220,
    weeklyUpkeep: 95,
    blurb: "Clean address. Mail that looks legitimate.",
    raidRisk: 0.6,
  },
  {
    id: "ms_flat",
    name: "Millstone Flat",
    district: "millstone",
    cost: 4500,
    weeklyIncome: 75,
    weeklyUpkeep: 35,
    blurb: "Cheap keys. Yard dogs know your scent.",
    raidRisk: 1,
  },
  {
    id: "ms_row",
    name: "Brick Rowhouse",
    district: "millstone",
    cost: 11000,
    weeklyIncome: 175,
    weeklyUpkeep: 70,
    blurb: "Basement storage. Tenants who don’t ask.",
    raidRisk: 0.9,
  },
  {
    id: "ms_shed",
    name: "Yard Shed Unit",
    district: "millstone",
    cost: 8000,
    weeklyIncome: 130,
    weeklyUpkeep: 55,
    blurb: "Corrugated roof, padlock theater, real lock elsewhere.",
    raidRisk: 1.1,
  },
  {
    id: "dr_cot",
    name: "Pier Cot",
    district: "docksreach",
    cost: 5000,
    weeklyIncome: 100,
    weeklyUpkeep: 55,
    blurb: "Salt air and night radios. Heat sticks here.",
    raidRisk: 1.3,
  },
  {
    id: "dr_bay",
    name: "Side Bay Lease",
    district: "docksreach",
    cost: 16000,
    weeklyIncome: 260,
    weeklyUpkeep: 110,
    blurb: "Half a bay for crates that never appear on manifests.",
    raidRisk: 1.2,
  },
  {
    id: "dr_safe",
    name: "Harbor Soft-House",
    district: "docksreach",
    cost: 22000,
    weeklyIncome: 200,
    weeklyUpkeep: 120,
    blurb: "Quiet front. Better when the sweep rolls past.",
    raidRisk: 0.7,
  },
];

/** Original Nightwire awards — not Torn titles */
export const AWARDS: AwardDef[] = [
  { id: "neon_scratch", name: "Neon Scratch", blurb: "First clean lift under the wires.", category: "crime" },
  { id: "first_fail", name: "Burn Mark", blurb: "Empty hands. Still breathing.", category: "crime" },
  { id: "corner_habit", name: "Corner Habit", blurb: "Petty work until it feels like muscle memory.", category: "crime" },
  { id: "alley_ledger", name: "Alley Ledger", blurb: "Street scores logged in sweat.", category: "crime" },
  { id: "heavy_breath", name: "Heavy Breath", blurb: "A heavy score that actually paid.", category: "crime" },
  { id: "punch_card", name: "Punch Card", blurb: "First legal shift on the books.", category: "work" },
  { id: "side_hustle", name: "Side Hustle", blurb: "First short contract. Clean cash without a boss.", category: "work" },
  { id: "gig_circuit", name: "Gig Circuit", blurb: "Eight contracts. The city knows your rate.", category: "work" },
  { id: "steady_hands", name: "Steady Hands", blurb: "Ten shifts. Still showing up.", category: "work" },
  { id: "name_on_roster", name: "Name on the Roster", blurb: "Someone wrote a promotion next to yours.", category: "work" },
  { id: "campus_ghost", name: "Campus Ghost", blurb: "Finished a course without vanishing.", category: "work" },
  { id: "ledger_clean", name: "Ledger Clean", blurb: "Bookkeeping cert. Interest likes you now.", category: "work" },
  { id: "dock_cert", name: "Dock Cert", blurb: "Harbor paper that opens heavier doors.", category: "work" },
  { id: "keys_on_hook", name: "Keys on the Hook", blurb: "First property. Rent starts whispering.", category: "money" },
  { id: "rent_collector", name: "Rent Collector", blurb: "Two roofs. One ledger.", category: "money" },
  { id: "night_deposit", name: "Night Deposit", blurb: "Clean cash under glass.", category: "money" },
  { id: "nest_under_glass", name: "Nest Under Glass", blurb: "Five grand sleeping at the bank.", category: "money" },
  { id: "interest_drip", name: "Interest Drip", blurb: "The bank paid you for waiting.", category: "money" },
  { id: "ten_grand_glow", name: "Ten-Grand Glow", blurb: "Networth hits five figures.", category: "money" },
  { id: "iron_hours", name: "Iron Hours", blurb: "Ten gym sessions. Soft caps notice.", category: "body" },
  { id: "alley_mark", name: "Alley Mark", blurb: "Won a street fight that wasn’t a coin flip.", category: "body" },
  { id: "holding_cell_grad", name: "Holding Cell Grad", blurb: "Jailed once. Story material.", category: "body" },
  { id: "three_rails", name: "Three Rails", blurb: "Glassrow, Millstone, DocksReach — walked all three.", category: "city" },
  { id: "wire_climber", name: "Wire Climber", blurb: "Level 5 on the Nightwire climb.", category: "city" },
  { id: "too_loud", name: "Too Loud", blurb: "Heat past 80. The city heard you.", category: "city" },
  { id: "vex_noticed", name: "Vex Noticed", blurb: "Rival ink in the paper. You’re on their board.", category: "story" },
  { id: "first_favor", name: "First Favor", blurb: "Someone on the wire answered when you asked.", category: "story" },
  { id: "tip_bought", name: "Warm Tip", blurb: "Paid for intel that still smelled like the street.", category: "story" },
];

/** V0 contacts — unlock by play; tips/favors matter to odds, heat, stress */
export const CONTACTS: ContactDef[] = [
  {
    id: "reed",
    name: "Reed",
    role: "Mentor",
    homeDistrict: "glassrow",
    blurb: "Older voice on a cheap line. Keeps you from burning out early.",
    unlockHint: "Always available",
    actions: [
      {
        id: "ping",
        label: "Check in",
        blurb: "+happy, −stress. Soft pep talk.",
      },
      {
        id: "ask_favor",
        label: "Ask favor",
        blurb: "Spend favor for a small XP nudge.",
        favorCost: 2,
      },
    ],
  },
  {
    id: "mara",
    name: "Mara Vale",
    role: "Counsel",
    homeDistrict: "glassrow",
    blurb: "Clean suit, dirty Rolodex. Investigation is her language.",
    unlockHint: "Jail once, investigation open, or level 2+",
    actions: [
      {
        id: "retain",
        label: "Retain hour",
        blurb: "Cheaper lawyer: drop investigation one stage ($1200 clean).",
        cleanCost: 1200,
      },
      {
        id: "cool_case",
        label: "Cool the case",
        blurb: "Spend favor + $800 clean to drop two stages.",
        favorCost: 2,
        cleanCost: 800,
      },
    ],
  },
  {
    id: "kilo",
    name: "Kilo",
    role: "Pier tipster",
    homeDistrict: "docksreach",
    blurb: "Whistles when containers move. Harbor windows are his product.",
    unlockHint: "Visit DocksReach",
    actions: [
      {
        id: "tip",
        label: "Buy pier tip",
        blurb: "+heavy odds for 4h (harbor window). Costs street cash.",
        streetCost: 350,
      },
      {
        id: "ping",
        label: "Radio check",
        blurb: "Soft heat bleed if you’re near the water.",
      },
    ],
  },
  {
    id: "ivy",
    name: "Ivy Chen",
    role: "Campus voice",
    homeDistrict: "millstone",
    blurb: "Advisor who notices when your schedule and your heat don’t match.",
    unlockHint: "Enroll or finish a course",
    actions: [
      {
        id: "office_hours",
        label: "Office hours",
        blurb: "−stress, +happy. Study nerves settle.",
      },
      {
        id: "ping",
        label: "Heat warning",
        blurb: "If heat is high, she talks you down (−heat soft).",
      },
    ],
  },
  {
    id: "nix",
    name: "Nix",
    role: "Alley broker",
    homeDistrict: "millstone",
    blurb: "Sells timing, not tools. Tips expire when the street forgets.",
    unlockHint: "5+ crime attempts",
    actions: [
      {
        id: "tip",
        label: "Street tip",
        blurb: "+street-family odds for 3h. Street cash.",
        streetCost: 250,
      },
      {
        id: "ask_favor",
        label: "Call marker",
        blurb: "Spend favor: petty odds bump for 2h.",
        favorCost: 1,
      },
    ],
  },
  {
    id: "soot",
    name: "Soot",
    role: "Iron contact",
    homeDistrict: "millstone",
    blurb: "Spotter who knows when your form is lying about your head.",
    unlockHint: "3+ gym sessions",
    actions: [
      {
        id: "walk_off",
        label: "Walk it off",
        blurb: "−stress, +happy. Body reset.",
      },
      {
        id: "ping",
        label: "Spot me",
        blurb: "Tiny favor gain if you’re not fried.",
      },
    ],
  },
];

export function getCrime(id: string) {
  return CRIMES.find((c) => c.id === id);
}
export function getJob(id: string) {
  return JOBS.find((j) => j.id === id);
}
export function getGig(id: string) {
  return GIGS.find((g) => g.id === id);
}
export function getCourse(id: string) {
  return COURSES.find((c) => c.id === id);
}
export function getItem(id: string) {
  return ITEMS.find((i) => i.id === id);
}
export function getDistrict(id: string) {
  return DISTRICTS.find((d) => d.id === id);
}
export function getNpc(id: string) {
  return NPCS.find((n) => n.id === id);
}
export function getProperty(id: string) {
  return PROPERTIES.find((p) => p.id === id);
}
export function getAward(id: string) {
  return AWARDS.find((a) => a.id === id);
}
export function getContact(id: string) {
  return CONTACTS.find((c) => c.id === id);
}
export function npcsInDistrict(district: string) {
  return NPCS.filter((n) => n.district === district);
}
export function propertiesInDistrict(district: string) {
  return PROPERTIES.filter((p) => p.district === district);
}
