import type { CourseDef, LicenseDef } from "@/game/types";

/** AAA course expansion — +24 courses toward 48, same schools. */
export const COURSES_EXTRA: CourseDef[] = [
  {
    id: "se6",
    school: "Street Electives",
    name: "Fence Diplomacy",
    hours: 40,
    fee: 1100,
    stipendPerHour: 42,
    blurb: "Buyers who stay quiet. Unlocks syndicate ledger work.",
    requiresCourse: "se5",
    requiresLevel: 6,
    gigPayBonus: 8,
    oddsBonus: 3,
    oddsFamilies: ["street", "heavy"],
    unlocks: ["syndicate_ledger"],
  },
  {
    id: "se7",
    school: "Street Electives",
    name: "Crowd Work",
    hours: 28,
    fee: 800,
    stipendPerHour: 38,
    blurb: "Move through festivals without leaving a face. Soft petty edges.",
    requiresCourse: "se2",
    requiresLevel: 4,
    oddsBonus: 4,
    oddsFamilies: ["petty"],
    gigPayBonus: 6,
  },
  {
    id: "se8",
    school: "Street Electives",
    name: "Night Circuits",
    hours: 44,
    fee: 1300,
    stipendPerHour: 48,
    blurb: "Routes that cameras forget. Street and heavy exits.",
    requiresCourse: "se6",
    requiresLevel: 7,
    oddsBonus: 4,
    oddsFamilies: ["street", "heavy"],
    jobPayBonus: 4,
  },
  {
    id: "se9",
    school: "Street Electives",
    name: "Crew Logistics",
    hours: 48,
    fee: 1600,
    stipendPerHour: 55,
    blurb: "Who carries what. Soft caps on street heat via better exits.",
    requiresCourse: "se8",
    requiresLevel: 8,
    oddsBonus: 3,
    oddsFamilies: ["street"],
    gigPayBonus: 10,
    jobPayBonus: 5,
  },
  {
    id: "cf5",
    school: "Commerce & Finance",
    name: "Offshore Paper",
    hours: 42,
    fee: 1800,
    stipendPerHour: 62,
    blurb: "Shells that float. Unlocks city vault and bond warehouse fraud.",
    requiresCourse: "cf4",
    requiresLevel: 8,
    jobPayBonus: 6,
    bankInterestBonus: 0.75,
    oddsBonus: 3,
    oddsFamilies: ["heavy"],
    unlocks: ["city_vault", "bond_warehouse"],
  },
  {
    id: "cf6",
    school: "Commerce & Finance",
    name: "Casino Math",
    hours: 36,
    fee: 1500,
    stipendPerHour: 58,
    blurb: "Counts that don't count. Cage and count-room edges.",
    requiresCourse: "cf2",
    requiresLevel: 6,
    jobPayBonus: 5,
    oddsBonus: 4,
    oddsFamilies: ["heavy"],
    unlocks: ["casino_count", "casino_armored", "armored_depot"],
  },
  {
    id: "cf7",
    school: "Commerce & Finance",
    name: "Lobby Law",
    hours: 40,
    fee: 1700,
    stipendPerHour: 60,
    blurb: "Civic doors that open for the right stamp. Mayor's safe work.",
    requiresCourse: "cf3",
    requiresLevel: 7,
    jobPayBonus: 4,
    oddsBonus: 3,
    oddsFamilies: ["heavy"],
    unlocks: ["mayor_safe", "embassy_bag"],
  },
  {
    id: "cf8",
    school: "Commerce & Finance",
    name: "Kingpin Accounting",
    hours: 52,
    fee: 2200,
    stipendPerHour: 70,
    blurb: "Books that own the city. Interest and legitimacy climb.",
    requiresCourse: "cf5",
    requiresLevel: 9,
    jobPayBonus: 8,
    bankInterestBonus: 1,
    oddsBonus: 2,
    oddsFamilies: ["heavy"],
  },
  {
    id: "hl5",
    school: "Harbor & Logistics",
    name: "Crane Certification",
    hours: 36,
    fee: 1400,
    stipendPerHour: 55,
    blurb: "Cab keys and night lifts. Unlocks port crane heists.",
    requiresCourse: "hl2",
    requiresLevel: 6,
    jobPayBonus: 8,
    oddsBonus: 4,
    oddsFamilies: ["heavy"],
    unlocks: ["port_crane", "rail_mail", "harbor_customs"],
  },
  {
    id: "hl6",
    school: "Harbor & Logistics",
    name: "Bonded Freight",
    hours: 44,
    fee: 1700,
    stipendPerHour: 60,
    blurb: "Customs grammar. Airport vaults and arms barges.",
    requiresCourse: "hl3",
    requiresLevel: 8,
    jobPayBonus: 10,
    oddsBonus: 4,
    oddsFamilies: ["heavy"],
    unlocks: ["airport_vault", "arms_barge", "rail_arms"],
  },
  {
    id: "hl7",
    school: "Harbor & Logistics",
    name: "Night Yard Command",
    hours: 48,
    fee: 1900,
    stipendPerHour: 65,
    blurb: "Whistle authority after dark. Heavy dock odds.",
    requiresCourse: "hl5",
    requiresLevel: 8,
    jobPayBonus: 10,
    oddsBonus: 3,
    oddsFamilies: ["heavy"],
  },
  {
    id: "hl8",
    school: "Harbor & Logistics",
    name: "Global Manifests",
    hours: 56,
    fee: 2400,
    stipendPerHour: 72,
    blurb: "Bay numbers that exist on three continents. Apex dock pay.",
    requiresCourse: "hl6",
    requiresLevel: 9,
    jobPayBonus: 12,
    oddsBonus: 3,
    oddsFamilies: ["heavy"],
  },
  {
    id: "mc5",
    school: "Med & Civic",
    name: "Pharma Chain",
    hours: 36,
    fee: 1100,
    stipendPerHour: 48,
    blurb: "Fridge codes and narc cages. Clinic heavy work.",
    requiresCourse: "mc2",
    requiresLevel: 6,
    hospitalTimeReduction: 8,
    oddsBonus: 4,
    oddsFamilies: ["street", "heavy"],
    unlocks: ["clinic_narc", "pharma_warehouse", "blood_bank"],
  },
  {
    id: "mc6",
    school: "Med & Civic",
    name: "Trauma Command",
    hours: 40,
    fee: 1300,
    stipendPerHour: 50,
    blurb: "Ward overflow as cover. Lab isolator paths.",
    requiresCourse: "mc4",
    requiresLevel: 6,
    hospitalTimeReduction: 10,
    jobPayBonus: 4,
    unlocks: ["lab_isolator", "hospital_mri"],
  },
  {
    id: "mc7",
    school: "Med & Civic",
    name: "Civic Shield",
    hours: 32,
    fee: 1000,
    stipendPerHour: 45,
    blurb: "Know-your-rights advanced. Soft street odds under pressure.",
    requiresCourse: "mc3",
    requiresLevel: 5,
    gigPayBonus: 8,
    oddsBonus: 3,
    oddsFamilies: ["street"],
    jobPayBonus: 3,
  },
  {
    id: "mc8",
    school: "Med & Civic",
    name: "Ward Architecture",
    hours: 48,
    fee: 1600,
    stipendPerHour: 55,
    blurb: "Badge paths that own the wing. Hospital clocks soften.",
    requiresCourse: "mc5",
    requiresLevel: 8,
    hospitalTimeReduction: 12,
    jobPayBonus: 5,
    oddsBonus: 3,
    oddsFamilies: ["heavy"],
  },
  {
    id: "le4",
    school: "Locks & Entry",
    name: "High-Security Pins",
    hours: 40,
    fee: 1400,
    stipendPerHour: 52,
    blurb: "Pins that fight back. Yacht and pier vault work.",
    requiresCourse: "le2",
    requiresLevel: 6,
    oddsBonus: 4,
    oddsFamilies: ["street", "heavy"],
    jobPayBonus: 4,
    unlocks: ["yacht_safe", "pier_vault", "pawn_safe"],
  },
  {
    id: "le5",
    school: "Locks & Entry",
    name: "Museum Glass",
    hours: 44,
    fee: 1600,
    stipendPerHour: 55,
    blurb: "Vibrations and silent drills. Museum vault specialty.",
    requiresCourse: "le3",
    requiresLevel: 7,
    oddsBonus: 5,
    oddsFamilies: ["heavy"],
    jobPayBonus: 5,
    unlocks: ["museum_vault", "spire_pent"],
  },
  {
    id: "le6",
    school: "Locks & Entry",
    name: "Bank Dial Lab",
    hours: 48,
    fee: 1900,
    stipendPerHour: 60,
    blurb: "Deposit boxes that breathe. Bank night work.",
    requiresCourse: "le5",
    requiresLevel: 8,
    oddsBonus: 4,
    oddsFamilies: ["heavy"],
    jobPayBonus: 6,
    unlocks: ["bank_night"],
  },
  {
    id: "le7",
    school: "Locks & Entry",
    name: "Master Entry Theory",
    hours: 56,
    fee: 2300,
    stipendPerHour: 68,
    blurb: "Every dial tells a story. Apex vault odds.",
    requiresCourse: "le6",
    requiresLevel: 9,
    oddsBonus: 3,
    oddsFamilies: ["heavy"],
    jobPayBonus: 6,
  },
  {
    id: "sy5",
    school: "Systems & Signals",
    name: "Skimmer Craft",
    hours: 32,
    fee: 1000,
    stipendPerHour: 45,
    blurb: "Plastic that listens. ATM and wire work.",
    requiresCourse: "sy1",
    requiresLevel: 4,
    oddsBonus: 4,
    oddsFamilies: ["street"],
    unlocks: ["atm_skimmer", "wire_tap", "dock_radio"],
  },
  {
    id: "sy6",
    school: "Systems & Signals",
    name: "Server Closets",
    hours: 40,
    fee: 1400,
    stipendPerHour: 52,
    blurb: "Where the city stores its secrets. Office server edges.",
    requiresCourse: "sy2",
    requiresLevel: 5,
    oddsBonus: 4,
    oddsFamilies: ["street", "heavy"],
    unlocks: ["office_server", "data_center", "telecom_hub"],
  },
  {
    id: "sy7",
    school: "Systems & Signals",
    name: "Federal Mesh",
    hours: 48,
    fee: 1900,
    stipendPerHour: 62,
    blurb: "Dead drops that survive audits. Federal drop box work.",
    requiresCourse: "sy3",
    requiresLevel: 8,
    oddsBonus: 4,
    oddsFamilies: ["heavy"],
    unlocks: ["federal_drop"],
  },
  {
    id: "sy8",
    school: "Systems & Signals",
    name: "Nightwire Protocol",
    hours: 56,
    fee: 2500,
    stipendPerHour: 75,
    blurb: "Own the exchange. Apex signal ops.",
    requiresCourse: "sy4",
    requiresLevel: 9,
    oddsBonus: 3,
    oddsFamilies: ["street", "heavy"],
    jobPayBonus: 6,
    unlocks: ["wire_exchange"],
  },
];

export const LICENSES_EXTRA: LicenseDef[] = [
  { id: "fence_diplomacy", name: "Fence Diplomacy Pass", courseId: "se6", blurb: "Buyers who stay quiet on paper.", oddsBonus: 2, oddsFamilies: ["street", "heavy"], legitimacyGain: 2, weeklyStipend: 35 },
  { id: "crowd_work", name: "Crowd Work Cert", courseId: "se7", blurb: "Festival faces that don't stick.", oddsBonus: 2, oddsFamilies: ["petty"], legitimacyGain: 2, weeklyStipend: 28 },
  { id: "night_circuits", name: "Night Circuits Card", courseId: "se8", blurb: "Routes cameras forget.", oddsBonus: 2, oddsFamilies: ["street", "heavy"], jobPayBonus: 2, legitimacyGain: 3, weeklyStipend: 40 },
  { id: "crew_logistics", name: "Crew Logistics Seal", courseId: "se9", blurb: "Who carries what — stamped civic.", oddsBonus: 2, oddsFamilies: ["street"], jobPayBonus: 3, legitimacyGain: 3, weeklyStipend: 48 },
  { id: "offshore_paper", name: "Offshore Paper Seal", courseId: "cf5", blurb: "Shells that float legally enough.", jobPayBonus: 4, bankInterestBonus: 0.5, legitimacyGain: 5, weeklyStipend: 80 },
  { id: "casino_math", name: "Casino Math Cert", courseId: "cf6", blurb: "Counts that don't count.", jobPayBonus: 3, oddsBonus: 2, oddsFamilies: ["heavy"], legitimacyGain: 3, weeklyStipend: 55 },
  { id: "lobby_law", name: "Lobby Law Card", courseId: "cf7", blurb: "Civic doors for the right stamp.", jobPayBonus: 3, oddsBonus: 2, oddsFamilies: ["heavy"], legitimacyGain: 4, weeklyStipend: 60 },
  { id: "kingpin_accounting", name: "Kingpin Accounting License", courseId: "cf8", blurb: "Books that own the city.", jobPayBonus: 5, bankInterestBonus: 0.75, legitimacyGain: 6, weeklyStipend: 90 },
  { id: "crane_cert", name: "Crane Certification", courseId: "hl5", blurb: "Cab keys on a civic card.", jobPayBonus: 5, oddsBonus: 2, oddsFamilies: ["heavy"], legitimacyGain: 3, weeklyStipend: 50 },
  { id: "bonded_freight", name: "Bonded Freight Seal", courseId: "hl6", blurb: "Customs grammar stamped.", jobPayBonus: 6, oddsBonus: 3, oddsFamilies: ["heavy"], legitimacyGain: 4, weeklyStipend: 65 },
  { id: "night_yard", name: "Night Yard Command", courseId: "hl7", blurb: "Whistle authority after dark.", jobPayBonus: 6, oddsBonus: 2, oddsFamilies: ["heavy"], legitimacyGain: 4, weeklyStipend: 70 },
  { id: "global_manifest", name: "Global Manifest License", courseId: "hl8", blurb: "Bay numbers across oceans.", jobPayBonus: 8, oddsBonus: 2, oddsFamilies: ["heavy"], legitimacyGain: 5, weeklyStipend: 85 },
  { id: "pharma_chain", name: "Pharma Chain Cert", courseId: "mc5", blurb: "Fridge codes that look medical.", hospitalTimeReduction: 5, oddsBonus: 2, oddsFamilies: ["street", "heavy"], legitimacyGain: 3, weeklyStipend: 45 },
  { id: "trauma_command", name: "Trauma Command Seal", courseId: "mc6", blurb: "Ward overflow as cover.", hospitalTimeReduction: 6, jobPayBonus: 2, legitimacyGain: 4, weeklyStipend: 48 },
  { id: "civic_shield", name: "Civic Shield Card", courseId: "mc7", blurb: "Advanced rights ink.", oddsBonus: 2, oddsFamilies: ["street"], jobPayBonus: 2, legitimacyGain: 5, weeklyStipend: 40 },
  { id: "ward_architecture", name: "Ward Architecture License", courseId: "mc8", blurb: "Badge paths that own the wing.", hospitalTimeReduction: 8, jobPayBonus: 3, oddsBonus: 2, oddsFamilies: ["heavy"], legitimacyGain: 4, weeklyStipend: 55 },
  { id: "high_sec_pins", name: "High-Security Pins Endorsement", courseId: "le4", blurb: "Pins that fight back — stamped.", oddsBonus: 2, oddsFamilies: ["street", "heavy"], jobPayBonus: 3, legitimacyGain: 3, weeklyStipend: 48 },
  { id: "museum_glass", name: "Museum Glass Endorsement", courseId: "le5", blurb: "Silent drill paper.", oddsBonus: 3, oddsFamilies: ["heavy"], jobPayBonus: 3, legitimacyGain: 4, weeklyStipend: 55 },
  { id: "bank_dial", name: "Bank Dial Lab Seal", courseId: "le6", blurb: "Deposit boxes that breathe.", oddsBonus: 3, oddsFamilies: ["heavy"], jobPayBonus: 4, legitimacyGain: 4, weeklyStipend: 60 },
  { id: "master_entry", name: "Master Entry License", courseId: "le7", blurb: "Every dial tells a story.", oddsBonus: 2, oddsFamilies: ["heavy"], jobPayBonus: 4, legitimacyGain: 5, weeklyStipend: 70 },
  { id: "skimmer_craft", name: "Skimmer Craft Card", courseId: "sy5", blurb: "Plastic that listens.", oddsBonus: 2, oddsFamilies: ["street"], legitimacyGain: 2, weeklyStipend: 38 },
  { id: "server_closets", name: "Server Closets Cert", courseId: "sy6", blurb: "Where secrets sleep.", oddsBonus: 2, oddsFamilies: ["street", "heavy"], legitimacyGain: 3, weeklyStipend: 48 },
  { id: "federal_mesh", name: "Federal Mesh Seal", courseId: "sy7", blurb: "Dead drops that survive audits.", oddsBonus: 3, oddsFamilies: ["heavy"], legitimacyGain: 4, weeklyStipend: 58 },
  { id: "nightwire_protocol", name: "Nightwire Protocol License", courseId: "sy8", blurb: "Own the exchange on paper.", oddsBonus: 2, oddsFamilies: ["street", "heavy"], jobPayBonus: 4, legitimacyGain: 5, weeklyStipend: 75 },
];
