import type { HeistDef } from "@/game/types";

/**
 * V2 organized heist boards — vertical slice of 8 (path toward 24).
 * Each board is multi-step: Intel → Crew → Kit → Window → Execute.
 * Original Nightwire ops only — not Torn clones.
 */
export const HEISTS: HeistDef[] = [
  {
    id: "tram_skim",
    name: "Tram Line Skim",
    blurb: "Three seats, one bagman, a short window between stops. Entry organized board.",
    district: "glassrow",
    risk: "moderate",
    requiresLevel: 2,
    payoutMin: 2800,
    payoutMax: 5200,
    xp: 80,
    heatOnSuccess: 12,
    heatOnFail: 18,
    cooldownHours: 4,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Watch the line",
        blurb: "Count cameras and which cars the inspectors skip.",
        energy: 4,
        streetCost: 200,
        successChance: 0.82,
        heatOnFail: 4,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire lookout",
        blurb: "A quiet pair of eyes at the platform.",
        energy: 2,
        streetCost: 600,
        successChance: 0.88,
        heatOnFail: 3,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage gloves",
        blurb: "Commit grip gloves to the board.",
        energy: 1,
        requireItems: [{ itemId: "gloves", qty: 1 }],
        successChance: 0.95,
        heatOnFail: 2,
      },
      {
        id: "window",
        kind: "window",
        name: "Catch the window",
        blurb: "Be in Glassrow. Night hours tighten the odds.",
        nerve: 2,
        successChance: 0.9,
        heatOnFail: 5,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Pull the skim",
        blurb: "Approach → lift → peel off. Abort or sacrifice mid-run.",
        nerve: 5,
      },
    ],
  },
  {
    id: "yard_boost",
    name: "Yard Boost Ring",
    blurb: "Millstone lot after shift. Crowbar crew, three cars, one fence.",
    district: "millstone",
    risk: "moderate",
    requiresLevel: 3,
    payoutMin: 4200,
    payoutMax: 7800,
    xp: 110,
    heatOnSuccess: 16,
    heatOnFail: 22,
    cooldownHours: 5,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Mark the lot",
        blurb: "Which cameras still work after rain.",
        energy: 5,
        streetCost: 350,
        successChance: 0.8,
        heatOnFail: 5,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire muscle",
        blurb: "Someone who can hold a door without talking.",
        energy: 3,
        streetCost: 900,
        successChance: 0.85,
        heatOnFail: 4,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage crowbar",
        blurb: "Commit a crowbar to the board.",
        energy: 1,
        requireItems: [{ itemId: "crowbar", qty: 1 }],
        successChance: 0.94,
        heatOnFail: 2,
      },
      {
        id: "window",
        kind: "window",
        name: "Shift change gap",
        blurb: "Stand in Millstone when the yard goes soft.",
        nerve: 3,
        successChance: 0.88,
        heatOnFail: 6,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Run the boost",
        blurb: "Approach → breach → fence drop.",
        nerve: 6,
      },
    ],
  },
  {
    id: "commons_sweep",
    name: "Commons Night Sweep",
    blurb: "OldCommons block party cover. Four corners, one bag.",
    district: "oldcommons",
    risk: "moderate",
    requiresLevel: 3,
    payoutMin: 3600,
    payoutMax: 7000,
    xp: 100,
    heatOnSuccess: 14,
    heatOnFail: 20,
    cooldownHours: 4,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Walk the corners",
        blurb: "Map which stoops talk to uniforms.",
        energy: 4,
        streetCost: 250,
        successChance: 0.83,
        heatOnFail: 4,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire runner",
        blurb: "Fast feet, no questions.",
        energy: 2,
        streetCost: 700,
        successChance: 0.86,
        heatOnFail: 4,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage radio",
        blurb: "Scanner on the board for sweep calls.",
        energy: 1,
        requireItems: [{ itemId: "radio", qty: 1 }],
        successChance: 0.93,
        heatOnFail: 2,
      },
      {
        id: "window",
        kind: "window",
        name: "Party cover",
        blurb: "Be in OldCommons. Night is kinder.",
        nerve: 2,
        successChance: 0.9,
        heatOnFail: 5,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Sweep the block",
        blurb: "Approach → bag → vanish into noise.",
        nerve: 5,
      },
    ],
  },
  {
    id: "bay_pierce",
    name: "Bay Pierce",
    blurb: "DocksReach side bay. One crate, one pier boss looking the other way.",
    district: "docksreach",
    risk: "high",
    requiresLevel: 4,
    requiresCourse: "hl1",
    payoutMin: 9000,
    payoutMax: 16000,
    xp: 160,
    heatOnSuccess: 22,
    heatOnFail: 30,
    cooldownHours: 8,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Manifest skim",
        blurb: "Which crate never made the sheet.",
        energy: 6,
        streetCost: 800,
        successChance: 0.75,
        heatOnFail: 7,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire dock hand",
        blurb: "Someone with a yard pass that still scans.",
        energy: 4,
        streetCost: 1800,
        successChance: 0.8,
        heatOnFail: 6,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage harbor key",
        blurb: "Commit a harbor keycard.",
        energy: 2,
        requireItems: [{ itemId: "harbor_key", qty: 1 }],
        successChance: 0.9,
        heatOnFail: 4,
      },
      {
        id: "window",
        kind: "window",
        name: "Tide gap",
        blurb: "Stand in DocksReach when the radios go soft.",
        nerve: 4,
        successChance: 0.84,
        heatOnFail: 8,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Pierce the bay",
        blurb: "Approach → cut → extract.",
        nerve: 8,
      },
    ],
  },
  {
    id: "ward_diversion",
    name: "Ward Diversion",
    blurb: "Ashcourt clinic overflow. Diversion upstairs, lift downstairs.",
    district: "ashcourt",
    risk: "high",
    requiresLevel: 4,
    requiresCourse: "se2",
    payoutMin: 7500,
    payoutMax: 14000,
    xp: 150,
    heatOnSuccess: 20,
    heatOnFail: 28,
    cooldownHours: 7,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Chart the ward",
        blurb: "Which doors blink after shift.",
        energy: 5,
        streetCost: 600,
        successChance: 0.78,
        heatOnFail: 6,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire orderly tip",
        blurb: "Someone who knows when the cameras nap.",
        energy: 3,
        streetCost: 1400,
        successChance: 0.82,
        heatOnFail: 5,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage badge blank",
        blurb: "Warm ink for a soft door.",
        energy: 2,
        requireItems: [{ itemId: "badge_blank", qty: 1 }],
        successChance: 0.9,
        heatOnFail: 3,
      },
      {
        id: "window",
        kind: "window",
        name: "Overflow hour",
        blurb: "Be in Ashcourt when the ward is loud.",
        nerve: 3,
        successChance: 0.85,
        heatOnFail: 7,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Run the diversion",
        blurb: "Approach → door → pharmacy skim.",
        nerve: 7,
      },
    ],
  },
  {
    id: "spire_float",
    name: "Spire Float",
    blurb: "SpireYard courier desk float. Paper that looks like payroll.",
    district: "spireyard",
    risk: "high",
    requiresLevel: 5,
    requiresCourse: "cf1",
    payoutMin: 11000,
    payoutMax: 19000,
    xp: 180,
    heatOnSuccess: 24,
    heatOnFail: 32,
    cooldownHours: 8,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Desk schedule",
        blurb: "Who leaves the float drawer cracked.",
        energy: 6,
        streetCost: 1000,
        cleanCost: 400,
        successChance: 0.74,
        heatOnFail: 8,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire clerk ghost",
        blurb: "A face that belongs near the mail room.",
        energy: 4,
        streetCost: 2200,
        successChance: 0.78,
        heatOnFail: 7,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage lockpick",
        blurb: "Quiet drawer work.",
        energy: 2,
        requireItems: [{ itemId: "lockpick", qty: 1 }],
        successChance: 0.88,
        heatOnFail: 4,
      },
      {
        id: "window",
        kind: "window",
        name: "Lunch float",
        blurb: "Be in SpireYard when the desk empties.",
        nerve: 4,
        successChance: 0.82,
        heatOnFail: 9,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Lift the float",
        blurb: "Approach → drawer → exit like payroll.",
        nerve: 8,
      },
    ],
  },
  {
    id: "soft_house_run",
    name: "Soft-House Run",
    blurb: "Harbor Soft-House as staging. Bigger bay pull with a quiet front.",
    district: "docksreach",
    risk: "extreme",
    requiresLevel: 6,
    requiresCourse: "hl1",
    requiresProperty: "dr_safe",
    payoutMin: 18000,
    payoutMax: 32000,
    xp: 240,
    heatOnSuccess: 30,
    heatOnFail: 40,
    cooldownHours: 12,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Soft-house brief",
        blurb: "Plan the route from the quiet front to the bay.",
        energy: 7,
        streetCost: 1500,
        successChance: 0.7,
        heatOnFail: 10,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire full crew",
        blurb: "Driver, cutter, lookout — paid quiet.",
        energy: 5,
        streetCost: 4000,
        successChance: 0.75,
        heatOnFail: 8,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage drill + key",
        blurb: "Quiet drill and harbor key on the board.",
        energy: 3,
        requireItems: [
          { itemId: "drill_bit", qty: 1 },
          { itemId: "harbor_key", qty: 1 },
        ],
        successChance: 0.86,
        heatOnFail: 5,
      },
      {
        id: "window",
        kind: "window",
        name: "Strike window",
        blurb: "Be in DocksReach. Soft-house owned. Night preferred.",
        nerve: 5,
        successChance: 0.78,
        heatOnFail: 12,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Run the soft house",
        blurb: "Approach → pierce → extract to the front.",
        nerve: 10,
      },
    ],
  },
  {
    id: "bond_desk",
    name: "Bond Desk Paper",
    blurb: "City bond office after hours. Commerce paper, heavy heat.",
    district: "spireyard",
    risk: "extreme",
    requiresLevel: 6,
    requiresCourse: "cf2",
    payoutMin: 20000,
    payoutMax: 36000,
    xp: 260,
    heatOnSuccess: 32,
    heatOnFail: 42,
    cooldownHours: 14,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Stamp schedule",
        blurb: "Which clerk leaves the bond drawer warm.",
        energy: 7,
        streetCost: 1200,
        cleanCost: 800,
        successChance: 0.68,
        heatOnFail: 11,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire paper ghost",
        blurb: "Someone who can walk like they belong.",
        energy: 5,
        streetCost: 3500,
        successChance: 0.72,
        heatOnFail: 9,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage badge + drill",
        blurb: "Office face and quiet metal.",
        energy: 3,
        requireItems: [
          { itemId: "badge_blank", qty: 1 },
          { itemId: "drill_bit", qty: 1 },
        ],
        successChance: 0.84,
        heatOnFail: 6,
      },
      {
        id: "window",
        kind: "window",
        name: "After-hours desk",
        blurb: "Be in SpireYard when the bond floor goes dark.",
        nerve: 5,
        successChance: 0.76,
        heatOnFail: 12,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Pull the paper",
        blurb: "Approach → desk → vanish with bonds.",
        nerve: 10,
      },
    ],
  },
];

export function getHeist(id: string) {
  return HEISTS.find((h) => h.id === id);
}
