import type { HeistDef } from "@/game/types";

/**
 * V2 organized heist boards — full set of 24 multi-step ops.
 * Each board: Intel → Crew → Kit → Window → Execute.
 * Original Nightwire ops only — not Torn clones. First 8 IDs stay stable.
 */
export const HEISTS: HeistDef[] = [
  {
    id: "tram_skim",
    name: "Tram Line Skim",
    blurb: "Three seats, one bagman, a short window between stops. Entry organized board.",
    district: "glassrow",
    risk: "moderate",
    requiresLevel: 2,
    payoutMin: 2800,
    payoutMax: 5200,
    xp: 80,
    heatOnSuccess: 12,
    heatOnFail: 18,
    cooldownHours: 4,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Watch the line",
        blurb: "Count cameras and which cars the inspectors skip.",
        energy: 4,
        streetCost: 200,
        successChance: 0.82,
        heatOnFail: 4,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire lookout",
        blurb: "A quiet pair of eyes at the platform.",
        energy: 2,
        streetCost: 600,
        successChance: 0.88,
        heatOnFail: 3,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage gloves",
        blurb: "Commit grip gloves to the board.",
        energy: 1,
        requireItems: [{ itemId: "gloves", qty: 1 }],
        successChance: 0.95,
        heatOnFail: 2,
      },
      {
        id: "window",
        kind: "window",
        name: "Catch the window",
        blurb: "Be in Glassrow. Night hours tighten the odds.",
        nerve: 2,
        successChance: 0.9,
        heatOnFail: 5,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Pull the skim",
        blurb: "Approach → lift → peel off. Abort or sacrifice mid-run.",
        nerve: 5,
      },
    ],
  },
  {
    id: "yard_boost",
    name: "Yard Boost Ring",
    blurb: "Millstone lot after shift. Crowbar crew, three cars, one fence.",
    district: "millstone",
    risk: "moderate",
    requiresLevel: 3,
    payoutMin: 4200,
    payoutMax: 7800,
    xp: 110,
    heatOnSuccess: 16,
    heatOnFail: 22,
    cooldownHours: 5,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Mark the lot",
        blurb: "Which cameras still work after rain.",
        energy: 5,
        streetCost: 350,
        successChance: 0.8,
        heatOnFail: 5,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire muscle",
        blurb: "Someone who can hold a door without talking.",
        energy: 3,
        streetCost: 900,
        successChance: 0.85,
        heatOnFail: 4,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage crowbar",
        blurb: "Commit a crowbar to the board.",
        energy: 1,
        requireItems: [{ itemId: "crowbar", qty: 1 }],
        successChance: 0.94,
        heatOnFail: 2,
      },
      {
        id: "window",
        kind: "window",
        name: "Shift change gap",
        blurb: "Stand in Millstone when the yard goes soft.",
        nerve: 3,
        successChance: 0.88,
        heatOnFail: 6,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Run the boost",
        blurb: "Approach → breach → fence drop.",
        nerve: 6,
      },
    ],
  },
  {
    id: "commons_sweep",
    name: "Commons Night Sweep",
    blurb: "OldCommons block party cover. Four corners, one bag.",
    district: "oldcommons",
    risk: "moderate",
    requiresLevel: 3,
    payoutMin: 3600,
    payoutMax: 7000,
    xp: 100,
    heatOnSuccess: 14,
    heatOnFail: 20,
    cooldownHours: 4,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Walk the corners",
        blurb: "Map which stoops talk to uniforms.",
        energy: 4,
        streetCost: 250,
        successChance: 0.83,
        heatOnFail: 4,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire runner",
        blurb: "Fast feet, no questions.",
        energy: 2,
        streetCost: 700,
        successChance: 0.86,
        heatOnFail: 4,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage radio",
        blurb: "Scanner on the board for sweep calls.",
        energy: 1,
        requireItems: [{ itemId: "radio", qty: 1 }],
        successChance: 0.93,
        heatOnFail: 2,
      },
      {
        id: "window",
        kind: "window",
        name: "Party cover",
        blurb: "Be in OldCommons. Night is kinder.",
        nerve: 2,
        successChance: 0.9,
        heatOnFail: 5,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Sweep the block",
        blurb: "Approach → bag → vanish into noise.",
        nerve: 5,
      },
    ],
  },
  {
    id: "bay_pierce",
    name: "Bay Pierce",
    blurb: "DocksReach side bay. One crate, one pier boss looking the other way.",
    district: "docksreach",
    risk: "high",
    requiresLevel: 4,
    requiresCourse: "hl1",
    payoutMin: 9000,
    payoutMax: 16000,
    xp: 160,
    heatOnSuccess: 22,
    heatOnFail: 30,
    cooldownHours: 8,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Manifest skim",
        blurb: "Which crate never made the sheet.",
        energy: 6,
        streetCost: 800,
        successChance: 0.75,
        heatOnFail: 7,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire dock hand",
        blurb: "Someone with a yard pass that still scans.",
        energy: 4,
        streetCost: 1800,
        successChance: 0.8,
        heatOnFail: 6,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage harbor key",
        blurb: "Commit a harbor keycard.",
        energy: 2,
        requireItems: [{ itemId: "harbor_key", qty: 1 }],
        successChance: 0.9,
        heatOnFail: 4,
      },
      {
        id: "window",
        kind: "window",
        name: "Tide gap",
        blurb: "Stand in DocksReach when the radios go soft.",
        nerve: 4,
        successChance: 0.84,
        heatOnFail: 8,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Pierce the bay",
        blurb: "Approach → cut → extract.",
        nerve: 8,
      },
    ],
  },
  {
    id: "ward_diversion",
    name: "Ward Diversion",
    blurb: "Ashcourt clinic overflow. Diversion upstairs, lift downstairs.",
    district: "ashcourt",
    risk: "high",
    requiresLevel: 4,
    requiresCourse: "mc2",
    payoutMin: 7500,
    payoutMax: 14000,
    xp: 150,
    heatOnSuccess: 20,
    heatOnFail: 28,
    cooldownHours: 7,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Chart the ward",
        blurb: "Which doors blink after shift.",
        energy: 5,
        streetCost: 600,
        successChance: 0.78,
        heatOnFail: 6,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire orderly tip",
        blurb: "Someone who knows when the cameras nap.",
        energy: 3,
        streetCost: 1400,
        successChance: 0.82,
        heatOnFail: 5,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage badge blank",
        blurb: "Warm ink for a soft door.",
        energy: 2,
        requireItems: [{ itemId: "badge_blank", qty: 1 }],
        successChance: 0.9,
        heatOnFail: 3,
      },
      {
        id: "window",
        kind: "window",
        name: "Overflow hour",
        blurb: "Be in Ashcourt when the ward is loud.",
        nerve: 3,
        successChance: 0.85,
        heatOnFail: 7,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Run the diversion",
        blurb: "Approach → door → pharmacy skim.",
        nerve: 7,
      },
    ],
  },
  {
    id: "spire_float",
    name: "Spire Float",
    blurb: "SpireYard courier desk float. Paper that looks like payroll.",
    district: "spireyard",
    risk: "high",
    requiresLevel: 5,
    requiresCourse: "cf1",
    payoutMin: 11000,
    payoutMax: 19000,
    xp: 180,
    heatOnSuccess: 24,
    heatOnFail: 32,
    cooldownHours: 8,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Desk schedule",
        blurb: "Who leaves the float drawer cracked.",
        energy: 6,
        streetCost: 1000,
        cleanCost: 400,
        successChance: 0.74,
        heatOnFail: 8,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire clerk ghost",
        blurb: "A face that belongs near the mail room.",
        energy: 4,
        streetCost: 2200,
        successChance: 0.78,
        heatOnFail: 7,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage lockpick",
        blurb: "Quiet drawer work.",
        energy: 2,
        requireItems: [{ itemId: "lockpick", qty: 1 }],
        successChance: 0.88,
        heatOnFail: 4,
      },
      {
        id: "window",
        kind: "window",
        name: "Lunch float",
        blurb: "Be in SpireYard when the desk empties.",
        nerve: 4,
        successChance: 0.82,
        heatOnFail: 9,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Lift the float",
        blurb: "Approach → drawer → exit like payroll.",
        nerve: 8,
      },
    ],
  },
  {
    id: "soft_house_run",
    name: "Soft-House Run",
    blurb: "Harbor Soft-House as staging. Bigger bay pull with a quiet front.",
    district: "docksreach",
    risk: "extreme",
    requiresLevel: 6,
    requiresCourse: "hl1",
    requiresProperty: "dr_safe",
    payoutMin: 18000,
    payoutMax: 32000,
    xp: 240,
    heatOnSuccess: 30,
    heatOnFail: 40,
    cooldownHours: 12,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Soft-house brief",
        blurb: "Plan the route from the quiet front to the bay.",
        energy: 7,
        streetCost: 1500,
        successChance: 0.7,
        heatOnFail: 10,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire full crew",
        blurb: "Driver, cutter, lookout — paid quiet.",
        energy: 5,
        streetCost: 4000,
        successChance: 0.75,
        heatOnFail: 8,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage drill + key",
        blurb: "Quiet drill and harbor key on the board.",
        energy: 3,
        requireItems: [
          { itemId: "drill_bit", qty: 1 },
          { itemId: "harbor_key", qty: 1 },
        ],
        successChance: 0.86,
        heatOnFail: 5,
      },
      {
        id: "window",
        kind: "window",
        name: "Strike window",
        blurb: "Be in DocksReach. Soft-house owned. Night preferred.",
        nerve: 5,
        successChance: 0.78,
        heatOnFail: 12,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Run the soft house",
        blurb: "Approach → pierce → extract to the front.",
        nerve: 10,
      },
    ],
  },
  {
    id: "bond_desk",
    name: "Bond Desk Paper",
    blurb: "City bond office after hours. Commerce paper, heavy heat.",
    district: "spireyard",
    risk: "extreme",
    requiresLevel: 6,
    requiresCourse: "cf2",
    payoutMin: 20000,
    payoutMax: 36000,
    xp: 260,
    heatOnSuccess: 32,
    heatOnFail: 42,
    cooldownHours: 14,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Stamp schedule",
        blurb: "Which clerk leaves the bond drawer warm.",
        energy: 7,
        streetCost: 1200,
        cleanCost: 800,
        successChance: 0.68,
        heatOnFail: 11,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire paper ghost",
        blurb: "Someone who can walk like they belong.",
        energy: 5,
        streetCost: 3500,
        successChance: 0.72,
        heatOnFail: 9,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage badge + drill",
        blurb: "Office face and quiet metal.",
        energy: 3,
        requireItems: [
          { itemId: "badge_blank", qty: 1 },
          { itemId: "drill_bit", qty: 1 },
        ],
        successChance: 0.84,
        heatOnFail: 6,
      },
      {
        id: "window",
        kind: "window",
        name: "After-hours desk",
        blurb: "Be in SpireYard when the bond floor goes dark.",
        nerve: 5,
        successChance: 0.76,
        heatOnFail: 12,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Pull the paper",
        blurb: "Approach → desk → vanish with bonds.",
        nerve: 10,
      },
    ],
  },

  // —— +16 toward full V2 set of 24 ——

  {
    id: "neon_till",
    name: "Neon Till Close",
    blurb: "Glassrow floor close. Shift Lead cover, till that never quite balances.",
    district: "glassrow",
    risk: "moderate",
    requiresLevel: 3,
    requiresJob: "retail_2",
    payoutMin: 3800,
    payoutMax: 7200,
    xp: 105,
    heatOnSuccess: 13,
    heatOnFail: 19,
    cooldownHours: 5,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Watch closeout",
        blurb: "Which till gets counted twice — and which never does.",
        energy: 4,
        streetCost: 280,
        successChance: 0.84,
        heatOnFail: 4,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire bag runner",
        blurb: "Someone who can exit like a vendor.",
        energy: 2,
        streetCost: 750,
        successChance: 0.87,
        heatOnFail: 3,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage gloves",
        blurb: "No prints on the till tray.",
        energy: 1,
        requireItems: [{ itemId: "gloves", qty: 1 }],
        successChance: 0.95,
        heatOnFail: 2,
      },
      {
        id: "window",
        kind: "window",
        name: "Lights-out count",
        blurb: "Be in Glassrow when neon kills the floor lights.",
        nerve: 2,
        successChance: 0.9,
        heatOnFail: 5,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Skim the till",
        blurb: "Approach → tray → exit with shrinkage cover.",
        nerve: 5,
      },
    ],
  },
  {
    id: "gallery_wire",
    name: "Gallery Wire Night",
    blurb: "Afterparty wire along the Glassrow gallery mezzanine. Commerce face required.",
    district: "glassrow",
    risk: "high",
    requiresLevel: 5,
    requiresCourse: "cf1",
    payoutMin: 9500,
    payoutMax: 17000,
    xp: 170,
    heatOnSuccess: 22,
    heatOnFail: 30,
    cooldownHours: 8,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Map the mezz",
        blurb: "Which cameras watch the wire, which watch the bar.",
        energy: 6,
        streetCost: 900,
        cleanCost: 300,
        successChance: 0.76,
        heatOnFail: 7,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire society face",
        blurb: "Someone who looks like a donor, not a lifter.",
        energy: 4,
        streetCost: 2000,
        successChance: 0.8,
        heatOnFail: 6,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage shim kit",
        blurb: "Quiet case work behind velvet.",
        energy: 2,
        requireItems: [{ itemId: "shim_kit", qty: 1 }],
        successChance: 0.9,
        heatOnFail: 4,
      },
      {
        id: "window",
        kind: "window",
        name: "Toast cover",
        blurb: "Be in Glassrow when the gallery toast goes loud.",
        nerve: 4,
        successChance: 0.84,
        heatOnFail: 8,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Pull the wire",
        blurb: "Approach → case → vanish into donors.",
        nerve: 8,
      },
    ],
  },
  {
    id: "loft_mail",
    name: "Loft Mail Relay",
    blurb: "Neon Loft Share as clean address. Relay warm packages through legitimate mail.",
    district: "glassrow",
    risk: "high",
    requiresLevel: 5,
    requiresProperty: "gr_loft",
    payoutMin: 10000,
    payoutMax: 18000,
    xp: 175,
    heatOnSuccess: 21,
    heatOnFail: 29,
    cooldownHours: 9,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Carrier route",
        blurb: "Which drop never gets scanned twice.",
        energy: 5,
        streetCost: 700,
        successChance: 0.78,
        heatOnFail: 6,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire mail ghost",
        blurb: "A face that belongs in the lobby.",
        energy: 3,
        streetCost: 1600,
        successChance: 0.82,
        heatOnFail: 5,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage courier bag",
        blurb: "Looks legit. Isn’t.",
        energy: 2,
        requireItems: [{ itemId: "courier_bag", qty: 1 }],
        successChance: 0.92,
        heatOnFail: 3,
      },
      {
        id: "window",
        kind: "window",
        name: "Morning drop",
        blurb: "Be in Glassrow when the loft mailroom opens soft.",
        nerve: 3,
        successChance: 0.86,
        heatOnFail: 7,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Run the relay",
        blurb: "Approach → swap → exit with clean stamps.",
        nerve: 7,
      },
    ],
  },
  {
    id: "pallet_ghost",
    name: "Pallet Ghost",
    blurb: "Millstone warehouse mislabel. One pallet that never existed on the sheet.",
    district: "millstone",
    risk: "moderate",
    requiresLevel: 3,
    requiresJob: "warehouse_1",
    payoutMin: 4500,
    payoutMax: 8500,
    xp: 115,
    heatOnSuccess: 15,
    heatOnFail: 21,
    cooldownHours: 5,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Scanner blind",
        blurb: "Which aisle the night tech skips.",
        energy: 5,
        streetCost: 400,
        successChance: 0.81,
        heatOnFail: 5,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire forklift tip",
        blurb: "Someone who can move weight without a radio call.",
        energy: 3,
        streetCost: 1000,
        successChance: 0.85,
        heatOnFail: 4,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage crowbar",
        blurb: "Pallet wrap and stubborn seals.",
        energy: 1,
        requireItems: [{ itemId: "crowbar", qty: 1 }],
        successChance: 0.94,
        heatOnFail: 2,
      },
      {
        id: "window",
        kind: "window",
        name: "Night count gap",
        blurb: "Stand in Millstone when inventory goes soft.",
        nerve: 3,
        successChance: 0.88,
        heatOnFail: 6,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Ghost the pallet",
        blurb: "Approach → mislabel → fence drop.",
        nerve: 6,
      },
    ],
  },
  {
    id: "substation_siphon",
    name: "Substation Siphon",
    blurb: "Millstone copper after the rain shorts the cameras. City Navigation required.",
    district: "millstone",
    risk: "high",
    requiresLevel: 5,
    requiresCourse: "se1",
    payoutMin: 11000,
    payoutMax: 19500,
    xp: 185,
    heatOnSuccess: 25,
    heatOnFail: 34,
    cooldownHours: 9,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Fence map",
        blurb: "Which gate still takes a shim after the storm.",
        energy: 6,
        streetCost: 850,
        successChance: 0.74,
        heatOnFail: 8,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire cutter",
        blurb: "Quiet copper hands, no chatter.",
        energy: 4,
        streetCost: 2100,
        successChance: 0.78,
        heatOnFail: 7,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage radio + gloves",
        blurb: "Hear sweeps; leave fewer prints.",
        energy: 2,
        requireItems: [
          { itemId: "radio", qty: 1 },
          { itemId: "gloves", qty: 1 },
        ],
        successChance: 0.9,
        heatOnFail: 4,
      },
      {
        id: "window",
        kind: "window",
        name: "Storm blackout",
        blurb: "Be in Millstone when the substation blinks.",
        nerve: 4,
        successChance: 0.82,
        heatOnFail: 9,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Siphon the copper",
        blurb: "Approach → cut → extract heavy.",
        nerve: 8,
      },
    ],
  },
  {
    id: "chop_lane",
    name: "Chop Lane Overnight",
    blurb: "Yard Shed staging. Three cars into parts before dawn.",
    district: "millstone",
    risk: "extreme",
    requiresLevel: 6,
    requiresProperty: "ms_shed",
    payoutMin: 17000,
    payoutMax: 30000,
    xp: 235,
    heatOnSuccess: 30,
    heatOnFail: 40,
    cooldownHours: 12,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Lane schedule",
        blurb: "Which patrol skips the shed alley.",
        energy: 7,
        streetCost: 1400,
        successChance: 0.7,
        heatOnFail: 10,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire chop crew",
        blurb: "Cutter, driver, fence — paid quiet.",
        energy: 5,
        streetCost: 3800,
        successChance: 0.74,
        heatOnFail: 8,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage crowbar + drill",
        blurb: "Doors and VIN plates.",
        energy: 3,
        requireItems: [
          { itemId: "crowbar", qty: 1 },
          { itemId: "drill_bit", qty: 1 },
        ],
        successChance: 0.86,
        heatOnFail: 5,
      },
      {
        id: "window",
        kind: "window",
        name: "Pre-dawn lane",
        blurb: "Be in Millstone. Shed owned. Night preferred.",
        nerve: 5,
        successChance: 0.78,
        heatOnFail: 12,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Run the chop",
        blurb: "Approach → strip → parts out before light.",
        nerve: 10,
      },
    ],
  },
  {
    id: "crane_blind",
    name: "Crane Blind Spot",
    blurb: "DocksReach crane arc the cameras miss. Dockhand pass required.",
    district: "docksreach",
    risk: "high",
    requiresLevel: 4,
    requiresJob: "dock_1",
    payoutMin: 8500,
    payoutMax: 15500,
    xp: 155,
    heatOnSuccess: 21,
    heatOnFail: 29,
    cooldownHours: 7,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Arc chart",
        blurb: "Where the crane shadow kills the lens.",
        energy: 5,
        streetCost: 650,
        successChance: 0.77,
        heatOnFail: 6,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire yard lookout",
        blurb: "Someone with a radio that lies soft.",
        energy: 3,
        streetCost: 1500,
        successChance: 0.81,
        heatOnFail: 5,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage harbor key",
        blurb: "Gate that still scans your face.",
        energy: 2,
        requireItems: [{ itemId: "harbor_key", qty: 1 }],
        successChance: 0.9,
        heatOnFail: 4,
      },
      {
        id: "window",
        kind: "window",
        name: "Tide crane gap",
        blurb: "Stand in DocksReach when the arc goes dark.",
        nerve: 4,
        successChance: 0.84,
        heatOnFail: 8,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Cut the blind",
        blurb: "Approach → lift → extract under steel.",
        nerve: 7,
      },
    ],
  },
  {
    id: "cold_chain",
    name: "Cold Chain Cut",
    blurb: "Refrigerated container that never thawed on the sheet. Harbor cert required.",
    district: "docksreach",
    risk: "extreme",
    requiresLevel: 7,
    requiresCourse: "hl1",
    payoutMin: 22000,
    payoutMax: 38000,
    xp: 270,
    heatOnSuccess: 34,
    heatOnFail: 44,
    cooldownHours: 14,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Temp log skim",
        blurb: "Which reefer unit reports false cold.",
        energy: 8,
        streetCost: 1600,
        successChance: 0.68,
        heatOnFail: 11,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire cold crew",
        blurb: "Cutter, driver, lookout — paid in quiet.",
        energy: 5,
        streetCost: 4200,
        successChance: 0.72,
        heatOnFail: 9,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage drill + key",
        blurb: "Seal work and yard access.",
        energy: 3,
        requireItems: [
          { itemId: "drill_bit", qty: 1 },
          { itemId: "harbor_key", qty: 1 },
        ],
        successChance: 0.85,
        heatOnFail: 6,
      },
      {
        id: "window",
        kind: "window",
        name: "Fog tide",
        blurb: "Be in DocksReach when the cold chain radios nap.",
        nerve: 5,
        successChance: 0.76,
        heatOnFail: 12,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Cut the chain",
        blurb: "Approach → pierce → extract before thaw.",
        nerve: 11,
      },
    ],
  },
  {
    id: "ambulance_divert",
    name: "Ambulance Divert",
    blurb: "Ashcourt overflow bay. One divert call, one unlocked med cart.",
    district: "ashcourt",
    risk: "moderate",
    requiresLevel: 3,
    requiresVisitedDistrict: "ashcourt",
    payoutMin: 4000,
    payoutMax: 7800,
    xp: 110,
    heatOnSuccess: 14,
    heatOnFail: 20,
    cooldownHours: 5,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Bay chart",
        blurb: "Which bay goes soft when the sirens stack.",
        energy: 4,
        streetCost: 320,
        successChance: 0.83,
        heatOnFail: 4,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire orderly tip",
        blurb: "Someone who knows the cart codes.",
        energy: 2,
        streetCost: 800,
        successChance: 0.86,
        heatOnFail: 4,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage badge blank",
        blurb: "Warm ink for a soft bay door.",
        energy: 1,
        requireItems: [{ itemId: "badge_blank", qty: 1 }],
        successChance: 0.93,
        heatOnFail: 2,
      },
      {
        id: "window",
        kind: "window",
        name: "Siren stack",
        blurb: "Be in Ashcourt when three ambs hit at once.",
        nerve: 3,
        successChance: 0.88,
        heatOnFail: 6,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Divert and lift",
        blurb: "Approach → cart → vanish into overflow.",
        nerve: 6,
      },
    ],
  },
  {
    id: "evidence_soft",
    name: "Evidence Soft Door",
    blurb: "Ashcourt evidence annex after hours. Persuasion face, heavy heat.",
    district: "ashcourt",
    risk: "extreme",
    requiresLevel: 6,
    requiresCourse: "se2",
    payoutMin: 19000,
    payoutMax: 34000,
    xp: 250,
    heatOnSuccess: 33,
    heatOnFail: 43,
    cooldownHours: 13,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Locker map",
        blurb: "Which cage still takes a warm badge.",
        energy: 7,
        streetCost: 1300,
        cleanCost: 500,
        successChance: 0.69,
        heatOnFail: 11,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire clerk ghost",
        blurb: "Someone who walks like paperwork.",
        energy: 5,
        streetCost: 3600,
        successChance: 0.73,
        heatOnFail: 9,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage badge + lockpick",
        blurb: "Face and quiet metal.",
        energy: 3,
        requireItems: [
          { itemId: "badge_blank", qty: 1 },
          { itemId: "lockpick", qty: 1 },
        ],
        successChance: 0.85,
        heatOnFail: 6,
      },
      {
        id: "window",
        kind: "window",
        name: "Annex dark",
        blurb: "Be in Ashcourt when the evidence floor goes quiet.",
        nerve: 5,
        successChance: 0.76,
        heatOnFail: 12,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Soft the cage",
        blurb: "Approach → door → extract tagged goods.",
        nerve: 10,
      },
    ],
  },
  {
    id: "clinic_ledger",
    name: "Clinic Ledger Lift",
    blurb: "Ward billing drawer that never reconciles. Line cook cover helps the hours.",
    district: "ashcourt",
    risk: "high",
    requiresLevel: 5,
    requiresJob: "kitchen_2",
    payoutMin: 9000,
    payoutMax: 16500,
    xp: 165,
    heatOnSuccess: 20,
    heatOnFail: 28,
    cooldownHours: 8,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Shift ledger",
        blurb: "Which clerk leaves the billing drawer cracked.",
        energy: 5,
        streetCost: 700,
        successChance: 0.77,
        heatOnFail: 6,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire kitchen tip",
        blurb: "Someone who can linger near cafeteria without a badge check.",
        energy: 3,
        streetCost: 1400,
        successChance: 0.81,
        heatOnFail: 5,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage lockpick",
        blurb: "Quiet drawer work.",
        energy: 2,
        requireItems: [{ itemId: "lockpick", qty: 1 }],
        successChance: 0.9,
        heatOnFail: 3,
      },
      {
        id: "window",
        kind: "window",
        name: "Lunch float",
        blurb: "Be in Ashcourt when billing empties for lunch.",
        nerve: 3,
        successChance: 0.85,
        heatOnFail: 7,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Lift the ledger",
        blurb: "Approach → drawer → exit like cafeteria staff.",
        nerve: 7,
      },
    ],
  },
  {
    id: "courier_swap",
    name: "Courier Desk Swap",
    blurb: "SpireYard desk packages that never match the log. Driver routes help.",
    district: "spireyard",
    risk: "moderate",
    requiresLevel: 3,
    requiresJob: "driver_1",
    payoutMin: 4200,
    payoutMax: 8000,
    xp: 112,
    heatOnSuccess: 14,
    heatOnFail: 20,
    cooldownHours: 5,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Manifest skim",
        blurb: "Which package number never gets called.",
        energy: 4,
        streetCost: 350,
        successChance: 0.82,
        heatOnFail: 4,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire desk ghost",
        blurb: "A face that belongs near the sorting bay.",
        energy: 2,
        streetCost: 850,
        successChance: 0.86,
        heatOnFail: 4,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage courier bag",
        blurb: "Looks like a real drop.",
        energy: 1,
        requireItems: [{ itemId: "courier_bag", qty: 1 }],
        successChance: 0.94,
        heatOnFail: 2,
      },
      {
        id: "window",
        kind: "window",
        name: "Rush hour desk",
        blurb: "Be in SpireYard when the desk is loud.",
        nerve: 3,
        successChance: 0.88,
        heatOnFail: 6,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Swap the drop",
        blurb: "Approach → swap → exit like a driver.",
        nerve: 6,
      },
    ],
  },
  {
    id: "penthouse_skim",
    name: "Penthouse Skim",
    blurb: "Spire Condo staging. Party float upstairs, clean exit downstairs.",
    district: "spireyard",
    risk: "extreme",
    requiresLevel: 7,
    requiresProperty: "sy_condo",
    requiresCourse: "cf2",
    payoutMin: 24000,
    payoutMax: 42000,
    xp: 280,
    heatOnSuccess: 35,
    heatOnFail: 46,
    cooldownHours: 15,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Guest list skim",
        blurb: "Which invite never gets checked twice.",
        energy: 8,
        streetCost: 1500,
        cleanCost: 900,
        successChance: 0.66,
        heatOnFail: 12,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire society crew",
        blurb: "Face, lookout, bag — paid in quiet suits.",
        energy: 5,
        streetCost: 4500,
        successChance: 0.7,
        heatOnFail: 10,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage suit + lockpick",
        blurb: "Look like money; open like a thief.",
        energy: 3,
        requireItems: [
          { itemId: "suit", qty: 1 },
          { itemId: "lockpick", qty: 1 },
        ],
        successChance: 0.84,
        heatOnFail: 6,
      },
      {
        id: "window",
        kind: "window",
        name: "Toast hour",
        blurb: "Be in SpireYard. Condo owned. Night preferred.",
        nerve: 5,
        successChance: 0.74,
        heatOnFail: 13,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Skim the pent",
        blurb: "Approach → float → extract like a guest.",
        nerve: 11,
      },
    ],
  },
  {
    id: "stoop_tax",
    name: "Stoop Tax Night",
    blurb: "OldCommons corner tax under party noise. Visit the Commons first.",
    district: "oldcommons",
    risk: "moderate",
    requiresLevel: 2,
    requiresVisitedDistrict: "oldcommons",
    payoutMin: 2600,
    payoutMax: 5000,
    xp: 75,
    heatOnSuccess: 11,
    heatOnFail: 17,
    cooldownHours: 4,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Walk the stoops",
        blurb: "Which corners pay quiet, which call uniforms.",
        energy: 3,
        streetCost: 180,
        successChance: 0.85,
        heatOnFail: 3,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire corner lookout",
        blurb: "Eyes that know when the block goes soft.",
        energy: 2,
        streetCost: 550,
        successChance: 0.88,
        heatOnFail: 3,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage gloves",
        blurb: "Fewer prints on the bag.",
        energy: 1,
        requireItems: [{ itemId: "gloves", qty: 1 }],
        successChance: 0.95,
        heatOnFail: 2,
      },
      {
        id: "window",
        kind: "window",
        name: "Party noise",
        blurb: "Be in OldCommons when the block is loud.",
        nerve: 2,
        successChance: 0.91,
        heatOnFail: 5,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Collect the tax",
        blurb: "Approach → bag → vanish into noise.",
        nerve: 5,
      },
    ],
  },
  {
    id: "race_bag",
    name: "Race Night Bag",
    blurb: "OldCommons race skim. Book bag walks when the crowd surges.",
    district: "oldcommons",
    risk: "high",
    requiresLevel: 4,
    requiresCourse: "se1",
    payoutMin: 8000,
    payoutMax: 15000,
    xp: 150,
    heatOnSuccess: 19,
    heatOnFail: 27,
    cooldownHours: 7,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Book stand map",
        blurb: "Which runner carries the night’s float.",
        energy: 5,
        streetCost: 600,
        successChance: 0.78,
        heatOnFail: 6,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire surge runner",
        blurb: "Fast feet when the crowd peaks.",
        energy: 3,
        streetCost: 1300,
        successChance: 0.82,
        heatOnFail: 5,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage radio",
        blurb: "Hear when the book moves.",
        energy: 2,
        requireItems: [{ itemId: "radio", qty: 1 }],
        successChance: 0.91,
        heatOnFail: 3,
      },
      {
        id: "window",
        kind: "window",
        name: "Finish surge",
        blurb: "Be in OldCommons when the race crowd breaks.",
        nerve: 3,
        successChance: 0.85,
        heatOnFail: 7,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Lift the bag",
        blurb: "Approach → cut → vanish into the surge.",
        nerve: 7,
      },
    ],
  },
  {
    id: "alley_stash",
    name: "Alley Stash Pull",
    blurb: "Commons Walk-up staging. Gang stash alley before dawn.",
    district: "oldcommons",
    risk: "high",
    requiresLevel: 5,
    requiresProperty: "oc_walkup",
    payoutMin: 12000,
    payoutMax: 21000,
    xp: 190,
    heatOnSuccess: 26,
    heatOnFail: 35,
    cooldownHours: 10,
    stages: [
      {
        id: "intel",
        kind: "intel",
        name: "Alley watch",
        blurb: "Which stash corner sleeps after two.",
        energy: 6,
        streetCost: 950,
        successChance: 0.73,
        heatOnFail: 8,
      },
      {
        id: "crew",
        kind: "crew",
        name: "Hire muscle pair",
        blurb: "Quiet hands that can hold a door.",
        energy: 4,
        streetCost: 2400,
        successChance: 0.77,
        heatOnFail: 7,
      },
      {
        id: "kit",
        kind: "kit",
        name: "Stage crowbar + vest",
        blurb: "Breach and a little armor for bad luck.",
        energy: 3,
        requireItems: [
          { itemId: "crowbar", qty: 1 },
          { itemId: "vest", qty: 1 },
        ],
        successChance: 0.88,
        heatOnFail: 5,
      },
      {
        id: "window",
        kind: "window",
        name: "Pre-dawn alley",
        blurb: "Be in OldCommons. Walk-up owned. Night preferred.",
        nerve: 4,
        successChance: 0.8,
        heatOnFail: 10,
      },
      {
        id: "execute",
        kind: "execute",
        name: "Pull the stash",
        blurb: "Approach → breach → extract to the walk-up.",
        nerve: 9,
      },
    ],
  },
];

export function getHeist(id: string) {
  return HEISTS.find((h) => h.id === id);
}
