import type { JobDef } from "@/game/types";

/**
 * AAA job expansion — rank-4 apex for existing careers + 8 new careers × 4 ranks.
 * Total with core 24: 8 + 32 = 40 → 64 jobs.
 */
export const JOBS_EXTRA: JobDef[] = [
  // —— Existing career apex (rank 4) ——
  {
    id: "retail_4",
    career: "retail",
    rank: 4,
    title: "District Merch Lead",
    basePay: 3000,
    energy: 5,
    districtBias: ["glassrow", "spireyard"],
    special: "Shrinkage cover",
    blurb: "Own multi-floor inventory stories. Shrinkage becomes a dialect.",
    promoteXp: 700,
    promoteCourse: "cf3",
    requiresLevel: 7,
    specialtyFamilies: ["petty", "street"],
    specialtyCrimeIds: ["shoplift", "jewel_case", "pawn_tag_swap", "coat_check"],
  },
  {
    id: "kitchen_4",
    career: "kitchen",
    rank: 4,
    title: "Executive Chef Cover",
    basePay: 2700,
    energy: 5,
    districtBias: ["millstone", "glassrow"],
    special: "Leftover kit",
    blurb: "Keys to every walk-in. Catering invoices that never existed.",
    promoteXp: 680,
    promoteCourse: "se4",
    requiresLevel: 6,
    specialtyCrimeIds: ["pharmacy", "food_truck", "hotel_safe", "food_wholesaler"],
  },
  {
    id: "warehouse_4",
    career: "warehouse",
    rank: 4,
    title: "Logistics Ghost",
    basePay: 3100,
    energy: 5,
    districtBias: ["millstone", "docksreach"],
    special: "Mislabel",
    blurb: "Pallets that vanish on paper. Yard radios answer to you.",
    promoteXp: 720,
    promoteCourse: "hl2",
    requiresLevel: 7,
    specialtyFamilies: ["street", "heavy"],
    specialtyCrimeIds: ["warehouse", "chop_shop", "chop_fleet", "truck_seal"],
  },
  {
    id: "dock_4",
    career: "dockhand",
    rank: 4,
    title: "Harbor Fixer",
    basePay: 3400,
    energy: 5,
    districtBias: ["docksreach"],
    special: "Mislabel",
    blurb: "Customs stamps bend. Cranes move when the city sleeps.",
    promoteXp: 780,
    promoteCourse: "hl3",
    requiresLevel: 8,
    specialtyFamilies: ["heavy", "street"],
    specialtyCrimeIds: ["harbor", "airport_cargo", "port_crane", "harbor_customs"],
  },
  {
    id: "driver_4",
    career: "driver",
    rank: 4,
    title: "Fleet Shadow",
    basePay: 2800,
    energy: 5,
    districtBias: ["oldcommons", "millstone", "glassrow"],
    special: "Fare tip",
    blurb: "Dispatch that erases routes. Plate data is your currency.",
    promoteXp: 660,
    promoteCourse: "se4",
    requiresLevel: 6,
    specialtyFamilies: ["street"],
    specialtyCrimeIds: ["car_breakin", "parking_garage", "valet_keys", "trailer_hitch"],
  },
  {
    id: "orderly_4",
    career: "orderly",
    rank: 4,
    title: "Wing Coordinator",
    basePay: 2900,
    energy: 5,
    districtBias: ["ashcourt", "redclinic"],
    special: "Keycard lapse",
    blurb: "Ward schedules in your pocket. Narc cages trust your face.",
    promoteXp: 700,
    promoteCourse: "mc3",
    requiresLevel: 7,
    specialtyCrimeIds: ["hospital_vault", "clinic_narc", "blood_bank", "ambulance_kit"],
  },
  {
    id: "casino_4",
    career: "casino",
    rank: 4,
    title: "Cage Liaison",
    basePay: 3300,
    energy: 5,
    districtBias: ["glassrow", "neonpier"],
    special: "Chip error",
    blurb: "Count-room whispers. Armored bays nod when you pass.",
    promoteXp: 800,
    promoteCourse: "cf3",
    requiresLevel: 8,
    specialtyFamilies: ["heavy"],
    specialtyCrimeIds: ["casino_cage", "casino_count", "casino_armored", "casino_tip"],
  },
  {
    id: "citydesk_4",
    career: "citydesk",
    rank: 4,
    title: "Civic Ghostwriter",
    basePay: 3000,
    energy: 5,
    districtBias: ["ashcourt", "spireyard"],
    special: "Stamp access",
    blurb: "Records rewrite on command. Vaults of paper — and steel.",
    promoteXp: 740,
    promoteCourse: "cf3",
    requiresLevel: 7,
    specialtyCrimeIds: ["bond_fraud", "city_vault", "mayor_safe", "news_archive"],
  },

  // —— Security ——
  {
    id: "security_1",
    career: "security",
    rank: 1,
    title: "Lobby Watch",
    basePay: 860,
    energy: 5,
    districtBias: ["spireyard", "glassrow"],
    special: "Badge lag",
    blurb: "Cameras and clipboards. Soft entry when you look away.",
    requiresLevel: 2,
    specialtyFamilies: ["street"],
    specialtyCrimeIds: ["badge_clone", "guard_booth", "parking_garage"],
  },
  {
    id: "security_2",
    career: "security",
    rank: 2,
    title: "Shift Guard",
    basePay: 1500,
    energy: 5,
    districtBias: ["spireyard", "ashcourt"],
    special: "Badge lag",
    blurb: "Radio codes and blind spots you invented.",
    promoteXp: 320,
    promoteCourse: "sy1",
    specialtyFamilies: ["street"],
    specialtyCrimeIds: ["badge_clone", "office_server", "spire_mailroom"],
  },
  {
    id: "security_3",
    career: "security",
    rank: 3,
    title: "Site Lead",
    basePay: 2300,
    energy: 5,
    districtBias: ["spireyard", "millstone"],
    special: "Badge lag",
    blurb: "Roster control. Doors open for people who tip quiet.",
    promoteXp: 520,
    promoteCourse: "sy2",
    requiresLevel: 5,
    specialtyFamilies: ["street", "heavy"],
    specialtyCrimeIds: ["armored", "armored_depot", "guard_booth"],
  },
  {
    id: "security_4",
    career: "security",
    rank: 4,
    title: "Contract Shadow",
    basePay: 3200,
    energy: 5,
    districtBias: ["spireyard", "glassrow"],
    special: "Badge lag",
    blurb: "Private contracts. Vault schedules live in your earpiece.",
    promoteXp: 740,
    promoteCourse: "sy3",
    requiresLevel: 7,
    specialtyFamilies: ["heavy"],
    specialtyCrimeIds: ["private_vault", "data_center", "bank_night"],
  },

  // —— Courier ——
  {
    id: "courierjob_1",
    career: "courier",
    rank: 1,
    title: "Bag Runner",
    basePay: 780,
    energy: 5,
    districtBias: ["glassrow", "oldcommons", "millstone"],
    special: "Route tip",
    blurb: "Dead drops and tram maps. Speed is the product.",
    specialtyFamilies: ["petty", "street"],
    specialtyCrimeIds: ["courier_hijack", "delivery_package", "bike_basket"],
  },
  {
    id: "courierjob_2",
    career: "courier",
    rank: 2,
    title: "Night Drop",
    basePay: 1350,
    energy: 5,
    districtBias: ["glassrow", "docksreach"],
    special: "Route tip",
    blurb: "After-dark envelopes. Cameras that somehow miss you.",
    promoteXp: 290,
    promoteCourse: "se1",
    specialtyFamilies: ["street"],
    specialtyCrimeIds: ["courier_hijack", "drop_swap", "wire_tap"],
  },
  {
    id: "courierjob_3",
    career: "courier",
    rank: 3,
    title: "Route Boss",
    basePay: 2100,
    energy: 5,
    districtBias: ["millstone", "docksreach"],
    special: "Route tip",
    blurb: "Assign the runs. Federal bags look like grocery runs.",
    promoteXp: 480,
    promoteCourse: "sy2",
    requiresLevel: 5,
    specialtyFamilies: ["street", "heavy"],
    specialtyCrimeIds: ["courier", "federal_drop", "drop_swap"],
  },
  {
    id: "courierjob_4",
    career: "courier",
    rank: 4,
    title: "Wire Broker",
    basePay: 2950,
    energy: 5,
    districtBias: ["glassrow", "spireyard", "docksreach"],
    special: "Route tip",
    blurb: "Own the chatter. Exchange hits start as errands.",
    promoteXp: 700,
    promoteCourse: "sy4",
    requiresLevel: 8,
    specialtyFamilies: ["heavy"],
    specialtyCrimeIds: ["courier", "wire_exchange", "embassy_bag"],
  },

  // —— Mechanic ——
  {
    id: "mechanic_1",
    career: "mechanic",
    rank: 1,
    title: "Bay Hand",
    basePay: 820,
    energy: 5,
    districtBias: ["millstone", "oldcommons"],
    special: "Parts float",
    blurb: "Oil and undercarriages. Parts walk when paperwork naps.",
    specialtyFamilies: ["street"],
    specialtyCrimeIds: ["catalytic", "bicycle", "scooter_boost"],
  },
  {
    id: "mechanic_2",
    career: "mechanic",
    rank: 2,
    title: "Shop Tech",
    basePay: 1450,
    energy: 5,
    districtBias: ["millstone"],
    special: "Parts float",
    blurb: "VIN stories that rewrite themselves.",
    promoteXp: 300,
    promoteCourse: "se1",
    specialtyFamilies: ["street"],
    specialtyCrimeIds: ["catalytic", "car_breakin", "bike_chop"],
  },
  {
    id: "mechanic_3",
    career: "mechanic",
    rank: 3,
    title: "Chop Lead",
    basePay: 2250,
    energy: 5,
    districtBias: ["millstone", "oldcommons"],
    special: "Parts float",
    blurb: "Bay doors after midnight. Wholesale that never hit a lot.",
    promoteXp: 500,
    promoteCourse: "se4",
    requiresLevel: 5,
    specialtyFamilies: ["street", "heavy"],
    specialtyCrimeIds: ["chop_shop", "chop_fleet", "scrap_yard"],
  },
  {
    id: "mechanic_4",
    career: "mechanic",
    rank: 4,
    title: "Fleet Ghost",
    basePay: 3050,
    energy: 5,
    districtBias: ["millstone", "docksreach"],
    special: "Parts float",
    blurb: "Whole fleets vanish into paperwork fog.",
    promoteXp: 720,
    promoteCourse: "hl2",
    requiresLevel: 7,
    specialtyFamilies: ["heavy"],
    specialtyCrimeIds: ["chop_fleet", "trailer_hitch", "truck_seal"],
  },

  // —— Bartender ——
  {
    id: "bartender_1",
    career: "bartender",
    rank: 1,
    title: "Barback",
    basePay: 740,
    energy: 5,
    districtBias: ["glassrow", "neonpier", "oldcommons"],
    special: "Tab float",
    blurb: "Ice and ears. Tips and tip-offs share a register.",
    specialtyFamilies: ["petty"],
    specialtyCrimeIds: ["tip_jar", "short_change", "coinop_scam"],
  },
  {
    id: "bartender_2",
    career: "bartender",
    rank: 2,
    title: "Bar Lead",
    basePay: 1280,
    energy: 5,
    districtBias: ["neonpier", "glassrow"],
    special: "Tab float",
    blurb: "Own the rail. Till stories bend after last call.",
    promoteXp: 280,
    promoteCourse: "se2",
    specialtyCrimeIds: ["club_till", "alley_dice", "tip_jar"],
  },
  {
    id: "bartender_3",
    career: "bartender",
    rank: 3,
    title: "Floor Manager",
    basePay: 2000,
    energy: 5,
    districtBias: ["neonpier", "glassrow"],
    special: "Tab float",
    blurb: "Velvet rope politics. Back-office keys in the tip jar.",
    promoteXp: 460,
    promoteCourse: "cf1",
    requiresLevel: 4,
    specialtyCrimeIds: ["club_till", "casino_tip", "pier_ticket"],
  },
  {
    id: "bartender_4",
    career: "bartender",
    rank: 4,
    title: "Nightlife Fixer",
    basePay: 2850,
    energy: 5,
    districtBias: ["neonpier", "glassrow", "spireyard"],
    special: "Tab float",
    blurb: "Clubs and cages. Soft money that hardens overnight.",
    promoteXp: 680,
    promoteCourse: "cf2",
    requiresLevel: 6,
    specialtyFamilies: ["street", "heavy"],
    specialtyCrimeIds: ["club_till", "yacht_safe", "pier_vault"],
  },

  // —— Telecom ——
  {
    id: "telecom_1",
    career: "telecom",
    rank: 1,
    title: "Line Tech",
    basePay: 880,
    energy: 5,
    districtBias: ["millstone", "spireyard"],
    special: "Signal ghost",
    blurb: "Poles and junction boxes. Blind spots you install yourself.",
    requiresLevel: 2,
    specialtyFamilies: ["street"],
    specialtyCrimeIds: ["wire_tap", "roof_antenna", "neon_sign"],
  },
  {
    id: "telecom_2",
    career: "telecom",
    rank: 2,
    title: "Node Op",
    basePay: 1550,
    energy: 5,
    districtBias: ["millstone", "ashcourt"],
    special: "Signal ghost",
    blurb: "Camera grids that lie on schedule.",
    promoteXp: 330,
    promoteCourse: "sy1",
    specialtyCrimeIds: ["atm_skimmer", "wire_tap", "dock_radio"],
  },
  {
    id: "telecom_3",
    career: "telecom",
    rank: 3,
    title: "Mesh Lead",
    basePay: 2400,
    energy: 5,
    districtBias: ["spireyard", "millstone"],
    special: "Signal ghost",
    blurb: "City mesh passwords. Heavy ops run quieter on your clock.",
    promoteXp: 540,
    promoteCourse: "sy2",
    requiresLevel: 5,
    specialtyFamilies: ["street", "heavy"],
    specialtyCrimeIds: ["office_server", "telecom_hub", "data_center"],
  },
  {
    id: "telecom_4",
    career: "telecom",
    rank: 4,
    title: "Signal Broker",
    basePay: 3300,
    energy: 5,
    districtBias: ["spireyard", "glassrow"],
    special: "Signal ghost",
    blurb: "Own the chatter. Exchange hits start as maintenance tickets.",
    promoteXp: 760,
    promoteCourse: "sy4",
    requiresLevel: 8,
    specialtyFamilies: ["heavy"],
    specialtyCrimeIds: ["telecom_hub", "wire_exchange", "federal_drop"],
  },

  // —— Hotel ——
  {
    id: "hotel_1",
    career: "hotel",
    rank: 1,
    title: "Housekeeping",
    basePay: 760,
    energy: 5,
    districtBias: ["spireyard", "glassrow"],
    special: "Keycard float",
    blurb: "Carts and safes. Guests leave more than towels.",
    specialtyFamilies: ["petty"],
    specialtyCrimeIds: ["hotel_minibar", "hotel_towel", "laundry_pouch"],
  },
  {
    id: "hotel_2",
    career: "hotel",
    rank: 2,
    title: "Front Desk",
    basePay: 1320,
    energy: 5,
    districtBias: ["spireyard", "glassrow"],
    special: "Keycard float",
    blurb: "Names that don't match IDs. Carts that skip floors.",
    promoteXp: 300,
    promoteCourse: "cf1",
    specialtyCrimeIds: ["hotel_cart", "hotel_safe", "coat_check"],
  },
  {
    id: "hotel_3",
    career: "hotel",
    rank: 3,
    title: "Night Manager",
    basePay: 2150,
    energy: 5,
    districtBias: ["spireyard"],
    special: "Keycard float",
    blurb: "Master keys and soft counts after midnight.",
    promoteXp: 500,
    promoteCourse: "le2",
    requiresLevel: 5,
    specialtyFamilies: ["street", "heavy"],
    specialtyCrimeIds: ["hotel_safe", "valet_keys", "spire_pent"],
  },
  {
    id: "hotel_4",
    career: "hotel",
    rank: 4,
    title: "Hospitality Ghost",
    basePay: 3000,
    energy: 5,
    districtBias: ["spireyard", "neonpier"],
    special: "Keycard float",
    blurb: "Penthouse vaults and yacht clients. Soft doors, hard money.",
    promoteXp: 720,
    promoteCourse: "le3",
    requiresLevel: 7,
    specialtyFamilies: ["heavy"],
    specialtyCrimeIds: ["spire_pent", "yacht_safe", "museum_vault"],
  },

  // —— Transit ——
  {
    id: "transit_1",
    career: "transit",
    rank: 1,
    title: "Platform Hand",
    basePay: 800,
    energy: 5,
    districtBias: ["millstone", "glassrow", "oldcommons"],
    special: "Fare float",
    blurb: "Turnstiles and lockers. Fareboxes that leak on purpose.",
    specialtyFamilies: ["petty"],
    specialtyCrimeIds: ["bus_pass", "ticket_scalp", "tram_farebox"],
  },
  {
    id: "transit_2",
    career: "transit",
    rank: 2,
    title: "Depot Clerk",
    basePay: 1400,
    energy: 5,
    districtBias: ["millstone", "docksreach"],
    special: "Fare float",
    blurb: "Locker tags and night manifests that almost match.",
    promoteXp: 310,
    promoteCourse: "se1",
    specialtyCrimeIds: ["bus_depot", "locker_tag", "press_van"],
  },
  {
    id: "transit_3",
    career: "transit",
    rank: 3,
    title: "Yard Dispatcher",
    basePay: 2200,
    energy: 5,
    districtBias: ["millstone", "docksreach"],
    special: "Fare float",
    blurb: "Rail cars that skip inspection. Arms crates that look like mail.",
    promoteXp: 510,
    promoteCourse: "hl1",
    requiresLevel: 5,
    specialtyFamilies: ["street", "heavy"],
    specialtyCrimeIds: ["rail_mail", "train_arms", "rail_arms"],
  },
  {
    id: "transit_4",
    career: "transit",
    rank: 4,
    title: "Rail Shadow",
    basePay: 3100,
    energy: 5,
    districtBias: ["docksreach", "millstone"],
    special: "Fare float",
    blurb: "Own the yard whistle. Federal drops ride your schedules.",
    promoteXp: 740,
    promoteCourse: "hl3",
    requiresLevel: 8,
    specialtyFamilies: ["heavy"],
    specialtyCrimeIds: ["rail_arms", "arms_barge", "airport_vault"],
  },

  // —— Pawn ——
  {
    id: "pawn_1",
    career: "pawn",
    rank: 1,
    title: "Counter Clerk",
    basePay: 770,
    energy: 5,
    districtBias: ["oldcommons", "millstone"],
    special: "Tag float",
    blurb: "Tickets and tags. Values that change under fluorescent light.",
    specialtyFamilies: ["petty"],
    specialtyCrimeIds: ["pawn_tag_swap", "short_change", "bicycle"],
  },
  {
    id: "pawn_2",
    career: "pawn",
    rank: 2,
    title: "Appraiser",
    basePay: 1340,
    energy: 5,
    districtBias: ["oldcommons", "glassrow"],
    special: "Tag float",
    blurb: "Know what walks. Know who buys quiet.",
    promoteXp: 290,
    promoteCourse: "se2",
    specialtyCrimeIds: ["pawn_safe", "jewel_case", "busker_case"],
  },
  {
    id: "pawn_3",
    career: "pawn",
    rank: 3,
    title: "Shop Boss",
    basePay: 2050,
    energy: 5,
    districtBias: ["oldcommons", "neonpier"],
    special: "Tag float",
    blurb: "Safe dials and fence networks. Street exits get cleaner.",
    promoteXp: 470,
    promoteCourse: "se5",
    requiresLevel: 5,
    specialtyFamilies: ["street"],
    specialtyCrimeIds: ["pawn_safe", "laundry_vault", "syndicate_ledger"],
  },
  {
    id: "pawn_4",
    career: "pawn",
    rank: 4,
    title: "Fence Broker",
    basePay: 2900,
    energy: 5,
    districtBias: ["oldcommons", "neonpier", "docksreach"],
    special: "Tag float",
    blurb: "Who buys the city. Ledger grabs start as appraisals.",
    promoteXp: 700,
    promoteCourse: "se5",
    requiresLevel: 7,
    specialtyFamilies: ["street", "heavy"],
    specialtyCrimeIds: ["syndicate_ledger", "gang_armory", "gang_stash"],
  },
];
