import type { JobDef } from "@/game/types";

/** V1 — 8 careers × 3 ranks = 24 jobs */
export const JOBS: JobDef[] = [
  // Retail
  {
    id: "retail_1",
    career: "retail",
    rank: 1,
    title: "Retail Clerk",
    basePay: 800,
    energy: 5,
    districtBias: ["glassrow"],
    special: "Shrinkage cover",
    blurb: "Glassrow floors. Watch cameras, move product, keep heat quiet.",
    specialtyFamilies: ["petty"],
    specialtyCrimeIds: ["shoplift", "vending", "short_change"],
  },
  {
    id: "retail_2",
    career: "retail",
    rank: 2,
    title: "Shift Lead",
    basePay: 1400,
    energy: 5,
    districtBias: ["glassrow"],
    special: "Shrinkage cover",
    blurb: "Keys, schedules, and cover stories when inventory walks.",
    promoteXp: 300,
    promoteCourse: "cf1",
    specialtyFamilies: ["petty"],
    specialtyCrimeIds: ["shoplift", "vending", "pickpocket", "cafe_phone"],
  },
  {
    id: "retail_3",
    career: "retail",
    rank: 3,
    title: "Floor Boss",
    basePay: 2200,
    energy: 5,
    districtBias: ["glassrow", "spireyard"],
    special: "Shrinkage cover",
    blurb: "Own the floor. Schedules bend for people who know you.",
    promoteXp: 500,
    promoteCourse: "cf2",
    requiresLevel: 5,
    specialtyFamilies: ["petty"],
    specialtyCrimeIds: ["shoplift", "vending", "pickpocket", "jewel_case"],
  },

  // Kitchen
  {
    id: "kitchen_1",
    career: "kitchen",
    rank: 1,
    title: "Kitchen Hand",
    basePay: 700,
    energy: 5,
    districtBias: ["millstone", "oldcommons"],
    special: "Leftover kit",
    blurb: "Heat and grease. Stable clean pay when the street runs hot.",
    specialtyCrimeIds: ["pharmacy", "food_truck"],
  },
  {
    id: "kitchen_2",
    career: "kitchen",
    rank: 2,
    title: "Line Cook",
    basePay: 1200,
    energy: 5,
    districtBias: ["millstone", "oldcommons"],
    special: "Leftover kit",
    blurb: "Own the line. Better tips, better leftovers, better cover.",
    promoteXp: 300,
    promoteCourse: "se2",
    specialtyCrimeIds: ["pharmacy", "food_truck"],
  },
  {
    id: "kitchen_3",
    career: "kitchen",
    rank: 3,
    title: "Sous",
    basePay: 1900,
    energy: 5,
    districtBias: ["millstone", "glassrow"],
    special: "Leftover kit",
    blurb: "Kitchen politics. Keys to the walk-in and the till.",
    promoteXp: 480,
    promoteCourse: "se2",
    requiresLevel: 4,
    specialtyCrimeIds: ["pharmacy", "food_truck", "hotel_safe"],
  },

  // Warehouse
  {
    id: "warehouse_1",
    career: "warehouse",
    rank: 1,
    title: "Warehouse Loader",
    basePay: 850,
    energy: 5,
    districtBias: ["millstone"],
    special: "Mislabel",
    blurb: "Pallets and scanners. Miscounts happen when you want them to.",
    specialtyFamilies: ["street"],
    specialtyCrimeIds: ["warehouse", "catalytic", "construction_skip"],
  },
  {
    id: "warehouse_2",
    career: "warehouse",
    rank: 2,
    title: "Inventory Tech",
    basePay: 1500,
    energy: 5,
    districtBias: ["millstone"],
    special: "Mislabel",
    blurb: "System access. Labels that lie on purpose.",
    promoteXp: 320,
    promoteCourse: "se1",
    specialtyFamilies: ["street"],
    specialtyCrimeIds: ["warehouse", "drop_swap", "chop_shop"],
  },
  {
    id: "warehouse_3",
    career: "warehouse",
    rank: 3,
    title: "Yard Lead",
    basePay: 2300,
    energy: 5,
    districtBias: ["millstone", "docksreach"],
    special: "Mislabel",
    blurb: "Yard keys and night schedules. Heavy doors open soft.",
    promoteXp: 520,
    promoteCourse: "hl1",
    requiresLevel: 5,
    specialtyFamilies: ["street", "heavy"],
    specialtyCrimeIds: ["warehouse", "chop_shop", "substation_copper"],
  },

  // Dockhand
  {
    id: "dock_1",
    career: "dockhand",
    rank: 1,
    title: "Dockhand",
    basePay: 900,
    energy: 5,
    districtBias: ["docksreach"],
    special: "Mislabel",
    blurb: "Cranes and crates. Harbor work opens container ops later.",
    requiresLevel: 2,
    specialtyFamilies: ["heavy", "street"],
    specialtyCrimeIds: ["harbor", "warehouse", "dock_pierce"],
  },
  {
    id: "dock_2",
    career: "dockhand",
    rank: 2,
    title: "Crane Assistant",
    basePay: 1600,
    energy: 5,
    districtBias: ["docksreach"],
    special: "Mislabel",
    blurb: "Yard access and miscount opportunities. Harbor specialty deepens.",
    promoteXp: 300,
    promoteCourse: "hl1",
    specialtyFamilies: ["heavy", "street"],
    specialtyCrimeIds: ["harbor", "warehouse", "courier", "dock_pierce"],
  },
  {
    id: "dock_3",
    career: "dockhand",
    rank: 3,
    title: "Pier Boss",
    basePay: 2500,
    energy: 5,
    districtBias: ["docksreach"],
    special: "Mislabel",
    blurb: "Manifests bend. Containers move when you say so.",
    promoteXp: 550,
    promoteCourse: "hl2",
    requiresLevel: 6,
    specialtyFamilies: ["heavy", "street"],
    specialtyCrimeIds: ["harbor", "airport_cargo", "train_arms", "courier"],
  },

  // Driver
  {
    id: "driver_1",
    career: "driver",
    rank: 1,
    title: "Driver",
    basePay: 750,
    energy: 5,
    districtBias: ["millstone", "glassrow", "oldcommons"],
    special: "Fare tip",
    blurb: "Wheels and routes. Learn the city by meter.",
    specialtyFamilies: ["street"],
    specialtyCrimeIds: ["car_breakin", "mug", "courier_hijack"],
  },
  {
    id: "driver_2",
    career: "driver",
    rank: 2,
    title: "Night Driver",
    basePay: 1300,
    energy: 5,
    districtBias: ["millstone", "glassrow", "oldcommons"],
    special: "Fare tip",
    blurb: "After-dark fares pay more. You know every alley camera.",
    promoteXp: 280,
    promoteCourse: "se1",
    specialtyFamilies: ["street"],
    specialtyCrimeIds: ["car_breakin", "mug", "bicycle", "race_skim"],
  },
  {
    id: "driver_3",
    career: "driver",
    rank: 3,
    title: "Dispatcher",
    basePay: 2000,
    energy: 5,
    districtBias: ["oldcommons", "millstone"],
    special: "Fare tip",
    blurb: "Assign the runs. Plate data and dead zones are currency.",
    promoteXp: 460,
    promoteCourse: "se2",
    requiresLevel: 4,
    specialtyFamilies: ["street"],
    specialtyCrimeIds: ["car_breakin", "mug", "meter_maid", "catalytic"],
  },

  // Hospital orderly
  {
    id: "orderly_1",
    career: "orderly",
    rank: 1,
    title: "Hospital Orderly",
    basePay: 820,
    energy: 5,
    districtBias: ["ashcourt"],
    special: "Keycard lapse",
    blurb: "Gurneys and badges. Civic floors with soft medical access.",
    requiresLevel: 2,
    specialtyCrimeIds: ["pharmacy", "hospital_vault", "laundry_pouch"],
  },
  {
    id: "orderly_2",
    career: "orderly",
    rank: 2,
    title: "Tech Aide",
    basePay: 1450,
    energy: 5,
    districtBias: ["ashcourt"],
    special: "Keycard lapse",
    blurb: "Wards and pharmacy windows. One badge opens two doors.",
    promoteXp: 320,
    promoteCourse: "mc1",
    specialtyCrimeIds: ["pharmacy", "hospital_vault", "evidence_room"],
  },
  {
    id: "orderly_3",
    career: "orderly",
    rank: 3,
    title: "Ward Assistant",
    basePay: 2100,
    energy: 5,
    districtBias: ["ashcourt"],
    special: "Keycard lapse",
    blurb: "Trusted face on the ward. Vault schedules live in your pocket.",
    promoteXp: 500,
    promoteCourse: "mc2",
    requiresLevel: 5,
    specialtyCrimeIds: ["hospital_vault", "evidence_room", "evidence_swap"],
  },

  // Casino
  {
    id: "casino_1",
    career: "casino",
    rank: 1,
    title: "Casino Floor",
    basePay: 880,
    energy: 5,
    districtBias: ["glassrow"],
    special: "Chip error",
    blurb: "Felt and neon. Watch chips walk; sometimes help them.",
    requiresLevel: 2,
    specialtyCrimeIds: ["casino_cage", "coinop_scam", "short_change"],
  },
  {
    id: "casino_2",
    career: "casino",
    rank: 2,
    title: "Table Op",
    basePay: 1550,
    energy: 5,
    districtBias: ["glassrow"],
    special: "Chip error",
    blurb: "Tables listen when you deal. Cage windows look softer.",
    promoteXp: 340,
    promoteCourse: "cf1",
    specialtyFamilies: ["heavy"],
    specialtyCrimeIds: ["casino_cage", "jewel_case"],
  },
  {
    id: "casino_3",
    career: "casino",
    rank: 3,
    title: "Pit Support",
    basePay: 2400,
    energy: 5,
    districtBias: ["glassrow", "spireyard"],
    special: "Chip error",
    blurb: "Pit keys and soft counts. Heavy money moves past you.",
    promoteXp: 560,
    promoteCourse: "cf2",
    requiresLevel: 6,
    specialtyFamilies: ["heavy"],
    specialtyCrimeIds: ["casino_cage", "private_vault", "armored"],
  },

  // City desk
  {
    id: "citydesk_1",
    career: "citydesk",
    rank: 1,
    title: "City Desk Mail",
    basePay: 780,
    energy: 5,
    districtBias: ["ashcourt", "spireyard"],
    special: "Stamp access",
    blurb: "Mail rooms and rubber stamps. Fraud starts as paperwork.",
    requiresLevel: 2,
    specialtyCrimeIds: ["badge_clone", "bond_fraud", "bus_pass"],
  },
  {
    id: "citydesk_2",
    career: "citydesk",
    rank: 2,
    title: "Clerk",
    basePay: 1380,
    energy: 5,
    districtBias: ["ashcourt", "spireyard"],
    special: "Stamp access",
    blurb: "Records that rewrite themselves when no one watches.",
    promoteXp: 300,
    promoteCourse: "cf1",
    specialtyCrimeIds: ["badge_clone", "bond_fraud", "aide_blackmail"],
  },
  {
    id: "citydesk_3",
    career: "citydesk",
    rank: 3,
    title: "Records Analyst",
    basePay: 2150,
    energy: 5,
    districtBias: ["spireyard", "ashcourt"],
    special: "Stamp access",
    blurb: "Clearance that opens vaults of paper — and real vaults.",
    promoteXp: 520,
    promoteCourse: "cf2",
    requiresLevel: 5,
    specialtyCrimeIds: ["bond_fraud", "aide_blackmail", "evidence_swap", "private_vault"],
  },
];
