/**
 * AAA art wiring — unique photoreal plates under public/art.
 * Paths are AI-protected (crimes/, jobs/, campus/, npcs/) against generate-missing-art --force.
 */

/** New crime ids → unique photoreal plate path. */
export const CRIME_ART_EXTRA: Record<string, string> = {
  newspaper_rack: "/art/crimes/newspaper_rack.webp",
  tip_jar: "/art/crimes/tip_jar.webp",
  lost_found: "/art/crimes/lost_found.webp",
  mailbox_rifle: "/art/crimes/mailbox_rifle.webp",
  parking_permit: "/art/crimes/parking_permit.webp",
  laundry_card: "/art/crimes/laundry_card.webp",
  scooter_boost: "/art/crimes/scooter_boost.webp",
  umbrella_stand: "/art/crimes/umbrella_stand.webp",
  hotel_minibar: "/art/crimes/hotel_minibar.webp",
  gym_locker: "/art/crimes/gym_locker.webp",
  flower_stall: "/art/crimes/flower_stall.webp",
  busker_case: "/art/crimes/busker_case.webp",
  library_fine: "/art/crimes/library_fine.webp",
  ticket_scalp: "/art/crimes/ticket_scalp.webp",
  bodega_back: "/art/crimes/bodega_back.webp",
  pawn_tag_swap: "/art/crimes/pawn_tag_swap.webp",
  street_vendor_ice: "/art/crimes/street_vendor_ice.webp",
  clinic_clipboard: "/art/crimes/clinic_clipboard.webp",
  coat_check: "/art/crimes/coat_check.webp",
  meter_jam: "/art/crimes/meter_jam.webp",
  soda_hack: "/art/crimes/soda_hack.webp",
  charity_bin: "/art/crimes/charity_bin.webp",
  office_snack: "/art/crimes/office_snack.webp",
  tram_farebox: "/art/crimes/tram_farebox.webp",
  bike_basket: "/art/crimes/bike_basket.webp",
  selfie_stick: "/art/crimes/selfie_stick.webp",
  locker_tag: "/art/crimes/locker_tag.webp",
  arcade_token: "/art/crimes/arcade_token.webp",
  pharmacy_otc: "/art/crimes/pharmacy_otc.webp",
  hotel_towel: "/art/crimes/hotel_towel.webp",
  yard_sale: "/art/crimes/yard_sale.webp",
  press_pass: "/art/crimes/press_pass.webp",
  atm_skimmer: "/art/crimes/atm_skimmer.webp",
  truck_seal: "/art/crimes/truck_seal.webp",
  parking_garage: "/art/crimes/parking_garage.webp",
  club_till: "/art/crimes/club_till.webp",
  ambulance_kit: "/art/crimes/ambulance_kit.webp",
  taxi_meter: "/art/crimes/taxi_meter.webp",
  pawn_safe: "/art/crimes/pawn_safe.webp",
  wire_tap: "/art/crimes/wire_tap.webp",
  hotel_cart: "/art/crimes/hotel_cart.webp",
  bus_depot: "/art/crimes/bus_depot.webp",
  clinic_sample: "/art/crimes/clinic_sample.webp",
  neon_sign: "/art/crimes/neon_sign.webp",
  shipping_label: "/art/crimes/shipping_label.webp",
  valet_keys: "/art/crimes/valet_keys.webp",
  roof_antenna: "/art/crimes/roof_antenna.webp",
  evidence_locker: "/art/crimes/evidence_locker.webp",
  food_wholesaler: "/art/crimes/food_wholesaler.webp",
  bike_chop: "/art/crimes/bike_chop.webp",
  casino_tip: "/art/crimes/casino_tip.webp",
  dock_radio: "/art/crimes/dock_radio.webp",
  spire_mailroom: "/art/crimes/spire_mailroom.webp",
  alley_dice: "/art/crimes/alley_dice.webp",
  scrap_yard: "/art/crimes/scrap_yard.webp",
  blood_bank: "/art/crimes/blood_bank.webp",
  press_van: "/art/crimes/press_van.webp",
  harbor_fuel: "/art/crimes/harbor_fuel.webp",
  arcade_board: "/art/crimes/arcade_board.webp",
  laundry_vault: "/art/crimes/laundry_vault.webp",
  trailer_hitch: "/art/crimes/trailer_hitch.webp",
  office_server: "/art/crimes/office_server.webp",
  pier_ticket: "/art/crimes/pier_ticket.webp",
  guard_booth: "/art/crimes/guard_booth.webp",
  armored_depot: "/art/crimes/armored_depot.webp",
  data_center: "/art/crimes/data_center.webp",
  pharma_warehouse: "/art/crimes/pharma_warehouse.webp",
  yacht_safe: "/art/crimes/yacht_safe.webp",
  rail_mail: "/art/crimes/rail_mail.webp",
  city_vault: "/art/crimes/city_vault.webp",
  casino_count: "/art/crimes/casino_count.webp",
  hospital_mri: "/art/crimes/hospital_mri.webp",
  port_crane: "/art/crimes/port_crane.webp",
  gang_armory: "/art/crimes/gang_armory.webp",
  embassy_bag: "/art/crimes/embassy_bag.webp",
  telecom_hub: "/art/crimes/telecom_hub.webp",
  museum_vault: "/art/crimes/museum_vault.webp",
  fuel_depot: "/art/crimes/fuel_depot.webp",
  bank_night: "/art/crimes/bank_night.webp",
  clinic_narc: "/art/crimes/clinic_narc.webp",
  chop_fleet: "/art/crimes/chop_fleet.webp",
  bond_warehouse: "/art/crimes/bond_warehouse.webp",
  substation_core: "/art/crimes/substation_core.webp",
  airport_vault: "/art/crimes/airport_vault.webp",
  mayor_safe: "/art/crimes/mayor_safe.webp",
  arms_barge: "/art/crimes/arms_barge.webp",
  federal_drop: "/art/crimes/federal_drop.webp",
  casino_armored: "/art/crimes/casino_armored.webp",
  lab_isolator: "/art/crimes/lab_isolator.webp",
  pier_vault: "/art/crimes/pier_vault.webp",
  news_archive: "/art/crimes/news_archive.webp",
  rail_arms: "/art/crimes/rail_arms.webp",
  spire_pent: "/art/crimes/spire_pent.webp",
  harbor_customs: "/art/crimes/harbor_customs.webp",
  syndicate_ledger: "/art/crimes/syndicate_ledger.webp",
  wire_exchange: "/art/crimes/wire_exchange.webp",
};

export const JOB_ART_EXTRA: Record<string, string> = {
  retail_4: "/art/jobs/retail_4.webp",
  kitchen_4: "/art/jobs/kitchen_4.webp",
  warehouse_4: "/art/jobs/warehouse_4.webp",
  dock_4: "/art/jobs/dock_4.webp",
  driver_4: "/art/jobs/driver_4.webp",
  orderly_4: "/art/jobs/orderly_4.webp",
  casino_4: "/art/jobs/casino_4.webp",
  citydesk_4: "/art/jobs/citydesk_4.webp",
  security_1: "/art/jobs/security_1.webp",
  security_2: "/art/jobs/security_2.webp",
  security_3: "/art/jobs/security_3.webp",
  security_4: "/art/jobs/security_4.webp",
  courierjob_1: "/art/jobs/courierjob_1.webp",
  courierjob_2: "/art/jobs/courierjob_2.webp",
  courierjob_3: "/art/jobs/courierjob_3.webp",
  courierjob_4: "/art/jobs/courierjob_4.webp",
  mechanic_1: "/art/jobs/mechanic_1.webp",
  mechanic_2: "/art/jobs/mechanic_2.webp",
  mechanic_3: "/art/jobs/mechanic_3.webp",
  mechanic_4: "/art/jobs/mechanic_4.webp",
  bartender_1: "/art/jobs/bartender_1.webp",
  bartender_2: "/art/jobs/bartender_2.webp",
  bartender_3: "/art/jobs/bartender_3.webp",
  bartender_4: "/art/jobs/bartender_4.webp",
  telecom_1: "/art/jobs/telecom_1.webp",
  telecom_2: "/art/jobs/telecom_2.webp",
  telecom_3: "/art/jobs/telecom_3.webp",
  telecom_4: "/art/jobs/telecom_4.webp",
  hotel_1: "/art/jobs/hotel_1.webp",
  hotel_2: "/art/jobs/hotel_2.webp",
  hotel_3: "/art/jobs/hotel_3.webp",
  hotel_4: "/art/jobs/hotel_4.webp",
  transit_1: "/art/jobs/transit_1.webp",
  transit_2: "/art/jobs/transit_2.webp",
  transit_3: "/art/jobs/transit_3.webp",
  transit_4: "/art/jobs/transit_4.webp",
  pawn_1: "/art/jobs/pawn_1.webp",
  pawn_2: "/art/jobs/pawn_2.webp",
  pawn_3: "/art/jobs/pawn_3.webp",
  pawn_4: "/art/jobs/pawn_4.webp",
};

export const CAREER_ART_EXTRA: Record<string, string> = {
  security: "/art/jobs/security.webp",
  courier: "/art/jobs/courier.webp",
  mechanic: "/art/jobs/mechanic.webp",
  bartender: "/art/jobs/bartender.webp",
  telecom: "/art/jobs/telecom.webp",
  hotel: "/art/jobs/hotel.webp",
  transit: "/art/jobs/transit.webp",
  pawn: "/art/jobs/pawn.webp",
};

export const COURSE_ART_EXTRA: Record<string, string> = {
  se6: "/art/campus/courses/se6.webp",
  se7: "/art/campus/courses/se7.webp",
  se8: "/art/campus/courses/se8.webp",
  se9: "/art/campus/courses/se9.webp",
  cf5: "/art/campus/courses/cf5.webp",
  cf6: "/art/campus/courses/cf6.webp",
  cf7: "/art/campus/courses/cf7.webp",
  cf8: "/art/campus/courses/cf8.webp",
  hl5: "/art/campus/courses/hl5.webp",
  hl6: "/art/campus/courses/hl6.webp",
  hl7: "/art/campus/courses/hl7.webp",
  hl8: "/art/campus/courses/hl8.webp",
  mc5: "/art/campus/courses/mc5.webp",
  mc6: "/art/campus/courses/mc6.webp",
  mc7: "/art/campus/courses/mc7.webp",
  mc8: "/art/campus/courses/mc8.webp",
  le4: "/art/campus/courses/le4.webp",
  le5: "/art/campus/courses/le5.webp",
  le6: "/art/campus/courses/le6.webp",
  le7: "/art/campus/courses/le7.webp",
  sy5: "/art/campus/courses/sy5.webp",
  sy6: "/art/campus/courses/sy6.webp",
  sy7: "/art/campus/courses/sy7.webp",
  sy8: "/art/campus/courses/sy8.webp",
};

export const NPC_ART_EXTRA: Record<string, string> = {
  gr_dealer: "/art/npcs/gr_dealer.webp",
  gr_pit: "/art/npcs/gr_pit.webp",
  ms_welder: "/art/npcs/ms_welder.webp",
  ms_parts: "/art/npcs/ms_parts.webp",
  dr_customs: "/art/npcs/dr_customs.webp",
  dr_crane: "/art/npcs/dr_crane.webp",
  ac_clerk: "/art/npcs/ac_clerk.webp",
  ac_detective: "/art/npcs/ac_detective.webp",
  sy_analyst: "/art/npcs/sy_analyst.webp",
  sy_contractor: "/art/npcs/sy_contractor.webp",
  oc_fence: "/art/npcs/oc_fence.webp",
  oc_enforcer: "/art/npcs/oc_enforcer.webp",
  np_hustler: "/art/npcs/np_hustler.webp",
  np_promoter: "/art/npcs/np_promoter.webp",
  rc_pharmacist: "/art/npcs/rc_pharmacist.webp",
  rc_paramedic: "/art/npcs/rc_paramedic.webp",
};

/** Procedural scene fallbacks for new crimes (CSS when photo missing). */
export const SCENES_EXTRA: Record<string, { bg: string; accent: string; label: string }> = {
  newspaper_rack: { bg: "linear-gradient(145deg,#141210 0%,#2a2418 45%,#0e0e10 100%)", accent: "#a08040", label: "rack" },
  tip_jar: { bg: "linear-gradient(150deg,#141218 0%,#2a2030 40%,#0e0e10 100%)", accent: "#c9a227", label: "tips" },
  atm_skimmer: { bg: "linear-gradient(145deg,#0a0810 0%,#241838 45%,#0c0a10 100%)", accent: "#9060c0", label: "skimmer" },
  data_center: { bg: "linear-gradient(150deg,#0a0810 0%,#241838 40%,#0c0a10 100%)", accent: "#9060c0", label: "rack cage" },
  wire_exchange: { bg: "linear-gradient(145deg,#100c14 0%,#281838 45%,#0c0a10 100%)", accent: "#9060c0", label: "exchange" },
  casino_count: { bg: "linear-gradient(160deg,#140e08 0%,#3a2810 45%,#100c08 100%)", accent: "#d4a017", label: "count room" },
  port_crane: { bg: "linear-gradient(150deg,#0a1014 0%,#143040 50%,#0a0e12 100%)", accent: "#3a90b0", label: "crane" },
  syndicate_ledger: { bg: "linear-gradient(160deg,#120e10 0%,#3a1520 40%,#1a0a10 100%)", accent: "#e05050", label: "ledger" },
};
